var registeredconsumers = true;
// APIACTOR
messageregistry.register('APIACTOR', MESSAGETYPES.API, {
  endpoint: 'string', method: 'string', payload: 'object?', token: 'string?', sender: 'string', tag: 'string'
}, APIBEHAVIOR);
ACTORCONSUMERS['APIACTOR:API'] = APIBEHAVIOR;
ACTORCONSUMERS['APIACTOR:api'] = APIBEHAVIOR;

messageregistry.register('APIACTOR', MESSAGETYPES.FETCH, {
  endpoint: 'string', method: 'string', payload: 'object?', token: 'string?', sender: 'string', tag: 'string'
}, APIBEHAVIOR);
ACTORCONSUMERS['APIACTOR:FETCH'] = APIBEHAVIOR;
ACTORCONSUMERS['APIACTOR:fetch'] = APIBEHAVIOR;

// DEBUGACTOR
messageregistry.register('DEBUGACTOR', MESSAGETYPES.INITOVERLAY, { sender: 'string?', tag: 'string?' }, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:INITOVERLAY'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:init_overlay'] = DEBUGBEHAVIOR;

messageregistry.register('DEBUGACTOR', MESSAGETYPES.SHOW, { error: 'object', continuation: 'object?', sender: 'string?', tag: 'string?' }, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:SHOW'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:show'] = DEBUGBEHAVIOR;

messageregistry.register('DEBUGACTOR', MESSAGETYPES.HIDE, { sender: 'string?', tag: 'string?' }, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:HIDE'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:hide'] = DEBUGBEHAVIOR;

messageregistry.register('DEBUGACTOR', MESSAGETYPES.RECOVER, { sender: 'string?', tag: 'string?' }, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:RECOVER'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:recover'] = DEBUGBEHAVIOR;

messageregistry.register('DEBUGACTOR', MESSAGETYPES.PING, { sender: 'string?', tag: 'string?' }, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:PING'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:ping'] = DEBUGBEHAVIOR;

// ==== ADDED: LOGLINE handler ====
messageregistry.register('DEBUGACTOR', MESSAGETYPES.LOGLINE, {
  level: 'string',
  message: 'string',
  data: 'object?',
  timestamp: 'number',
  prefix: 'string?'
}, DEBUGBEHAVIOR);
ACTORCONSUMERS['DEBUGACTOR:LOGLINE'] = DEBUGBEHAVIOR;
ACTORCONSUMERS['DEBUGACTOR:logline'] = DEBUGBEHAVIOR;
// ==== END ADDED ====

// EXECUTIONACTOR
messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.PIPELINELOADED, { pipelineid: 'string', env: 'object?' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:PIPELINELOADED'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:pipeline_loaded'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.ENVUPDATED, { pipelineid: 'string', env: 'object' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:ENVUPDATED'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:env_updated'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.GETSTATUS, { pipelineid: 'string?' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:GETSTATUS'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:get_status'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.EXECUTEELEMENT, {
  pipelineid: 'string', path: 'array', elementid: 'string', env: 'object', signature: 'object',
  executor: 'function', properties: 'object?', async: 'boolean?', serialized: 'object?',
  programRef: 'string?', elementId: 'string?', origin: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:EXECUTEELEMENT'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:execute_element'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.AWAITTASK, { taskid: 'string' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:AWAITTASK'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:await_task'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.GETTASKS, { pipelineid: 'string?', stageid: 'string?', elementid: 'string?', kind: 'string?' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:GETTASKS'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:get_tasks'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.GETTASKSTATUS, { taskid: 'string' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:GETTASKSTATUS'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:get_task_status'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.CANCELTASK, { taskid: 'string' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:CANCELTASK'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:cancel_task'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.STOPTASK, { taskid: 'string' }, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:STOPTASK'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:stop_task'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.CCCABORT, {
  pipelineid: 'string', path: 'array', elementid: 'string', continuation: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:CCCABORT'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:ccc_abort'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.CCCCONTINUE, {
  pipelineid: 'string', path: 'array', elementid: 'string', continuation: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:CCCCONTINUE'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:ccc_continue'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.CCCRETRY, {
  pipelineid: 'string', path: 'array', elementid: 'string', continuation: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:CCCRETRY'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:ccc_retry'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.TASKSETTLED, {
  taskid: 'string', status: 'string', result: 'any', error: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:TASKSETTLED'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:task_settled'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.RECOVER, {}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:RECOVER'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:recover'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.REGISTERPIPELINE, {
  pipelineid: 'string', dna: 'object?', env: 'object?'
}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:REGISTERPIPELINE'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:register_pipeline'] = EXECUTIONBEHAVIOR;

messageregistry.register('EXECUTIONACTOR', MESSAGETYPES.PING, {}, EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR:PING'] = EXECUTIONBEHAVIOR;
ACTORCONSUMERS['EXECUTIONACTOR:ping'] = EXECUTIONBEHAVIOR;

// HYPERVISORACTOR
messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.LOAD, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:LOAD'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:load'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SAVE, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SAVE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:save'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETENV, { pipelineId: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETENV'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_env'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SETENV, { pipelineId: 'string', env: 'object', stageId: 'string?', elementId: 'string?' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SETENV'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:set_env'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETLATESTENV, { pipelineId: 'string', stageId: 'string', elementId: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETLATESTENV'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_latest_env'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETRENDERHTML, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETRENDERHTML'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_render_html'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SETRENDERHTML, { html: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SETRENDERHTML'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:set_render_html'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETEXECUTIONSTACK, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETEXECUTIONSTACK'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_execution_stack'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SETEXECUTIONSTACK, { stack: 'array' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SETEXECUTIONSTACK'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:set_execution_stack'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETROUTE, { key: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETROUTE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_route'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SETROUTE, { key: 'string', route: 'object?' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SETROUTE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:set_route'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETACTIVEPIPELINES, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETACTIVEPIPELINES'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_active_pipelines'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.REGISTERPIPELINE, { pipelineId: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:REGISTERPIPELINE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:register_pipeline'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.UNREGISTERPIPELINE, { pipelineId: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:UNREGISTERPIPELINE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:unregister_pipeline'] = HYPERVISORBEHAVIOR;

// ==== ADDED: BOOTDNA handler ====
messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.BOOTDNA, {
  dna: 'object',
  pipelineId: 'string',
  options: 'object?',
  sender: 'string',
  tag: 'string'
}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:BOOTDNA'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:bootdna'] = HYPERVISORBEHAVIOR;
// ==== END ADDED ====

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.SETPROGRAM, { programKey: 'string', programSource: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:SETPROGRAM'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:set_program'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.GETPROGRAM, { programKey: 'string' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:GETPROGRAM'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:get_program'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.MARKBOOT, { boot: 'boolean' }, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:MARKBOOT'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:mark_boot'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.EVENTTRIGGERED, {
  pipelineId: 'string', stageId: 'string', stagePath: 'array', eventPayload: 'object'
}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:EVENTTRIGGERED'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:event_triggered'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.PING, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:PING'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:ping'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.RECOVER, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:RECOVER'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:recover'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.ACTIVATEACTORS, {}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:ACTIVATEACTORS'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:activate_actors'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.BOOTPIPELINE, {
  dna: 'object', accessors: 'object?', sinks: 'array', pipelineId: 'string', options: 'object?', firstStage: 'object?'
}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:BOOTPIPELINE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:boot_pipeline'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.COMPILESTAGE, {
  pipeline: 'object', pipelineId: 'string', stageIndex: 'number', stagePath: 'array', briefcase: 'object', env: 'object?', options: 'object?'
}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:COMPILESTAGE'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:compile_stage'] = HYPERVISORBEHAVIOR;

messageregistry.register('HYPERVISORACTOR', MESSAGETYPES.STAGECOMPLETED, {
  pipelineId: 'string', stageId: 'string', env: 'object?', nextStageMessage: 'object?'
}, HYPERVISORBEHAVIOR);
ACTORCONSUMERS['HYPERVISORACTOR:STAGECOMPLETED'] = HYPERVISORBEHAVIOR;
ACTORCONSUMERS['HYPERVISORACTOR:stage_completed'] = HYPERVISORBEHAVIOR;

// RENDERACTOR
messageregistry.register('RENDERACTOR', MESSAGETYPES.RENDER, { id: 'string', renderer: 'function', data: 'any', env: 'object' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:RENDER'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:render'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.CLEAR, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:CLEAR'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:clear'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.HTML, { id: 'string', markup: 'string', append: 'boolean' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:HTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:html'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.REMOVE, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:REMOVE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:remove'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETSTYLES, { id: 'string', styles: 'object' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETSTYLES'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setstyles'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETATTR, { id: 'string', name: 'string', value: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETATTR'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setattr'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.TOGGLECLASS, { id: 'string', classname: 'string', force: 'boolean?' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:TOGGLECLASS'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:toggleclass'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.CRYPTO, { bytes: 'number' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:CRYPTO'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:crypto'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GEOLOCATION, { enablehighaccuracy: 'boolean', timeout: 'number' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GEOLOCATION'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:geolocation'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.PERSISTENCE, { action: 'string', key: 'string?', value: 'string?' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:PERSISTENCE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:persistence'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.CREATEELEMENT, { tag: 'string', props: 'object?' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:CREATEELEMENT'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:createelement'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.CREATECONTAINER, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:CREATECONTAINER'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:createcontainer'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.CREATEFROMHTML, { html: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:CREATEFROMHTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:createfromhtml'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.PROPERTY, { id: 'string', name: 'string', arguments: 'array?' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:PROPERTY'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:property'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETHTML, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETHTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:gethtml'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETVALUE, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETVALUE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getvalue'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETSTYLE, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETSTYLE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getstyle'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETPOSITION, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETPOSITION'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getposition'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETLAYOUT, { id: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETLAYOUT'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getlayout'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETHTML, { id: 'string', value: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETHTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:sethtml'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETPOSITION, { id: 'string', value: 'object' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETPOSITION'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setposition'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETSTYLE, { id: 'string', value: 'object' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETSTYLE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setstyle'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETVALUE, { id: 'string', value: 'any' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETVALUE'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setvalue'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.SETLAYOUT, { id: 'string', value: 'object' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:SETLAYOUT'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:setlayout'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETVIEWPORT, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETVIEWPORT'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getviewport'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETSCREEN, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETSCREEN'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:getscreen'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.MATCHMEDIA, { query: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:MATCHMEDIA'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:matchmedia'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.GETBODYHTML, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:GETBODYHTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:get_body_html'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.RESTOREBODYHTML, { html: 'string' }, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:RESTOREBODYHTML'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:restore_body_html'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.RECOVER, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:RECOVER'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:recover'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.PING, {}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:PING'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:ping'] = RENDERBEHAVIOR;

messageregistry.register('RENDERACTOR', MESSAGETYPES.REGISTEREVENTLISTENER, {
  pipelineId: 'string', stageId: 'string', stagePath: 'array', sourceid: 'string', event: 'string',
  control: 'object', elements: 'array', briefcase: 'object?', options: 'object?'
}, RENDERBEHAVIOR);
ACTORCONSUMERS['RENDERACTOR:REGISTEREVENTLISTENER'] = RENDERBEHAVIOR;
ACTORCONSUMERS['RENDERACTOR:register_event_listener'] = RENDERBEHAVIOR;

// WORLDMAPACTOR
messageregistry.register('WORLDMAPACTOR', MESSAGETYPES.UPDATE, { updates: 'array' }, WORLDMAPBEHAVIOR);
ACTORCONSUMERS['WORLDMAPACTOR:UPDATE'] = WORLDMAPBEHAVIOR;
ACTORCONSUMERS['WORLDMAPACTOR:update'] = WORLDMAPBEHAVIOR;

messageregistry.register('WORLDMAPACTOR', MESSAGETYPES.UPDATEFN, { fn: 'function' }, WORLDMAPBEHAVIOR);
ACTORCONSUMERS['WORLDMAPACTOR:UPDATEFN'] = WORLDMAPBEHAVIOR;
ACTORCONSUMERS['WORLDMAPACTOR:update_fn'] = WORLDMAPBEHAVIOR;

messageregistry.register('WORLDMAPACTOR', MESSAGETYPES.OBSERVE, { observer: 'function' }, WORLDMAPBEHAVIOR);
ACTORCONSUMERS['WORLDMAPACTOR:OBSERVE'] = WORLDMAPBEHAVIOR;
ACTORCONSUMERS['WORLDMAPACTOR:observe'] = WORLDMAPBEHAVIOR;

messageregistry.register('WORLDMAPACTOR', MESSAGETYPES.UNOBSERVE, { observer: 'function' }, WORLDMAPBEHAVIOR);
ACTORCONSUMERS['WORLDMAPACTOR:UNOBSERVE'] = WORLDMAPBEHAVIOR;
ACTORCONSUMERS['WORLDMAPACTOR:unobserve'] = WORLDMAPBEHAVIOR;

messageregistry.register('WORLDMAPACTOR', MESSAGETYPES.GETWORLDMAP, {}, WORLDMAPBEHAVIOR);
ACTORCONSUMERS['WORLDMAPACTOR:GETWORLDMAP'] = WORLDMAPBEHAVIOR;
ACTORCONSUMERS['WORLDMAPACTOR:get_worldmap'] = WORLDMAPBEHAVIOR;

// MAILACTOR
messageregistry.register('MAILACTOR', MESSAGETYPES.SEND, { recipient: 'string', message: 'object' }, MAILBEHAVIOR);
messageregistry.register('MAILACTOR', MESSAGETYPES.ACK, { recipient: 'string', ids: 'array' }, MAILBEHAVIOR);
