var registeredconsumers = true;

// APIACTOR
MESSAGEREGISTRY.register('APIACTOR', MESSAGETYPES.API, {
  ENDPOINT: 'string', METHOD: 'string', PAYLOAD: 'object?', TOKEN: 'string?', SENDER: 'string', TAG: 'string'
}, APIBEHAVIOR);

MESSAGEREGISTRY.register('APIACTOR', MESSAGETYPES.FETCH, {
  ENDPOINT: 'string', METHOD: 'string', PAYLOAD: 'object?', TOKEN: 'string?', SENDER: 'string', TAG: 'string'
}, APIBEHAVIOR);

// DEBUGACTOR
MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.INITOVERLAY, { SENDER: 'string?', TAG: 'string?' }, DEBUGBEHAVIOR);

MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.SHOW, { ERROR: 'object', CONTINUATION: 'object?', SENDER: 'string?', TAG: 'string?' }, DEBUGBEHAVIOR);

MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.HIDE, { SENDER: 'string?', TAG: 'string?' }, DEBUGBEHAVIOR);

MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.RECOVER, { SENDER: 'string?', TAG: 'string?' }, DEBUGBEHAVIOR);

MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.PING, { SENDER: 'string?', TAG: 'string?' }, DEBUGBEHAVIOR);

MESSAGEREGISTRY.register('DEBUGACTOR', MESSAGETYPES.LOGLINE, {
  LEVEL: 'string',
  MESSAGE: 'string',
  DATA: 'object?',
  TIMESTAMP: 'number',
  PREFIX: 'string?'
}, DEBUGBEHAVIOR);

// EXECUTIONACTOR
MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.PIPELINELOADED, { PIPELINEID: 'string', ENV: 'object?' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.ENVUPDATED, { PIPELINEID: 'string', ENV: 'object' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.GETSTATUS, { PIPELINEID: 'string?' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.EXECUTEELEMENT, {
  PIPELINEID: 'string', PATH: 'array', ELEMENTID: 'string', ENV: 'object', SIGNATURE: 'object',
  EXECUTOR: 'function', PROPERTIES: 'object?', ASYNC: 'boolean?', SERIALIZED: 'object?',
  PROGRAMREF: 'string?', ORIGIN: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.AWAITTASK, { TASKID: 'string' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.GETTASKS, { PIPELINEID: 'string?', STAGEID: 'string?', ELEMENTID: 'string?', KIND: 'string?' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.GETTASKSTATUS, { TASKID: 'string' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.CANCELTASK, { TASKID: 'string' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.STOPTASK, { TASKID: 'string' }, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.CCCABORT, {
  PIPELINEID: 'string', PATH: 'array', ELEMENTID: 'string', CONTINUATION: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.CCCCONTINUE, {
  PIPELINEID: 'string', PATH: 'array', ELEMENTID: 'string', CONTINUATION: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.CCCRETRY, {
  PIPELINEID: 'string', PATH: 'array', ELEMENTID: 'string', CONTINUATION: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.TASKSETTLED, {
  TASKID: 'string', STATUS: 'string', RESULT: 'any', ERROR: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.RECOVER, {}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.REGISTERPIPELINE, {
  PIPELINEID: 'string', DNA: 'object?', ENV: 'object?'
}, EXECUTIONBEHAVIOR);

MESSAGEREGISTRY.register('EXECUTIONACTOR', MESSAGETYPES.PING, {}, EXECUTIONBEHAVIOR);

// HYPERVISORACTOR
MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.LOAD, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SAVE, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETENV, { PIPELINEID: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SETENV, { PIPELINEID: 'string', ENV: 'object', STAGEID: 'string?', ELEMENTID: 'string?' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETLATESTENV, { PIPELINEID: 'string', STAGEID: 'string', ELEMENTID: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETRENDERHTML, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SETRENDERHTML, { HTML: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETEXECUTIONSTACK, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SETEXECUTIONSTACK, { STACK: 'array' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETROUTE, { KEY: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SETROUTE, { KEY: 'string', ROUTE: 'object?' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETACTIVEPIPELINES, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.REGISTERPIPELINE, { PIPELINEID: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.UNREGISTERPIPELINE, { PIPELINEID: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.BOOTDNA, {
  DNA: 'object',
  PIPELINEID: 'string',
  OPTIONS: 'object?',
  SENDER: 'string',
  TAG: 'string'
}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.SETPROGRAM, { PROGRAMKEY: 'string', PROGRAMSOURCE: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.GETPROGRAM, { PROGRAMKEY: 'string' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.MARKBOOT, { BOOT: 'boolean' }, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.EVENTTRIGGERED, {
  PIPELINEID: 'string', STAGEID: 'string', STAGEPATH: 'array', EVENTPAYLOAD: 'object'
}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.PING, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.RECOVER, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.ACTIVATEACTORS, {}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.COMPILESTAGE, {
  PIPELINE: 'object', PIPELINEID: 'string', STAGEINDEX: 'number', STAGEPATH: 'array', BRIEFCASE: 'object', ENV: 'object?', OPTIONS: 'object?'
}, HYPERVISORBEHAVIOR);

MESSAGEREGISTRY.register('HYPERVISORACTOR', MESSAGETYPES.STAGECOMPLETED, {
  PIPELINEID: 'string', STAGEID: 'string', ENV: 'object?', NEXTSTAGEMESSAGE: 'object?'
}, HYPERVISORBEHAVIOR);

// RENDERACTOR
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RENDER, { ID: 'string', RENDERER: 'function', DATA: 'any', ENV: 'object' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CLEAR, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.HTML, { ID: 'string', MARKUP: 'string', APPEND: 'boolean' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.REMOVE, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETSTYLES, { ID: 'string', STYLES: 'object' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETATTR, { ID: 'string', NAME: 'string', VALUE: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.TOGGLECLASS, { ID: 'string', CLASSNAME: 'string', FORCE: 'boolean?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CRYPTO, { BYTES: 'number' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GEOLOCATION, { ENABLEHIGHACCURACY: 'boolean', TIMEOUT: 'number' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PERSISTENCE, { ACTION: 'string', KEY: 'string?', VALUE: 'string?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATEELEMENT, { TAG: 'string', PROPS: 'object?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATECONTAINER, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATEFROMHTML, { HTML: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PROPERTY, { ID: 'string', NAME: 'string', ARGUMENTS: 'array?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETHTML, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETVALUE, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETSTYLE, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETPOSITION, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETLAYOUT, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETHTML, { ID: 'string', VALUE: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETPOSITION, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETSTYLE, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETVALUE, { ID: 'string', VALUE: 'any' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETLAYOUT, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETVIEWPORT, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETSCREEN, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.MATCHMEDIA, { QUERY: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETBODYHTML, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RESTOREBODYHTML, { HTML: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RECOVER, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PING, {}, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.REGISTEREVENTLISTENER, {
  PIPELINEID: 'string', STAGEID: 'string', STAGEPATH: 'array', SOURCEID: 'string', EVENT: 'string',
  CONTROL: 'object', ELEMENTS: 'array', BRIEFCASE: 'object?', OPTIONS: 'object?'
}, RENDERBEHAVIOR);

// WORLDMAPACTOR
MESSAGEREGISTRY.register('WORLDMAPACTOR', MESSAGETYPES.UPDATE, { UPDATES: 'array' }, WORLDMAPBEHAVIOR);

MESSAGEREGISTRY.register('WORLDMAPACTOR', MESSAGETYPES.UPDATEFN, { FN: 'function' }, WORLDMAPBEHAVIOR);

MESSAGEREGISTRY.register('WORLDMAPACTOR', MESSAGETYPES.OBSERVE, { OBSERVER: 'function' }, WORLDMAPBEHAVIOR);

MESSAGEREGISTRY.register('WORLDMAPACTOR', MESSAGETYPES.UNOBSERVE, { OBSERVER: 'function' }, WORLDMAPBEHAVIOR);

MESSAGEREGISTRY.register('WORLDMAPACTOR', MESSAGETYPES.GETWORLDMAP, {}, WORLDMAPBEHAVIOR);

// MAILACTOR
MESSAGEREGISTRY.register('MAILACTOR', MESSAGETYPES.SEND, { RECIPIENT: 'string', MESSAGE: 'object' }, MAILBEHAVIOR);
MESSAGEREGISTRY.register('MAILACTOR', MESSAGETYPES.ACK, { RECIPIENT: 'string', IDS: 'array' }, MAILBEHAVIOR);
