// registerconsumers.js — actor consumer registration.
//
// @proposal=P9 (Cycle P9-03) — the HYPERVISORACTOR registrations for
// the DNA-era message types are removed.
//
// @proposal=P-Q — RENDERACTOR registration for LOADSCRIPT added.
//
// @proposal=P-FW-PANEGRAMMAR (Cycle C1) — RENDERACTOR registration for
// PANELAYOUT added.
//
// @proposal=P-PALETTEGENERATE-COMMAND (Cycle C5) — RENDERACTOR
// registration for PALETTEGENERATE added. Interface declares
// RULESET (function) and OVERRIDES (object, optional).
//
// @proposal=P-SETACCENT-HANDLER (Cycle C5) — RENDERACTOR registration
// for SETACCENT added. Interface declares SELECTOR (object),
// PROP (string), HEX (string), REF (any, optional).

var REGISTEREDCONSUMERS = true;

// ... (APIACTOR, DEBUGACTOR, EXECUTIONACTOR, HYPERVISORACTOR unchanged) ...

// RENDERACTOR
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RENDER, { ID: 'string', RENDERER: 'function', DATA: 'any', ENV: 'object' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CLEAR, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.HTML, { ID: 'string', MARKUP: 'string', APPEND: 'boolean' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.REMOVE, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETSTYLES, { ID: 'string', STYLES: 'object' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETATTR, { ID: 'string', NAME: 'string', VALUE: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.TOGGLECLASS, { ID: 'string', CLASSNAME: 'string', FORCE: 'boolean?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CRYPTO, { BYTES: 'number' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GEOLOCATION, { ENABLEHIGHACCURACY: 'boolean', TIMEOUT: 'number' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PERSISTENCE, { ACTION: 'string', KEY: 'string?', VALUE: 'string?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATEELEMENT, { TAG: 'string', PROPS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATECONTAINER, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CREATEFROMHTML, { HTML: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PROPERTY, { ID: 'string', NAME: 'string', ARGUMENTS: 'array?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETHTML, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETELEMENTS, { ID: 'string', TAGNAME: 'string?', LIMIT: 'number?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKOVERFLOW, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKSPACING, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKOVERLAP, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKSCROLLABILITY, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKCONTROLLEDOVERLAY, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CORRECTOVERFLOW, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CORRECTSPACING, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CORRECTOVERLAP, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CORRECTSCROLLABILITY, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CORRECTCONTROLLEDOVERLAY, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.REWRITESTYLEATTRS, { ID: 'string', RULES: 'array' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CONSOLIDATESTYLES, { ID: 'string', SAFEPROPS: 'array?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PANELAYOUT, { ID: 'string', SHAPE: 'string', VIEWPORT: 'object', HEIGHT: 'any?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PALETTEGENERATE, { RULESET: 'function', OVERRIDES: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETACCENT, { SELECTOR: 'object', PROP: 'string', HEX: 'string', REF: 'any?' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.OPTIMIZECONTRAST, { ID: 'string', THEMESTYLES: 'object?', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.OPTIMIZEHARMONY, { ID: 'string', THEMESTYLES: 'object?', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.OPTIMIZETEXTVISIBILITY, { ID: 'string', THEMESTYLES: 'object?', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.OPTIMIZEBUTTONVISIBILITY, { ID: 'string', THEMESTYLES: 'object?', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.VERIFYCONTRAST, { ID: 'string', MINRATIO: 'number?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.VERIFYTEXTVISIBILITY, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.VERIFYBUTTONVISIBILITY, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.VERIFYHARMONY, { ID: 'string', OPTIONS: 'object?' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.CHECKFOCUSVISIBILITY, { ID: 'string' }, RENDERBEHAVIOR);

MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETVALUE, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETSTYLE, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETPOSITION, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETLAYOUT, { ID: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETHTML, { ID: 'string', VALUE: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETPOSITION, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETSTYLE, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETVALUE, { ID: 'string', VALUE: 'any' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.SETLAYOUT, { ID: 'string', VALUE: 'object' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETVIEWPORT, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETSCREEN, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.MATCHMEDIA, { QUERY: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.GETBODYHTML, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RESTOREBODYHTML, { HTML: 'string' }, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.RECOVER, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.PING, {}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.REGISTEREVENTLISTENER, {
  PIPELINEID: 'string', STAGEID: 'string', STAGEPATH: 'array', SOURCEID: 'string', EVENT: 'string',
  CONTROL: 'object', ELEMENTS: 'array', BRIEFCASE: 'object?', OPTIONS: 'object?'
}, RENDERBEHAVIOR);
MESSAGEREGISTRY.register('RENDERACTOR', MESSAGETYPES.LOADSCRIPT, { SRC: 'string' }, RENDERBEHAVIOR);
