function APIBEHAVIOR(ENV, MESSAGE) {
  LOGDEBUG(ENV, '[APIACTOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);

  if (MESSAGE.TYPE === MESSAGETYPES.API || MESSAGE.TYPE === MESSAGETYPES.FETCH) {
    LOGDEBUG(ENV, '[APIACTOR]', 'ACTION:', MESSAGE.TYPE, 'METHOD:', MESSAGE.METHOD, 'ENDPOINT:', MESSAGE.ENDPOINT);

    var UPDATEDAPI = {
      LASTREQUEST: {
        TYPE: MESSAGE.TYPE,
        ENDPOINT: MESSAGE.ENDPOINT,
        METHOD: MESSAGE.METHOD,
        PAYLOAD: MESSAGE.PAYLOAD || {},
        TOKEN: MESSAGE.TOKEN || '',
        TIMESTAMP: Date.now()
      },
      REQUESTCOUNT: (ENV.API && (ENV.API.REQUESTCOUNT || ENV.API.REQUESTCOUNT || ENV.API.requestCount) || 0) + 1
    };

    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'api', VALUE: UPDATEDAPI }]
    }, GENERATETAG(), 'APIACTOR');

    var APICONSTANTS = (typeof CREATEAPICONSTANTS === 'function') ? CREATEAPICONSTANTS() : (typeof CREATEAPICONSTANTS === 'function' ? CREATEAPICONSTANTS() : { APIBASE: 'https://vflkhntzwfovnuyccxow.supabase.co/functions/v1' });
    var APIBASE = APICONSTANTS.APIBASE || APICONSTANTS.APIBASE || '';
    var URL = APIBASE + '/' + MESSAGE.ENDPOINT;
    var ISTEXTUAL = MESSAGE.TYPE === MESSAGETYPES.FETCH;
    var METHOD = String(MESSAGE.METHOD || 'GET').toUpperCase();
    var HEADERS = {
      'Authorization': 'Bearer ' + (MESSAGE.TOKEN || '')
    };
    if (METHOD === 'POST') {
      HEADERS['Content-Type'] = 'application/json';
    }
    if (ISTEXTUAL) {
      HEADERS['Accept'] = 'text/plain, */*';
    }
    var BODY = METHOD === 'POST' ? JSON.stringify(MESSAGE.PAYLOAD || {}) : undefined;

    FETCH(URL, { METHOD: METHOD, HEADERS: HEADERS, BODY: BODY }).then(function(RESPONSE) {
      var STATUS = RESPONSE.STATUS;
      LOGDEBUG(ENV, '[APIACTOR]', 'ACTION RESPONSE STATUS:', STATUS, 'FOR:', MESSAGE.ENDPOINT);
      if (!ISTEXTUAL) {
        return RESPONSE.JSON().then(function(DATA) {
          LOGDEBUG(ENV, '[APIACTOR]', 'ACTION JSON RESPONSE RECEIVED FOR:', MESSAGE.ENDPOINT);
          var RESPONSESPEC = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
          var RESPONSETYPE = (RESPONSESPEC && (RESPONSESPEC.RESPONSETYPE || RESPONSESPEC.RESPONSETYPE)) || 'response';
          SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STATUS: STATUS, DATA: DATA }, 'APIACTOR', RESPONSETYPE);
        });
      }
      return RESPONSE.TEXT().then(function(DATA) {
        LOGDEBUG(ENV, '[APIACTOR]', 'ACTION TEXT RESPONSE RECEIVED FOR:', MESSAGE.ENDPOINT);
        var RESPONSESPEC = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
        var RESPONSETYPE = (RESPONSESPEC && (RESPONSESPEC.RESPONSETYPE || RESPONSESPEC.RESPONSETYPE)) || 'response';
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STATUS: STATUS, DATA: DATA }, 'APIACTOR', RESPONSETYPE);
      });
    }).catch(function(ERR) {
      LOGERROR(ENV, '[APIACTOR]', 'ACTION REQUEST ERROR FOR:', MESSAGE.ENDPOINT, ERR);
      var RESPONSESPEC = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
      var RESPONSETYPE = (RESPONSESPEC && (RESPONSESPEC.RESPONSETYPE || RESPONSESPEC.RESPONSETYPE)) || 'response';
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: ERR.MESSAGE || String(ERR) }, 'APIACTOR', RESPONSETYPE);
    });
  }

  return ENV;
}

function ENQUEUEAPI(ENDPOINT, METHOD, PAYLOAD, OPTIONS, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('APIACTOR', MESSAGETYPES.API, {
    ENDPOINT: ENDPOINT,
    METHOD: METHOD,
    PAYLOAD: PAYLOAD || {},
    TOKEN: (OPTIONS && OPTIONS.TOKEN) || ''
  }, TAG, 'system', RESPONSESPEC);
}

function ENQUEUEFETCH(ENDPOINT, METHOD, PAYLOAD, OPTIONS, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('APIACTOR', MESSAGETYPES.FETCH, {
    ENDPOINT: ENDPOINT,
    METHOD: METHOD,
    PAYLOAD: PAYLOAD || {},
    TOKEN: (OPTIONS && OPTIONS.TOKEN) || ''
  }, TAG, 'system', RESPONSESPEC);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    APIBEHAVIOR: APIBEHAVIOR,
    ENQUEUEAPI: ENQUEUEAPI,
    ENQUEUEFETCH: ENQUEUEFETCH
  };
}
