var DEBUGVERBOSITYCONSTANTS = CREATEVERBOSITYCONSTANTS();

function GETCTX(ERROR, CONT) {
  var ENV = (CONT && CONT.ENVSNAPSHOT) ||
    (CONT && CONT.OPTIONS && CONT.OPTIONS.CONTEXT && CONT.OPTIONS.CONTEXT.ENV) || {};
  return {
    PIPELINEID: ENV.PIPELINEID || ENV.AGENTID ||
      (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.PIPELINEID) || 'UNKNOWNPIPELINE',
    PATH: [
      (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.PIPELINESTAGE) || 'UNKNOWNSTAGE',
      (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.BLOCKID) ||
      (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.ELEMENTID) || 'UNKNOWNELEMENT'
    ],
    ELEMENTID: (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.BLOCKID) ||
      (ERROR && ERROR.DIAGNOSTIC && ERROR.DIAGNOSTIC.ELEMENTID) || 'UNKNOWNELEMENT'
  };
}

function BTN(TEXT, STYLE, ONCLICK) {
  var B = DOCUMENT.CREATEELEMENT('button');
  B.TEXTCONTENT = TEXT;
  B.STYLE.CSSTEXT = 'border:none; padding:10px 20px; cursor:pointer; font-weight:bold; ' + STYLE;
  B.ONCLICK = ONCLICK;
  return B;
}

function ENSUREOVERLAY(DEBUGSLICE) {
  if (!DEBUGSLICE.OVERLAY) {
    var OVERLAY = DOCUMENT.GETELEMENTBYID('debugoverlay');
    if (!OVERLAY) {
      OVERLAY = DOCUMENT.CREATEELEMENT('div');
      OVERLAY.ID = 'debugoverlay';
      OVERLAY.STYLE.CSSTEXT = 'position:fixed;top:0;left:0;width:100vw;height:100vh;background:rgba(0,0,0,0.95);z-index:10000;display:none;flex-direction:column;';
      DOCUMENT.BODY.APPENDCHILD(OVERLAY);
    }
    DEBUGSLICE.OVERLAY = OVERLAY;
  }
  return DEBUGSLICE.OVERLAY;
}

function ENSUREDEBUGSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'debug', function() {
    return {
      OVERLAY: null,
      CURRENTCONTINUATION: null,
      OVERLAYVISIBLE: false,
      CCCSTATE: { CURRENTCONTINUATION: null },
      GLOBALLISTENERSINSTALLED: false
    };
  });
}

// Pure behavior function: (env, message) -> env
function DEBUGBEHAVIOR(ENV, MESSAGE) {
  LOGDEBUG(ENV, '[DEBUGACTOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);

  var DEBUGSLICE = ENSUREDEBUGSLICE(ENV);

  if (MESSAGE.TYPE === MESSAGETYPES.PING) {
    LOGDEBUG(ENV, '[DEBUGACTOR]', 'ACTION PING');
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      var RESPONSESPECPING = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
      var RESPONSETYPEPING = (RESPONSESPECPING && (RESPONSESPECPING.RESPONSETYPE || RESPONSESPECPING.RESPONSETYPE)) || 'response';
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'DEBUGACTOR', RESPONSETYPEPING);
    }
    return ENV;
  }

  if (MESSAGE.TYPE === MESSAGETYPES.INITOVERLAY || MESSAGE.TYPE === MESSAGETYPES.INIT_OVERLAY) {
    LOGDEBUG(ENV, '[DEBUGACTOR]', 'ACTION INITOVERLAY');
    ENSUREOVERLAY(DEBUGSLICE);

    if (!DEBUGSLICE.GLOBALLISTENERSINSTALLED) {
      DEBUGSLICE.GLOBALLISTENERSINSTALLED = true;

      WINDOW.ADDEVENTLISTENER('error', function(E) {
        E.PREVENTDEFAULT();
        LOGWARN(ENV, '[DEBUGACTOR]', 'GLOBAL WINDOW ERROR CAPTURED:', E.ERROR || E);
        SENDINSTRUCTION('DEBUGACTOR', MESSAGETYPES.SHOW, {
          ERROR: E.ERROR || E,
          CONTINUATION: null
        }, null, 'window');
      });

      WINDOW.ADDEVENTLISTENER('unhandledrejection', function(E) {
        if (E.REASON && E.REASON.DIAGNOSTIC) {
          E.PREVENTDEFAULT();
          LOGWARN(ENV, '[DEBUGACTOR]', 'GLOBAL UNHANDLED REJECTION CAPTURED:', E.REASON);
          SENDINSTRUCTION('DEBUGACTOR', MESSAGETYPES.SHOW, {
            ERROR: E.REASON,
            CONTINUATION: E.REASON.DIAGNOSTIC.CONTINUATION || null
          }, null, 'window');
        }
      });
    }

    DEBUGSLICE.OVERLAYVISIBLE = false;
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'debug', VALUE: DEBUGSLICE }]
    }, GENERATETAG(), 'DEBUGACTOR');

    if (MESSAGE.SENDER && MESSAGE.TAG) {
      var RESPONSESPECINIT = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
      var RESPONSETYPEINIT = (RESPONSESPECINIT && (RESPONSESPECINIT.RESPONSETYPE || RESPONSESPECINIT.RESPONSETYPE)) || 'response';
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'DEBUGACTOR', RESPONSETYPEINIT);
    }
    return ENV;
  }

  if (MESSAGE.TYPE === MESSAGETYPES.HIDE) {
    LOGDEBUG(ENV, '[DEBUGACTOR]', 'ACTION HIDE');
    if (DEBUGSLICE.OVERLAY) {
      DEBUGSLICE.OVERLAY.STYLE.DISPLAY = 'none';
      DEBUGSLICE.OVERLAY.INNERHTML = '';
    }
    DEBUGSLICE.OVERLAYVISIBLE = false;
    DEBUGSLICE.CCCSTATE.CURRENTCONTINUATION = null;
    DEBUGSLICE.CURRENTCONTINUATION = null;

    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'debug', VALUE: DEBUGSLICE }]
    }, GENERATETAG(), 'DEBUGACTOR');

    if (MESSAGE.SENDER && MESSAGE.TAG) {
      var RESPONSESPECHIDE = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
      var RESPONSETYPEHIDE = (RESPONSESPECHIDE && (RESPONSESPECHIDE.RESPONSETYPE || RESPONSESPECHIDE.RESPONSETYPE)) || 'response';
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'DEBUGACTOR', RESPONSETYPEHIDE);
    }
    return ENV;
  }

  if (MESSAGE.TYPE === MESSAGETYPES.SHOW) {
    LOGINFO(ENV, '[DEBUGACTOR]', 'ACTION SHOW DEBUG OVERLAY');
    LOGDEBUG(ENV, '[DEBUGACTOR]', 'ACTION SHOW ERROR:', MESSAGE.ERROR, 'CONTINUATION:', MESSAGE.CONTINUATION);
    var OVERLAY = ENSUREOVERLAY(DEBUGSLICE);

    OVERLAY.INNERHTML = FORMATDEBUGTRACE(
      MESSAGE.ERROR,
      (MESSAGE.ERROR && MESSAGE.ERROR.DIAGNOSTIC && MESSAGE.ERROR.DIAGNOSTIC.DEBUGTRACE) || []
    );

    var ACTIONS = DOCUMENT.CREATEELEMENT('div');
    ACTIONS.STYLE.CSSTEXT = 'position:fixed;bottom:40px;right:40px;display:flex;gap:20px;';

    if (MESSAGE.CONTINUATION) {
      var CTX = GETCTX(MESSAGE.ERROR, MESSAGE.CONTINUATION);

      ACTIONS.APPENDCHILD(BTN('RETRY STAGE', 'background:#00ff00;color:#000;', function() {
        LOGDEBUG(ENV, '[DEBUGACTOR]', 'RETRYING STAGE:', CTX);
        OVERLAY.STYLE.DISPLAY = 'none';
        OVERLAY.INNERHTML = '';
        SENDINSTRUCTION('EXECUTIONACTOR', 'CCCRETRY', {
          PIPELINEID: CTX.PIPELINEID,
          PATH: CTX.PATH,
          ELEMENTID: CTX.ELEMENTID,
          CONTINUATION: MESSAGE.CONTINUATION
        }, null, 'DEBUGACTOR');
      }));

      ACTIONS.APPENDCHILD(BTN('CONTINUE', 'background:#4488ff;color:#fff;', function() {
        LOGDEBUG(ENV, '[DEBUGACTOR]', 'CONTINUING STAGE:', CTX);
        OVERLAY.STYLE.DISPLAY = 'none';
        OVERLAY.INNERHTML = '';
        SENDINSTRUCTION('EXECUTIONACTOR', 'CCCCONTINUE', {
          PIPELINEID: CTX.PIPELINEID,
          PATH: CTX.PATH,
          ELEMENTID: CTX.ELEMENTID,
          CONTINUATION: MESSAGE.CONTINUATION
        }, null, 'DEBUGACTOR');
      }));
    }

    ACTIONS.APPENDCHILD(BTN('ABORT', 'background:#ff5555;color:#fff;', function() {
      var ABORTCTX = MESSAGE.CONTINUATION
        ? GETCTX(null, MESSAGE.CONTINUATION)
        : { PIPELINEID: 'unknownpipeline', PATH: ['unknownstage', 'unknownelement'], ELEMENTID: 'unknownelement' };
      LOGDEBUG(ENV, '[DEBUGACTOR]', 'ABORTING STAGE:', ABORTCTX);
      OVERLAY.STYLE.DISPLAY = 'none';
      OVERLAY.INNERHTML = '';
      SENDINSTRUCTION('EXECUTIONACTOR', 'CCCABORT', {
        PIPELINEID: ABORTCTX.PIPELINEID,
        PATH: ABORTCTX.PATH,
        ELEMENTID: ABORTCTX.ELEMENTID,
        CONTINUATION: MESSAGE.CONTINUATION
      }, null, 'DEBUGACTOR');
    }));

    OVERLAY.APPENDCHILD(ACTIONS);
    OVERLAY.STYLE.DISPLAY = 'flex';

    DEBUGSLICE.OVERLAYVISIBLE = true;
    DEBUGSLICE.CCCSTATE.CURRENTCONTINUATION = MESSAGE.CONTINUATION || null;
    DEBUGSLICE.CURRENTCONTINUATION = MESSAGE.CONTINUATION || null;

    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'debug', VALUE: DEBUGSLICE }]
    }, GENERATETAG(), 'DEBUGACTOR');

    if (MESSAGE.SENDER && MESSAGE.TAG) {
      var RESPONSESPECSHOW = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
      var RESPONSETYPESHOW = (RESPONSESPECSHOW && (RESPONSESPECSHOW.RESPONSETYPE || RESPONSESPECSHOW.RESPONSETYPE)) || 'response';
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'DEBUGACTOR', RESPONSETYPESHOW);
    }
    return ENV;
  }

  if (MESSAGE.TYPE === MESSAGETYPES.RECOVER) {
    LOGDEBUG(ENV, '[DEBUGACTOR]', 'ACTION RECOVER DEBUG STATE');
    DBRESTORE('actor:state:debug').then(function(SAVED) {
      var NEWDEBUG = (SAVED !== null && SAVED !== undefined) ? SAVED : {
        OVERLAY: null,
        CURRENTCONTINUATION: null,
        OVERLAYVISIBLE: false,
        CCCSTATE: { CURRENTCONTINUATION: null },
        GLOBALLISTENERSINSTALLED: false
      };
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'debug', VALUE: NEWDEBUG }]
      }, GENERATETAG(), 'DEBUGACTOR');
      if (MESSAGE.SENDER && MESSAGE.TAG) {
        var RESPONSESPECRECOVER = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
        var RESPONSETYPERECOVER = (RESPONSESPECRECOVER && (RESPONSESPECRECOVER.RESPONSETYPE || RESPONSESPECRECOVER.RESPONSETYPE)) || 'response';
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'DEBUGACTOR', RESPONSETYPERECOVER);
      }
    }).catch(function(E) {
      LOGWARN(ENV, '[DEBUGACTOR]', 'STATE RESTORE FAILED:', E);
      if (MESSAGE.SENDER && MESSAGE.TAG) {
        var RESPONSESPECERR = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
        var RESPONSETYPEERR = (RESPONSESPECERR && (RESPONSESPECERR.RESPONSETYPE || RESPONSESPECERR.RESPONSETYPE)) || 'response';
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'DEBUGACTOR', RESPONSETYPEERR);
      }
    });
    return ENV;
  }

  return ENV;
}

function ENQUEUEDEBUGPING(RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('DEBUGACTOR', MESSAGETYPES.PING, {}, TAG, 'system', RESPONSESPEC);
}

function ENQUEUEDEBUGRECOVER(RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('DEBUGACTOR', MESSAGETYPES.RECOVER, {}, TAG, 'system', RESPONSESPEC);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    DEBUGVERBOSITYCONSTANTS: DEBUGVERBOSITYCONSTANTS,
    GETCTX: GETCTX,
    BTN: BTN,
    ENSUREOVERLAY: ENSUREOVERLAY,
    ENSUREDEBUGSLICE: ENSUREDEBUGSLICE,
    DEBUGBEHAVIOR: DEBUGBEHAVIOR,
    ENQUEUEDEBUGPING: ENQUEUEDEBUGPING,
    ENQUEUEDEBUGRECOVER: ENQUEUEDEBUGRECOVER
  };
}
