var EXECUTIONVERBOSITYCONSTANTS = createverbosityconstants();

// @proposal=P21 — bounded task history.
var TASKHISTORYMAX = 200;

function SANITIZEFORSTATE(VALUE, SEEN) {
  if (VALUE === null || VALUE === undefined) return VALUE;
  if (typeof VALUE === 'function') return '[Function]';
  if (typeof HTMLElement !== 'undefined' && VALUE instanceof HTMLElement) return '[DOMNODE]';
  if (typeof Node !== 'undefined' && VALUE instanceof Node) return '[DOMNODE]';
  if (typeof EventTarget !== 'undefined' && VALUE instanceof EventTarget) return '[EventTarget]';
  if (typeof VALUE !== 'object') return VALUE;
  if (SEEN === undefined) SEEN = [];
  if (SEEN.indexOf(VALUE) !== -1) return '[Circular]';
  SEEN.push(VALUE);
  if (Array.isArray(VALUE)) {
    var ARR = VALUE.map(function(ITEM) { return SANITIZEFORSTATE(ITEM, SEEN); });
    SEEN.pop();
    return ARR;
  }
  var OUT = {};
  Object.keys(VALUE).forEach(function(KEY) {
    OUT[KEY] = SANITIZEFORSTATE(VALUE[KEY], SEEN);
  });
  SEEN.pop();
  return OUT;
}

function ENSUREEXECUTIONSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'execution', function() {
    return {
      PIPELINES: {},
      TASKS: {},
      TASKORDER: [],
      TASKINDEX: {},
      TASKCOUNTER: 0,
      HTMLSNAPSHOT: null
    };
  });
}

function NEXTTASKID(EXECSLICE) {
  EXECSLICE.TASKCOUNTER = (EXECSLICE.TASKCOUNTER || 0) + 1;
  return 'TASK' + Date.now() + EXECSLICE.TASKCOUNTER + Math.random().toString(36).slice(2, 8);
}

function ISSETTLED(TASK) {
  if (!TASK) return false;
  var S = TASK.STATUS;
  var TERMINAL = S === 'EXECUTED' || S === 'FAILED' || S === 'CANCELLED' || S === 'STOPPED';
  if (!TERMINAL) return false;
  var CONSUMERS = TASK.CONSUMERS || [];
  return CONSUMERS.length === 0;
}

function SWEEPSETTLEDTASKS(EXECSLICE) {
  if (!EXECSLICE || !EXECSLICE.TASKS) return;
  var KEEP = {};
  var KEEPTASKORDER = [];
  Object.keys(EXECSLICE.TASKS).forEach(function(TID) {
    var T = EXECSLICE.TASKS[TID];
    if (ISSETTLED(T)) {
      EXECSLICE.TASKINDEX[TID] = {
        TASKID: T.TASKID,
        KIND: T.KIND,
        PIPELINEID: T.PIPELINEID,
        ELEMENTID: T.ELEMENTID,
        PARENTTASKID: T.PARENTTASKID,
        STATUS: T.STATUS,
        ORIGIN: T.ORIGIN,
        PROGRAMREF: T.PROGRAMREF
      };
    } else {
      KEEP[TID] = T;
      KEEPTASKORDER.push(TID);
    }
  });
  EXECSLICE.TASKS = KEEP;
  EXECSLICE.TASKORDER = KEEPTASKORDER;
}

function REMOVETASKFROMHISTORY(EXECSLICE, TASKID) {
  var T = EXECSLICE.TASKS[TASKID];
  if (T) {
    EXECSLICE.TASKINDEX[TASKID] = {
      TASKID: T.TASKID,
      KIND: T.KIND,
      PIPELINEID: T.PIPELINEID,
      ELEMENTID: T.ELEMENTID,
      PARENTTASKID: T.PARENTTASKID,
      STATUS: T.STATUS,
      ORIGIN: T.ORIGIN,
      PROGRAMREF: T.PROGRAMREF
    };
    delete EXECSLICE.TASKS[TASKID];
  }
  EXECSLICE.TASKORDER = (EXECSLICE.TASKORDER || []).filter(function(ID) { return ID !== TASKID; });
}

function MAKETASK(EXECSLICE, DESCRIPTOR) {
  var TASKID = NEXTTASKID(EXECSLICE);
  var TASK = {
    TASKID: TASKID,
    KIND: 'element',
    PIPELINEID: DESCRIPTOR.PIPELINEID || null,
    ELEMENTID: DESCRIPTOR.ELEMENTID || null,
    PARENTTASKID: null,
    CHILDTASKIDS: [],
    STATUS: 'WAITING',
    SERIALIZED: DESCRIPTOR.SERIALIZED || null,
    PROGRAMREF: DESCRIPTOR.PROGRAMREF || null,
    ORIGIN: DESCRIPTOR.ORIGIN || null,
    TOKEN: DESCRIPTOR.TOKEN || null,
    STAGEPATH: DESCRIPTOR.STAGEPATH || null,
    CONSUMERS: [],
    RESULT: null,
    ERROR: null
  };
  EXECSLICE.TASKS[TASKID] = TASK;
  if (!EXECSLICE.TASKORDER) EXECSLICE.TASKORDER = [];
  EXECSLICE.TASKORDER.push(TASKID);
  while (EXECSLICE.TASKORDER.length > TASKHISTORYMAX) {
    var OLDEST = EXECSLICE.TASKORDER.shift();
    if (EXECSLICE.TASKS[OLDEST]) {
      REMOVETASKFROMHISTORY(EXECSLICE, OLDEST);
    }
  }
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'MAKETASK CREATED ELEMENT TASK:', TASKID, 'PIPELINEID:', TASK.PIPELINEID, 'ELEMENTID:', TASK.ELEMENTID);
  return TASK;
}

function CANCELTASK(EXECSLICE, TASKID) {
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return;
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'CANCELTASK CANCELLING TASK:', TASKID);
  TASK.STATUS = 'CANCELLED';
  (TASK.CHILDTASKIDS || []).forEach(function(CHILDID) { CANCELTASK(EXECSLICE, CHILDID); });
  var ERR = { ERROR: 'Task cancelled: ' + TASKID };
  (TASK.CONSUMERS || []).forEach(function(CONSUMER) {
    SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, ERR, 'EXECUTIONACTOR');
  });
  TASK.CONSUMERS = [];
  TASK.RESULT = null;
  TASK.ERROR = null;
}

function STOPTASK(EXECSLICE, TASKID) {
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return;
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'STOPTASK STOPPING TASK:', TASKID);
  TASK.STATUS = 'STOPPED';
  var ERR = { ERROR: 'Task stopped: ' + TASKID };
  (TASK.CONSUMERS || []).forEach(function(CONSUMER) {
    SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, ERR, 'EXECUTIONACTOR');
  });
  TASK.CONSUMERS = [];
  TASK.RESULT = null;
  TASK.ERROR = null;
}

function ENSUREPIPELINE(EXECSLICE, PIPELINEID) {
  if (!EXECSLICE.PIPELINES[PIPELINEID]) {
    logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'ENSUREPIPELINE INITIALIZING PIPELINE TRACKING FOR:', PIPELINEID);
    EXECSLICE.PIPELINES[PIPELINEID] = {
      STATUS: 'running',
      ENV: {},
      DNA: null,
      USESELEMENTSNAPSHOTS: false
    };
  }
  return EXECSLICE.PIPELINES[PIPELINEID];
}

function SENDEXECUTIONUPDATE(EXECSLICE) {
  SWEEPSETTLEDTASKS(EXECSLICE);
  SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
    UPDATES: [{ PATH: 'EXECUTION', VALUE: EXECSLICE }]
  }, GENERATETAG(), 'EXECUTIONACTOR');
}

// ============================================================
// §1 — Message handlers (P64)
// ============================================================

function EXECUTIONBEHAVIORPIPELINELOADED(ENV, MESSAGE) {
  loginfo(ENV, '[EXECUTIONACTOR]', 'ACTION PIPELINELOADED:', MESSAGE.PIPELINEID);
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var PIPELINE = ENSUREPIPELINE(EXECSLICE, MESSAGE.PIPELINEID);
  if (MESSAGE.ENV && Object.keys(MESSAGE.ENV).length > 0) PIPELINE.ENV = MESSAGE.ENV;
  PIPELINE.STATUS = 'running';
  SENDEXECUTIONUPDATE(EXECSLICE);
  return ENV;
}

function EXECUTIONBEHAVIORENVUPDATED(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var P3 = ENSUREPIPELINE(EXECSLICE, MESSAGE.PIPELINEID);
  P3.ENV = SANITIZEFORSTATE(MESSAGE.ENV || {});
  SENDEXECUTIONUPDATE(EXECSLICE);
  return ENV;
}

function EXECUTIONBEHAVIORGETSTATUS(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var STATUS = MESSAGE.PIPELINEID ? (EXECSLICE.PIPELINES[MESSAGE.PIPELINEID] || null) : EXECSLICE.PIPELINES;
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, STATUS, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIOREXECUTEELEMENT(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var PIPELINEID = MESSAGE.PIPELINEID;
  var ELEMENTID = MESSAGE.ELEMENTID;
  var PATH = MESSAGE.PATH;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION EXECUTEELEMENT ELEMENT:', ELEMENTID, 'PIPELINE:', PIPELINEID, 'PATH:', PATH);
  var TASK = MAKETASK(EXECSLICE, {
    KIND: 'element',
    PIPELINEID: PIPELINEID,
    ELEMENTID: ELEMENTID,
    SERIALIZED: MESSAGE.SERIALIZED || null,
    PROGRAMREF: MESSAGE.PROGRAMREF || null,
    ORIGIN: MESSAGE.ORIGIN || null,
    TOKEN: MESSAGE.TOKEN || null,
    STAGEPATH: MESSAGE.PATH || null
  });
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    TASK.CONSUMERS = TASK.CONSUMERS || [];
    TASK.CONSUMERS.push({ SENDER: MESSAGE.SENDER, TAG: MESSAGE.TAG });
    logdebug(ENV, '[EXECUTIONACTOR]', 'REGISTERED CONSUMER FOR TASK:', TASK.TASKID, 'SENDER:', MESSAGE.SENDER, 'TAG:', MESSAGE.TAG);
  }
  SENDEXECUTIONUPDATE(EXECSLICE);
  RUNELEMENTTASK(TASK.TASKID, MESSAGE, ENV);
  return ENV;
}

function EXECUTIONBEHAVIORAWAITTASK(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION AWAITTASK TASK:', MESSAGE.TASKID);
  var AWAITTASK = EXECSLICE.TASKS[MESSAGE.TASKID];
  if (!AWAITTASK) {
    var INDEXED = EXECSLICE.TASKINDEX ? EXECSLICE.TASKINDEX[MESSAGE.TASKID] : null;
    if (INDEXED) {
      if (MESSAGE.SENDER && MESSAGE.TAG) {
        var RECHECK = INDEXED.STATUS === 'FAILED' || INDEXED.STATUS === 'CANCELLED' || INDEXED.STATUS === 'STOPPED'
          ? { TASKID: INDEXED.TASKID, PIPELINEID: INDEXED.PIPELINEID, ELEMENTID: INDEXED.ELEMENTID, ERROR: 'Task settled: ' + INDEXED.STATUS }
          : { TASKID: INDEXED.TASKID, PIPELINEID: INDEXED.PIPELINEID, ELEMENTID: INDEXED.ELEMENTID, RESULT: null };
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RECHECK, 'EXECUTIONACTOR');
      }
      return ENV;
    }
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: '[EXECUTIONACTOR] UNKNOWN TASK: ' + MESSAGE.TASKID }, 'EXECUTIONACTOR');
    }
    return ENV;
  }
  if (AWAITTASK.STATUS === 'EXECUTED') {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, AWAITTASK.RESULT || {}, 'EXECUTIONACTOR');
    }
  } else if (AWAITTASK.STATUS === 'FAILED') {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: AWAITTASK.ERROR ? AWAITTASK.ERROR.message : 'TASK FAILED' }, 'EXECUTIONACTOR');
    }
  } else if (AWAITTASK.STATUS === 'CANCELLED') {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: AWAITTASK.ERROR ? AWAITTASK.ERROR.message : 'TASK CANCELLED' }, 'EXECUTIONACTOR');
    }
  } else if (AWAITTASK.STATUS === 'STOPPED') {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: 'TASK STOPPED' }, 'EXECUTIONACTOR');
    }
  } else {
    if (!AWAITTASK.CONSUMERS) AWAITTASK.CONSUMERS = [];
    AWAITTASK.CONSUMERS.push({ SENDER: MESSAGE.SENDER, TAG: MESSAGE.TAG });
    SENDEXECUTIONUPDATE(EXECSLICE);
  }
  return ENV;
}

function EXECUTIONBEHAVIORGETTASKS(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var RESULT = [];
  Object.keys(EXECSLICE.TASKS).forEach(function(TID) {
    var T = EXECSLICE.TASKS[TID];
    if (MESSAGE.PIPELINEID && T.PIPELINEID !== MESSAGE.PIPELINEID) return;
    if (MESSAGE.ELEMENTID && T.ELEMENTID !== MESSAGE.ELEMENTID) return;
    if (MESSAGE.KIND && T.KIND !== MESSAGE.KIND) return;
    RESULT.push({
      TASKID: T.TASKID,
      KIND: T.KIND,
      PIPELINEID: T.PIPELINEID,
      ELEMENTID: T.ELEMENTID,
      PARENTTASKID: T.PARENTTASKID,
      STATUS: T.STATUS,
      ORIGIN: T.ORIGIN,
      PROGRAMREF: T.PROGRAMREF,
      SERIALIZED: T.SERIALIZED,
      CONSUMERCOUNT: (T.CONSUMERS || []).length
    });
  });
  if (EXECSLICE.TASKINDEX) {
    Object.keys(EXECSLICE.TASKINDEX).forEach(function(TID) {
      var T = EXECSLICE.TASKINDEX[TID];
      if (MESSAGE.PIPELINEID && T.PIPELINEID !== MESSAGE.PIPELINEID) return;
      if (MESSAGE.ELEMENTID && T.ELEMENTID !== MESSAGE.ELEMENTID) return;
      if (MESSAGE.KIND && T.KIND !== MESSAGE.KIND) return;
      RESULT.push({
        TASKID: T.TASKID,
        KIND: T.KIND,
        PIPELINEID: T.PIPELINEID,
        ELEMENTID: T.ELEMENTID,
        PARENTTASKID: T.PARENTTASKID,
        STATUS: T.STATUS,
        ORIGIN: T.ORIGIN,
        PROGRAMREF: T.PROGRAMREF,
        SERIALIZED: null,
        CONSUMERCOUNT: 0
      });
    });
  }
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RESULT, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIORGETTASKSTATUS(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  var T2 = EXECSLICE.TASKS[MESSAGE.TASKID];
  if (!T2 && EXECSLICE.TASKINDEX) T2 = EXECSLICE.TASKINDEX[MESSAGE.TASKID];
  var STATUSRESULT = T2 ? {
    TASKID: T2.TASKID,
    KIND: T2.KIND,
    PIPELINEID: T2.PIPELINEID,
    ELEMENTID: T2.ELEMENTID,
    PARENTTASKID: T2.PARENTTASKID,
    STATUS: T2.STATUS,
    ORIGIN: T2.ORIGIN,
    PROGRAMREF: T2.PROGRAMREF,
    SERIALIZED: T2.SERIALIZED || null,
    CONSUMERCOUNT: (T2.CONSUMERS || []).length
  } : null;
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, STATUSRESULT, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIORCANCELTASK(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  CANCELTASK(EXECSLICE, MESSAGE.TASKID);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return ENV;
}

function EXECUTIONBEHAVIORSTOPTASK(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  STOPTASK(EXECSLICE, MESSAGE.TASKID);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return ENV;
}

function EXECUTIONBEHAVIORCCCRETRY(ENV, MESSAGE) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCRETRY PIPELINE:', MESSAGE.PIPELINEID, 'ELEMENT:', MESSAGE.ELEMENTID);
  var RETRYCONTINUATION = MESSAGE.CONTINUATION;
  if (!RETRYCONTINUATION || typeof RETRYCONTINUATION.FN !== 'function') {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
        { ERROR: 'cccretry: no continuation' }, 'EXECUTIONACTOR');
    }
    return ENV;
  }
  try {
    var RETRYRESULT = RETRYCONTINUATION.FN.apply(null, RETRYCONTINUATION.ARGS || []);
    Promise.resolve(RETRYRESULT).then(function(SETTLED) {
      if (MESSAGE.SENDER && MESSAGE.TAG) {
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
          { RESULT: SETTLED || {} }, 'EXECUTIONACTOR');
      }
    }).catch(function(RETRYERR) {
      if (MESSAGE.SENDER && MESSAGE.TAG) {
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
          { ERROR: RETRYERR && RETRYERR.message ? RETRYERR.message : String(RETRYERR) },
          'EXECUTIONACTOR');
      }
    });
  } catch (SYNCERR) {
    if (MESSAGE.SENDER && MESSAGE.TAG) {
      SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
        { ERROR: SYNCERR && SYNCERR.message ? SYNCERR.message : String(SYNCERR) },
        'EXECUTIONACTOR');
    }
  }
  return ENV;
}

function EXECUTIONBEHAVIORCCCCONTINUE(ENV, MESSAGE) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCCONTINUE PIPELINE:', MESSAGE.PIPELINEID, 'ELEMENT:', MESSAGE.ELEMENTID);
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
      { RESULT: {} }, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIORCCCABORT(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCABORT PIPELINE:', MESSAGE.PIPELINEID, 'ELEMENT:', MESSAGE.ELEMENTID);
  if (MESSAGE.PIPELINEID && EXECSLICE.PIPELINES && EXECSLICE.PIPELINES[MESSAGE.PIPELINEID]) {
    EXECSLICE.PIPELINES[MESSAGE.PIPELINEID].STATUS = 'aborted';
    SENDEXECUTIONUPDATE(EXECSLICE);
  }
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG,
      { ERROR: 'pipeline aborted' }, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIORTASKSETTLED(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION TASKSETTLED TASK:', MESSAGE.TASKID, 'STATUS:', MESSAGE.STATUS);
  var TASK4 = EXECSLICE.TASKS[MESSAGE.TASKID];
  if (TASK4) {
    TASK4.STATUS = MESSAGE.STATUS;
    TASK4.RESULT = MESSAGE.RESULT || null;
    TASK4.ERROR = MESSAGE.ERROR || null;

    var CONSUMERS = TASK4.CONSUMERS || [];
    var TASKRESULTTYPE = MESSAGETYPES.TASKRESULT;
    if (MESSAGE.STATUS === 'EXECUTED') {
      CONSUMERS.forEach(function(CONSUMER) {
        SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, MESSAGE.RESULT || {}, 'EXECUTIONACTOR', TASKRESULTTYPE);
      });
    } else if (MESSAGE.STATUS === 'FAILED') {
      CONSUMERS.forEach(function(CONSUMER) {
        SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, { ERROR: MESSAGE.ERROR ? MESSAGE.ERROR.message : 'TASK FAILED' }, 'EXECUTIONACTOR', TASKRESULTTYPE);
      });
    }
    TASK4.CONSUMERS = [];
    TASK4.RESULT = null;
    TASK4.ERROR = null;
    SENDEXECUTIONUPDATE(EXECSLICE);
  }
  return ENV;
}

function EXECUTIONBEHAVIORRECOVER(ENV, MESSAGE) {
  DBRESTORE('actor:state:execution').then(function(SAVED) {
    if (SAVED !== null && SAVED !== undefined) {
      ENV.EXECUTION = SAVED;
    } else {
      ENV.EXECUTION = {
        PIPELINES: {},
        TASKS: {},
        TASKORDER: [],
        TASKINDEX: {},
        TASKCOUNTER: 0,
        HTMLSNAPSHOT: null
      };
    }
    SENDEXECUTIONUPDATE(ENV.EXECUTION);
    if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'EXECUTIONACTOR');
  }).catch(function(E) {
    if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: E.message || String(E) }, 'EXECUTIONACTOR');
  });
  return ENV;
}

function EXECUTIONBEHAVIORREGISTERPIPELINE(ENV, MESSAGE) {
  var EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION REGISTERPIPELINE:', MESSAGE.PIPELINEID);
  var P10 = ENSUREPIPELINE(EXECSLICE, MESSAGE.PIPELINEID);
  P10.USESELEMENTSNAPSHOTS = true;
  if (MESSAGE.ENV) P10.ENV = SANITIZEFORSTATE(MESSAGE.ENV);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return ENV;
}

function EXECUTIONBEHAVIORPING(ENV, MESSAGE) {
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'EXECUTIONACTOR');
  }
  return ENV;
}

function EXECUTIONBEHAVIORDEFAULT(ENV, MESSAGE) {
  logwarn(ENV, '[EXECUTIONACTOR]', 'UNKNOWN MESSAGE TYPE:', MESSAGE.TYPE);
  return ENV;
}

// ============================================================
// §2 — Dispatcher surface (P64)
// ============================================================

var EXECUTIONBEHAVIORDISPATCH = MAKEACTORDISPATCHSURFACE('EXECUTIONACTOR', [
  MAKETYPEDDISPATCH(MESSAGETYPES.PIPELINELOADED, EXECUTIONBEHAVIORPIPELINELOADED),
  MAKETYPEDDISPATCH(MESSAGETYPES.ENVUPDATED, EXECUTIONBEHAVIORENVUPDATED),
  MAKETYPEDDISPATCH(MESSAGETYPES.GETSTATUS, EXECUTIONBEHAVIORGETSTATUS),
  MAKETYPEDDISPATCH(MESSAGETYPES.EXECUTEELEMENT, EXECUTIONBEHAVIOREXECUTEELEMENT),
  MAKETYPEDDISPATCH(MESSAGETYPES.AWAITTASK, EXECUTIONBEHAVIORAWAITTASK),
  MAKETYPEDDISPATCH(MESSAGETYPES.GETTASKS, EXECUTIONBEHAVIORGETTASKS),
  MAKETYPEDDISPATCH(MESSAGETYPES.GETTASKSTATUS, EXECUTIONBEHAVIORGETTASKSTATUS),
  MAKETYPEDDISPATCH(MESSAGETYPES.CANCELTASK, EXECUTIONBEHAVIORCANCELTASK),
  MAKETYPEDDISPATCH(MESSAGETYPES.STOPTASK, EXECUTIONBEHAVIORSTOPTASK),
  MAKETYPEDDISPATCH(MESSAGETYPES.CCCRETRY, EXECUTIONBEHAVIORCCCRETRY),
  MAKETYPEDDISPATCH(MESSAGETYPES.CCCCONTINUE, EXECUTIONBEHAVIORCCCCONTINUE),
  MAKETYPEDDISPATCH(MESSAGETYPES.CCCABORT, EXECUTIONBEHAVIORCCCABORT),
  MAKETYPEDDISPATCH(MESSAGETYPES.TASKSETTLED, EXECUTIONBEHAVIORTASKSETTLED),
  MAKETYPEDDISPATCH(MESSAGETYPES.RECOVER, EXECUTIONBEHAVIORRECOVER),
  MAKETYPEDDISPATCH(MESSAGETYPES.REGISTERPIPELINE, EXECUTIONBEHAVIORREGISTERPIPELINE),
  MAKETYPEDDISPATCH(MESSAGETYPES.PING, EXECUTIONBEHAVIORPING),
  EXECUTIONBEHAVIORDEFAULT
]);

// @proposal=P64 — the actor's behaviour is the surface's dispatch.
function EXECUTIONBEHAVIOR(ENV, MESSAGE) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);
  return EXECUTIONBEHAVIORDISPATCH.DISPATCH(ENV, MESSAGE);
}

// @proposal=P64 — publish the surface and the aggregate; self-register.
REGISTERACTORSURFACE('EXECUTIONACTOR', EXECUTIONBEHAVIORDISPATCH);
REGISTERAGGREGATEBEHAVIOR('EXECUTIONACTOR', EXECUTIONBEHAVIOR);
ACTORCONSUMERS['EXECUTIONACTOR'] = EXECUTIONBEHAVIOR;

// ============================================================
// §3 — Task settlement (unchanged)
// ============================================================

function SETTLETASK(TASKID, STATUS, RESULT, ERROR, ENV) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'SETTLETASK TASK:', TASKID, 'STATUS:', STATUS);
  var EXECSLICE = ENV && ENV.execution;
  if (!EXECSLICE) {
    EXECSLICE = ENSUREEXECUTIONSLICE(ENV);
  }
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return;
  TASK.STATUS = STATUS;
  TASK.RESULT = RESULT || null;
  TASK.ERROR = ERROR || null;
  var CONSUMERS = TASK.CONSUMERS || [];
  var TASKRESULTTYPE = MESSAGETYPES.TASKRESULT;

  var RESPONSEPAYLOAD;
  if (STATUS === 'EXECUTED') {
    RESPONSEPAYLOAD = {
      TASKID: TASKID,
      PIPELINEID: TASK.PIPELINEID,
      ELEMENTID: TASK.ELEMENTID,
      RESULT: RESULT || {}
    };
    CONSUMERS.forEach(function(CONSUMER) {
      SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, RESPONSEPAYLOAD, 'EXECUTIONACTOR', TASKRESULTTYPE);
    });
    SENDINSTRUCTION('BROADCAST', MESSAGETYPES.BLOCKEXECUTED, {
      PIPELINEID: TASK.PIPELINEID || null,
      STAGEPATH: TASK.STAGEPATH || null,
      ELEMENTID: TASK.ELEMENTID || null,
      TOKEN: TASK.TOKEN || null,
      RESULT: RESULT || {}
    }, GENERATETAG(), 'EXECUTIONACTOR');
  } else if (STATUS === 'FAILED') {
    RESPONSEPAYLOAD = {
      TASKID: TASKID,
      PIPELINEID: TASK.PIPELINEID,
      ELEMENTID: TASK.ELEMENTID,
      ERROR: {
        MESSAGE: ERROR ? ERROR.message : 'TASK FAILED',
        DIAGNOSTIC: (ERROR && ERROR.diagnostic) ? ERROR.diagnostic : {}
      }
    };
    CONSUMERS.forEach(function(CONSUMER) {
      SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, RESPONSEPAYLOAD, 'EXECUTIONACTOR', TASKRESULTTYPE);
    });
    SENDINSTRUCTION('BROADCAST', MESSAGETYPES.BLOCKFAILED, {
      PIPELINEID: TASK.PIPELINEID || null,
      STAGEPATH: TASK.STAGEPATH || null,
      ELEMENTID: TASK.ELEMENTID || null,
      TOKEN: TASK.TOKEN || null,
      ERROR: ERROR ? ERROR.message : 'TASK FAILED',
      DIAGNOSTIC: (ERROR && ERROR.diagnostic) ? ERROR.diagnostic : {}
    }, GENERATETAG(), 'EXECUTIONACTOR');
  }
  TASK.CONSUMERS = [];
  TASK.RESULT = null;
  TASK.ERROR = null;
  SENDEXECUTIONUPDATE(EXECSLICE);
  logdebug(ENV, '[EXECUTIONACTOR]', 'SETTLETASK COMPLETED:', TASKID, 'CONSUMERS NOTIFIED:', CONSUMERS.length);
}

function RUNELEMENTTASK(TASKID, DESCRIPTOR, ENV) {
  var EXECUTIONCONTEXT = {
    ENV: DESCRIPTOR.ENV || {},
    INPUTS: (DESCRIPTOR.SIGNATURE && (DESCRIPTOR.SIGNATURE.inputs || DESCRIPTOR.SIGNATURE.INPUTS)) || [],
    OUTPUTS: (DESCRIPTOR.SIGNATURE && (DESCRIPTOR.SIGNATURE.outputs || DESCRIPTOR.SIGNATURE.OUTPUTS)) || {},
    PROPERTIES: DESCRIPTOR.PROPERTIES || {}
  };

  logdebug(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK START:', TASKID, DESCRIPTOR.ELEMENTID, 'PIPELINE:', DESCRIPTOR.PIPELINEID);

  var EXECUTOR = DESCRIPTOR.EXECUTOR;
  if (typeof EXECUTOR !== 'function') {
    var FAILUREERROR = new Error('[EXECUTIONACTOR] DESCRIPTOR.EXECUTOR is not a function');
    SETTLETASK(TASKID, 'FAILED', null, FAILUREERROR, ENV);
    return;
  }

  var EXECUTIONPROMISE;
  try {
    EXECUTIONPROMISE = Promise.resolve(EXECUTOR(EXECUTIONCONTEXT));
  } catch (SYNCERR) {
    EXECUTIONPROMISE = Promise.reject(SYNCERR);
  }

  EXECUTIONPROMISE.then(function(RESULT) {
    logdebug(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK COMPLETED:', TASKID, DESCRIPTOR.ELEMENTID);
    SETTLETASK(TASKID, 'EXECUTED', RESULT || {}, null, ENV);
  }).catch(function(ERR) {
    logerror(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK FAILED:', TASKID, DESCRIPTOR.ELEMENTID, ERR);
    SETTLETASK(TASKID, 'FAILED', null, ERR, ENV);
  });
}

// ============================================================
// §4 — Producers (unchanged)
// ============================================================

function ENQUEUEEXECUTIONPIPELINELOADED(PIPELINEID, ENV, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.PIPELINELOADED, { PIPELINEID: PIPELINEID, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONSUBMIT(DESCRIPTOR, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.EXECUTEELEMENT, DESCRIPTOR, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONAWAITTASK(TASKID, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.AWAITTASK, { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONGETTASKS(FILTERS, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.GETTASKS, FILTERS || {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONGETTASKSTATUS(TASKID, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.GETTASKSTATUS, { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONCANCELTASK(TASKID, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.CANCELTASK, { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONSTOPTASK(TASKID, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.STOPTASK, { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONGETSTATUS(PIPELINEID, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.GETSTATUS, { PIPELINEID: PIPELINEID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONENVUPDATED(PIPELINEID, ENV, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.ENVUPDATED, { PIPELINEID: PIPELINEID, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONCCCABORT(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.CCCABORT, { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONCCCCONTINUE(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.CCCCONTINUE, { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONCCCRETRY(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.CCCRETRY, { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONREGISTERPIPELINE(PIPELINEID, DNA, ENV, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.REGISTERPIPELINE, { PIPELINEID: PIPELINEID, DNA: DNA, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONRECOVER(RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.RECOVER, {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}
function ENQUEUEEXECUTIONPING(RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('EXECUTIONACTOR', MESSAGETYPES.PING, {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC);
}

// ============================================================
// §5 — Actor handle surface (P4, unchanged)
// ============================================================

var EXECUTIONACTORHANDLE = null;

function EXECUTIONACTORHANDLEINSTANCE() {
  if (!EXECUTIONACTORHANDLE) {
    EXECUTIONACTORHANDLE = CREATEACTORHANDLE('EXECUTIONACTOR');
  }
  return EXECUTIONACTORHANDLE;
}

function SUBMIT(ACTION) { return EXECUTIONACTORHANDLEINSTANCE().SUBMIT(ACTION); }
function EXPECT(ID, INTERVAL, TIMEOUT) { return EXECUTIONACTORHANDLEINSTANCE().EXPECT(ID, INTERVAL, TIMEOUT); }
function GETACTIONRESULT(ID) { return EXECUTIONACTORHANDLEINSTANCE().GETACTIONRESULT(ID); }

function STARTEXECUTIONACTOR(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS :
      (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      if (ENV) ENV.VERBOSITY = LVL;
    }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('EXECUTIONACTOR', EXECUTIONBEHAVIOR, MESSAGE); },
    SUBMIT: SUBMIT,
    EXPECT: EXPECT,
    GETACTIONRESULT: GETACTIONRESULT
  };
}

function ENSUREEXECUTIONACTORREADY(OPTIONS) {
  return Promise.resolve(STARTEXECUTIONACTOR(OPTIONS));
}
