var PIPELINELOADEDTYPE = messagetype('PIPELINELOADED', {
  PIPELINEID: stringtype(),
  ENV: optionaltype(objecttype())
});
var ENVUPDATEDTYPE = messagetype('ENVUPDATED', {
  PIPELINEID: stringtype(),
  ENV: objecttype()
});
var GETSTATUSTYPE = messagetype('GETSTATUS', {
  PIPELINEID: optionaltype(stringtype())
});
var EXECUTEELEMENTTYPE = messagetype('EXECUTEELEMENT', {
  PIPELINEID: stringtype(),
  PATH: arraytype(),
  ELEMENTID: stringtype(),
  ENV: objecttype(),
  SIGNATURE: objecttype(),
  EXECUTOR: functiontype(),
  PROPERTIES: optionaltype(objecttype()),
  ASYNC: optionaltype(booleantype()),
  SERIALIZED: optionaltype(objecttype()),
  PROGRAMREF: optionaltype(stringtype()),
  ORIGIN: optionaltype(objecttype()),
  TOKEN: optionaltype(stringtype())
});
var AWAITTASKTYPE = messagetype('AWAITTASK', {
  TASKID: stringtype()
});
var GETTASKSTYPE = messagetype('GETTASKS', {
  PIPELINEID: optionaltype(stringtype()),
  STAGEID: optionaltype(stringtype()),
  ELEMENTID: optionaltype(stringtype()),
  KIND: optionaltype(stringtype())
});
var GETTASKSTATUSTYPE = messagetype('GETTASKSTATUS', {
  TASKID: stringtype()
});
var CANCELTASKTYPE = messagetype('CANCELTASK', {
  TASKID: stringtype()
});
var STOPTASKTYPE = messagetype('STOPTASK', {
  TASKID: stringtype()
});
var CCCABORTTYPE = messagetype('CCCABORT', {
  PIPELINEID: stringtype(),
  PATH: arraytype(),
  ELEMENTID: stringtype(),
  CONTINUATION: optionaltype(objecttype())
});
var CCCCONTINUETYPE = messagetype('CCCCONTINUE', {
  PIPELINEID: stringtype(),
  PATH: arraytype(),
  ELEMENTID: stringtype(),
  CONTINUATION: optionaltype(objecttype())
});
var CCCRETRYTYPE = messagetype('CCCRETRY', {
  PIPELINEID: stringtype(),
  PATH: arraytype(),
  ELEMENTID: stringtype(),
  CONTINUATION: optionaltype(objecttype())
});
var TASKSETTLEDTYPE = messagetype('TASKSETTLED', {
  TASKID: stringtype(),
  STATUS: stringtype(),
  RESULT: anytype(),
  ERROR: optionaltype(objecttype())
});
var REGISTERPIPELINETYPE = messagetype('REGISTERPIPELINE', {
  PIPELINEID: stringtype(),
  DNA: optionaltype(objecttype()),
  ENV: optionaltype(objecttype())
});
var TASKRESULTTYPE = messagetype('TASKRESULT', {});

REGISTERMESSAGETYPE(PIPELINELOADEDTYPE);
REGISTERMESSAGETYPE(ENVUPDATEDTYPE);
REGISTERMESSAGETYPE(GETSTATUSTYPE);
REGISTERMESSAGETYPE(EXECUTEELEMENTTYPE);
REGISTERMESSAGETYPE(AWAITTASKTYPE);
REGISTERMESSAGETYPE(GETTASKSTYPE);
REGISTERMESSAGETYPE(GETTASKSTATUSTYPE);
REGISTERMESSAGETYPE(CANCELTASKTYPE);
REGISTERMESSAGETYPE(STOPTASKTYPE);
REGISTERMESSAGETYPE(CCCABORTTYPE);
REGISTERMESSAGETYPE(CCCCONTINUETYPE);
REGISTERMESSAGETYPE(CCCRETRYTYPE);
REGISTERMESSAGETYPE(TASKSETTLEDTYPE);
REGISTERMESSAGETYPE(REGISTERPIPELINETYPE);
REGISTERMESSAGETYPE(TASKRESULTTYPE);

REGISTERRESPONSETYPE('TASKRESULT');

// @proposal=P21 — bounded task history.
var TASKHISTORYMAX = 200;

function SANITIZEFORSTATE(VALUE, SEEN) {
  if (VALUE === null || VALUE === undefined) return VALUE;
  if (typeof VALUE === 'function') return '[Function]';
  if (typeof HTMLElement !== 'undefined' && VALUE instanceof HTMLElement) return '[DOMNODE]';
  if (typeof Node !== 'undefined' && VALUE instanceof Node) return '[DOMNODE]';
  if (typeof EventTarget !== 'undefined' && VALUE instanceof EventTarget) return '[EventTarget]';
  if (typeof VALUE !== 'object') return VALUE;
  if (SEEN === undefined) SEEN = [];
  if (SEEN.indexOf(VALUE) !== -1) return '[Circular]';
  SEEN.push(VALUE);
  if (Array.isArray(VALUE)) { var ARR = VALUE.map(function(ITEM) { return SANITIZEFORSTATE(ITEM, SEEN); }); SEEN.pop(); return ARR; }
  var OUT = {};
  Object.keys(VALUE).forEach(function(KEY) { OUT[KEY] = SANITIZEFORSTATE(VALUE[KEY], SEEN); });
  SEEN.pop();
  return OUT;
}

function ENSUREEXECUTIONSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'execution', function() {
    return { PIPELINES: {}, TASKS: {}, TASKORDER: [], TASKINDEX: {}, TASKCOUNTER: 0, HTMLSNAPSHOT: null };
  });
}

function NEXTTASKID(EXECSLICE) {
  EXECSLICE.TASKCOUNTER = (EXECSLICE.TASKCOUNTER || 0) + 1;
  return 'TASK' + Date.now() + EXECSLICE.TASKCOUNTER + Math.random().toString(36).slice(2, 8);
}

function ISSETTLED(TASK) {
  if (!TASK) return false;
  var S = TASK.STATUS;
  var TERMINAL = S === 'EXECUTED' || S === 'FAILED' || S === 'CANCELLED' || S === 'STOPPED';
  if (!TERMINAL) return false;
  var CONSUMERS = TASK.CONSUMERS || [];
  return CONSUMERS.length === 0;
}

function SWEEPSETTLEDTASKS(EXECSLICE) {
  if (!EXECSLICE || !EXECSLICE.TASKS) return;
  var KEEP = {};
  var KEEPTASKORDER = [];
  Object.keys(EXECSLICE.TASKS).forEach(function(TID) {
    var T = EXECSLICE.TASKS[TID];
    if (ISSETTLED(T)) {
      EXECSLICE.TASKINDEX[TID] = { TASKID: T.TASKID, KIND: T.KIND, PIPELINEID: T.PIPELINEID, ELEMENTID: T.ELEMENTID, PARENTTASKID: T.PARENTTASKID, STATUS: T.STATUS, ORIGIN: T.ORIGIN, PROGRAMREF: T.PROGRAMREF };
    } else {
      KEEP[TID] = T;
      KEEPTASKORDER.push(TID);
    }
  });
  EXECSLICE.TASKS = KEEP;
  EXECSLICE.TASKORDER = KEEPTASKORDER;
}

function REMOVETASKFROMHISTORY(EXECSLICE, TASKID) {
  var T = EXECSLICE.TASKS[TASKID];
  if (T) {
    EXECSLICE.TASKINDEX[TASKID] = { TASKID: T.TASKID, KIND: T.KIND, PIPELINEID: T.PIPELINEID, ELEMENTID: T.ELEMENTID, PARENTTASKID: T.PARENTTASKID, STATUS: T.STATUS, ORIGIN: T.ORIGIN, PROGRAMREF: T.PROGRAMREF };
    delete EXECSLICE.TASKS[TASKID];
  }
  EXECSLICE.TASKORDER = (EXECSLICE.TASKORDER || []).filter(function(ID) { return ID !== TASKID; });
}

function TRIMTASKORDER(EXECSLICE) {
  function STEP() {
    if (EXECSLICE.TASKORDER.length <= TASKHISTORYMAX) return null;
    var OLDEST = EXECSLICE.TASKORDER.shift();
    if (EXECSLICE.TASKS[OLDEST]) REMOVETASKFROMHISTORY(EXECSLICE, OLDEST);
    return STEP;
  }
  return trampoline(STEP)();
}

function MAKETASK(EXECSLICE, DESCRIPTOR) {
  var TASKID = NEXTTASKID(EXECSLICE);
  var TASK = {
    TASKID: TASKID,
    KIND: 'element',
    PIPELINEID: DESCRIPTOR.PIPELINEID || null,
    ELEMENTID: DESCRIPTOR.ELEMENTID || null,
    PARENTTASKID: null,
    CHILDTASKIDS: [],
    STATUS: 'WAITING',
    SERIALIZED: DESCRIPTOR.SERIALIZED || null,
    PROGRAMREF: DESCRIPTOR.PROGRAMREF || null,
    ORIGIN: DESCRIPTOR.ORIGIN || null,
    TOKEN: DESCRIPTOR.TOKEN || null,
    STAGEPATH: DESCRIPTOR.STAGEPATH || null,
    CONSUMERS: [],
    RESULT: null,
    ERROR: null,
    SETTLE_SIGNAL: { PROMISE: null, RESOLVE: null }
  };
  TASK.SETTLE_SIGNAL.PROMISE = new Promise(function(RESOLVE) {
    TASK.SETTLE_SIGNAL.RESOLVE = RESOLVE;
  });
  EXECSLICE.TASKS[TASKID] = TASK;
  if (!EXECSLICE.TASKORDER) EXECSLICE.TASKORDER = [];
  EXECSLICE.TASKORDER.push(TASKID);
  TRIMTASKORDER(EXECSLICE);
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'MAKETASK CREATED ELEMENT TASK:', TASKID, 'PIPELINEID:', TASK.PIPELINEID, 'ELEMENTID:', TASK.ELEMENTID);
  return TASK;
}

function CANCELTASK(EXECSLICE, TASKID) {
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return;
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'CANCELTASK CANCELLING TASK:', TASKID);
  TASK.STATUS = 'CANCELLED';
  (TASK.CHILDTASKIDS || []).forEach(function(CHILDID) { CANCELTASK(EXECSLICE, CHILDID); });
  var ERR = { ERROR: 'Task cancelled: ' + TASKID };
  (TASK.CONSUMERS || []).forEach(function(CONSUMER) { SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, ERR, 'EXECUTIONACTOR'); });
  TASK.CONSUMERS = [];
  TASK.RESULT = null;
  TASK.ERROR = null;
  if (TASK.SETTLE_SIGNAL && TASK.SETTLE_SIGNAL.RESOLVE) {
    TASK.SETTLE_SIGNAL.RESOLVE({ STATUS: 'CANCELLED', RESULT: null, ERROR: { message: 'Task cancelled: ' + TASKID } });
    TASK.SETTLE_SIGNAL.RESOLVE = null;
  }
}

function STOPTASK(EXECSLICE, TASKID) {
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return;
  logdebug(EXECSLICE, '[EXECUTIONACTOR]', 'STOPTASK STOPPING TASK:', TASKID);
  TASK.STATUS = 'STOPPED';
  var ERR = { ERROR: 'Task stopped: ' + TASKID };
  (TASK.CONSUMERS || []).forEach(function(CONSUMER) { SENDRESPONSE(CONSUMER.SENDER, CONSUMER.TAG, ERR, 'EXECUTIONACTOR'); });
  TASK.CONSUMERS = [];
  TASK.RESULT = null;
  TASK.ERROR = null;
  if (TASK.SETTLE_SIGNAL && TASK.SETTLE_SIGNAL.RESOLVE) {
    TASK.SETTLE_SIGNAL.RESOLVE({ STATUS: 'STOPPED', RESULT: null, ERROR: { message: 'Task stopped: ' + TASKID } });
    TASK.SETTLE_SIGNAL.RESOLVE = null;
  }
}

function ENSUREPIPELINE(EXECSLICE, PIPELINEID) {
  if (!EXECSLICE.PIPELINES[PIPELINEID]) {
    EXECSLICE.PIPELINES[PIPELINEID] = { STATUS: 'running', ENV: {}, DNA: null, USESELEMENTSNAPSHOTS: false };
  }
  return EXECSLICE.PIPELINES[PIPELINEID];
}

function SENDEXECUTIONUPDATE(EXECSLICE) {
  SWEEPSETTLEDTASKS(EXECSLICE);
  SENDINSTRUCTION('WORLDMAPACTOR', 'UPDATE', {
    UPDATES: [{ PATH: 'EXECUTION', VALUE: EXECSLICE }]
  }, GENERATETAG(), 'EXECUTIONACTOR');
}

// ============================================================
// §1 — Message handlers
// ============================================================

function EXECUTIONBEHAVIORPIPELINELOADED(ENV, ARGS) {
  loginfo(ENV, '[EXECUTIONACTOR]', 'ACTION PIPELINELOADED:', ARGS.PIPELINEID);
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  var PIPELINE = ENSUREPIPELINE(EXECSLICE, ARGS.PIPELINEID);
  if (ARGS.ENV && Object.keys(ARGS.ENV).length > 0) PIPELINE.ENV = ARGS.ENV;
  PIPELINE.STATUS = 'running';
  SENDEXECUTIONUPDATE(EXECSLICE);
  return NEXTENV;
}

function EXECUTIONBEHAVIORENVUPDATED(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  var P3 = ENSUREPIPELINE(EXECSLICE, ARGS.PIPELINEID);
  P3.ENV = SANITIZEFORSTATE(ARGS.ENV || {});
  SENDEXECUTIONUPDATE(EXECSLICE);
  return NEXTENV;
}

function EXECUTIONBEHAVIORGETSTATUS(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  var STATUS = ARGS.PIPELINEID ? (EXECSLICE.PIPELINES[ARGS.PIPELINEID] || null) : EXECSLICE.PIPELINES;
  return { ENV: NEXTENV, RESPONSE: STATUS };
}

function EXECUTIONBEHAVIOREXECUTEELEMENT(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION EXECUTEELEMENT ELEMENT:', ARGS.ELEMENTID, 'PIPELINE:', ARGS.PIPELINEID, 'PATH:', ARGS.PATH);
  var TASK = MAKETASK(EXECSLICE, {
    KIND: 'element',
    PIPELINEID: ARGS.PIPELINEID,
    ELEMENTID: ARGS.ELEMENTID,
    SERIALIZED: ARGS.SERIALIZED || null,
    PROGRAMREF: ARGS.PROGRAMREF || null,
    ORIGIN: ARGS.ORIGIN || null,
    TOKEN: ARGS.TOKEN || null,
    STAGEPATH: ARGS.PATH || null
  });
  SENDEXECUTIONUPDATE(EXECSLICE);
  return RUNELEMENTTASK(TASK.TASKID, ARGS, NEXTENV);
}

function EXECUTIONBEHAVIORAWAITTASK(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION AWAITTASK TASK:', ARGS.TASKID);
  var TASK = EXECSLICE.TASKS[ARGS.TASKID];
  if (!TASK) {
    var INDEXED = EXECSLICE.TASKINDEX ? EXECSLICE.TASKINDEX[ARGS.TASKID] : null;
    if (INDEXED) {
      var RECHECK = (INDEXED.STATUS === 'FAILED' || INDEXED.STATUS === 'CANCELLED' || INDEXED.STATUS === 'STOPPED')
        ? { TASKID: INDEXED.TASKID, PIPELINEID: INDEXED.PIPELINEID, ELEMENTID: INDEXED.ELEMENTID, ERROR: 'Task settled: ' + INDEXED.STATUS }
        : { TASKID: INDEXED.TASKID, PIPELINEID: INDEXED.PIPELINEID, ELEMENTID: INDEXED.ELEMENTID, RESULT: null };
      return { ENV: NEXTENV, RESPONSE: RECHECK };
    }
    return { ENV: NEXTENV, RESPONSE: { ERROR: '[EXECUTIONACTOR] UNKNOWN TASK: ' + ARGS.TASKID } };
  }
  if (TASK.STATUS === 'EXECUTED') {
    return { ENV: NEXTENV, RESPONSE: TASK.RESULT || {} };
  }
  if (TASK.STATUS === 'FAILED') {
    return { ENV: NEXTENV, RESPONSE: { ERROR: TASK.ERROR ? TASK.ERROR.message : 'TASK FAILED' } };
  }
  if (TASK.STATUS === 'CANCELLED') {
    return { ENV: NEXTENV, RESPONSE: { ERROR: TASK.ERROR ? TASK.ERROR.message : 'TASK CANCELLED' } };
  }
  if (TASK.STATUS === 'STOPPED') {
    return { ENV: NEXTENV, RESPONSE: { ERROR: 'TASK STOPPED' } };
  }
  // Pending: chain off the settle signal.
  var CAPTURED_ENV = NEXTENV;
  return TASK.SETTLE_SIGNAL.PROMISE.then(function(SETTLEMENT) {
    if (SETTLEMENT.STATUS === 'EXECUTED') return { ENV: CAPTURED_ENV, RESPONSE: SETTLEMENT.RESULT || {} };
    return { ENV: CAPTURED_ENV, RESPONSE: { ERROR: SETTLEMENT.ERROR && SETTLEMENT.ERROR.message ? SETTLEMENT.ERROR.message : ('TASK ' + SETTLEMENT.STATUS) } };
  });
}

function EXECUTIONBEHAVIORGETTASKS(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  var RESULT = [];
  Object.keys(EXECSLICE.TASKS).forEach(function(TID) {
    var T = EXECSLICE.TASKS[TID];
    if (ARGS.PIPELINEID && T.PIPELINEID !== ARGS.PIPELINEID) return;
    if (ARGS.ELEMENTID && T.ELEMENTID !== ARGS.ELEMENTID) return;
    if (ARGS.KIND && T.KIND !== ARGS.KIND) return;
    RESULT.push({ TASKID: T.TASKID, KIND: T.KIND, PIPELINEID: T.PIPELINEID, ELEMENTID: T.ELEMENTID, PARENTTASKID: T.PARENTTASKID, STATUS: T.STATUS, ORIGIN: T.ORIGIN, PROGRAMREF: T.PROGRAMREF, SERIALIZED: T.SERIALIZED, CONSUMERCOUNT: (T.CONSUMERS || []).length });
  });
  if (EXECSLICE.TASKINDEX) {
    Object.keys(EXECSLICE.TASKINDEX).forEach(function(TID) {
      var T = EXECSLICE.TASKINDEX[TID];
      if (ARGS.PIPELINEID && T.PIPELINEID !== ARGS.PIPELINEID) return;
      if (ARGS.ELEMENTID && T.ELEMENTID !== ARGS.ELEMENTID) return;
      if (ARGS.KIND && T.KIND !== ARGS.KIND) return;
      RESULT.push({ TASKID: T.TASKID, KIND: T.KIND, PIPELINEID: T.PIPELINEID, ELEMENTID: T.ELEMENTID, PARENTTASKID: T.PARENTTASKID, STATUS: T.STATUS, ORIGIN: T.ORIGIN, PROGRAMREF: T.PROGRAMREF, SERIALIZED: null, CONSUMERCOUNT: 0 });
    });
  }
  return { ENV: NEXTENV, RESPONSE: RESULT };
}

function EXECUTIONBEHAVIORGETTASKSTATUS(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  var T2 = EXECSLICE.TASKS[ARGS.TASKID];
  if (!T2 && EXECSLICE.TASKINDEX) T2 = EXECSLICE.TASKINDEX[ARGS.TASKID];
  var STATUSRESULT = T2 ? { TASKID: T2.TASKID, KIND: T2.KIND, PIPELINEID: T2.PIPELINEID, ELEMENTID: T2.ELEMENTID, PARENTTASKID: T2.PARENTTASKID, STATUS: T2.STATUS, ORIGIN: T2.ORIGIN, PROGRAMREF: T2.PROGRAMREF, SERIALIZED: T2.SERIALIZED || null, CONSUMERCOUNT: (T2.CONSUMERS || []).length } : null;
  return { ENV: NEXTENV, RESPONSE: STATUSRESULT };
}

function EXECUTIONBEHAVIORCANCELTASK(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  CANCELTASK(EXECSLICE, ARGS.TASKID);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return NEXTENV;
}

function EXECUTIONBEHAVIORSTOPTASK(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  STOPTASK(EXECSLICE, ARGS.TASKID);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return NEXTENV;
}

function EXECUTIONBEHAVIORCCCCONTINUE(ENV, ARGS) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCCONTINUE PIPELINE:', ARGS.PIPELINEID, 'ELEMENT:', ARGS.ELEMENTID);
  return { ENV: ENV, RESPONSE: {} };
}

function EXECUTIONBEHAVIORCCCRETRY(ENV, ARGS) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCRETRY PIPELINE:', ARGS.PIPELINEID, 'ELEMENT:', ARGS.ELEMENTID);
  var RETRYCONTINUATION = ARGS.CONTINUATION;
  if (!RETRYCONTINUATION || typeof RETRYCONTINUATION.FN !== 'function') {
    return { ENV: ENV, RESPONSE: { ERROR: 'cccretry: no continuation' } };
  }
  var RETRYRESULT;
  try {
    RETRYRESULT = RETRYCONTINUATION.FN.apply(null, RETRYCONTINUATION.ARGS || []);
  } catch (SYNCERR) {
    return { ENV: ENV, RESPONSE: { ERROR: SYNCERR && SYNCERR.message ? SYNCERR.message : String(SYNCERR) } };
  }
  return Promise.resolve(RETRYRESULT).then(function(SETTLED) {
    return { ENV: ENV, RESPONSE: SETTLED || {} };
  }).catch(function(RETRYERR) {
    return { ENV: ENV, RESPONSE: { ERROR: RETRYERR && RETRYERR.message ? RETRYERR.message : String(RETRYERR) } };
  });
}

function EXECUTIONBEHAVIORCCCABORT(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION CCCABORT PIPELINE:', ARGS.PIPELINEID, 'ELEMENT:', ARGS.ELEMENTID);
  if (ARGS.PIPELINEID && EXECSLICE.PIPELINES && EXECSLICE.PIPELINES[ARGS.PIPELINEID]) {
    EXECSLICE.PIPELINES[ARGS.PIPELINEID].STATUS = 'aborted';
    SENDEXECUTIONUPDATE(EXECSLICE);
  }
  return { ENV: NEXTENV, RESPONSE: { ERROR: 'pipeline aborted' } };
}

function EXECUTIONBEHAVIORTASKSETTLED(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION TASKSETTLED TASK:', ARGS.TASKID, 'STATUS:', ARGS.STATUS);
  var TASK4 = EXECSLICE.TASKS[ARGS.TASKID];
  if (TASK4) {
    TASK4.STATUS = ARGS.STATUS;
    TASK4.RESULT = ARGS.RESULT || null;
    TASK4.ERROR = ARGS.ERROR || null;
    if (TASK4.SETTLE_SIGNAL && TASK4.SETTLE_SIGNAL.RESOLVE) {
      TASK4.SETTLE_SIGNAL.RESOLVE({ STATUS: ARGS.STATUS, RESULT: ARGS.RESULT || null, ERROR: ARGS.ERROR || null });
      TASK4.SETTLE_SIGNAL.RESOLVE = null;
    }
    TASK4.CONSUMERS = [];
    SENDEXECUTIONUPDATE(EXECSLICE);
  }
  return NEXTENV;
}

function EXECUTIONBEHAVIORRECOVER(ENV, ARGS) {
  return DBRESTORE('actor:state:execution').then(function(SAVED) {
    var NEXTENV = {};
    Object.keys(ENV).forEach(function(K) { NEXTENV[K] = ENV[K]; });
    NEXTENV.EXECUTION = (SAVED !== null && SAVED !== undefined) ? SAVED : { PIPELINES: {}, TASKS: {}, TASKORDER: [], TASKINDEX: {}, TASKCOUNTER: 0, HTMLSNAPSHOT: null };
    SENDEXECUTIONUPDATE(NEXTENV.EXECUTION);
    return { ENV: NEXTENV, RESPONSE: NEXTENV };
  }).catch(function(E) {
    return ENV;
  });
}

function EXECUTIONBEHAVIORREGISTERPIPELINE(ENV, ARGS) {
  var NEXTENV = ENSUREEXECUTIONSLICE(ENV);
  var EXECSLICE = NEXTENV.execution;
  logdebug(ENV, '[EXECUTIONACTOR]', 'ACTION REGISTERPIPELINE:', ARGS.PIPELINEID);
  var P10 = ENSUREPIPELINE(EXECSLICE, ARGS.PIPELINEID);
  P10.USESELEMENTSNAPSHOTS = true;
  if (ARGS.ENV) P10.ENV = SANITIZEFORSTATE(ARGS.ENV);
  SENDEXECUTIONUPDATE(EXECSLICE);
  return NEXTENV;
}

function EXECUTIONBEHAVIORPING(ENV, ARGS) {
  return { ENV: ENV, RESPONSE: true };
}

// ============================================================
// §2 — Handler registration
// ============================================================

REGISTERACTORMESSAGE('EXECUTIONACTOR', PIPELINELOADEDTYPE,
  EXECUTIONBEHAVIORPIPELINELOADED);

REGISTERACTORMESSAGE('EXECUTIONACTOR', ENVUPDATEDTYPE,
  EXECUTIONBEHAVIORENVUPDATED);

REGISTERACTORMESSAGE('EXECUTIONACTOR', GETSTATUSTYPE,
  EXECUTIONBEHAVIORGETSTATUS);

REGISTERACTORMESSAGE('EXECUTIONACTOR', EXECUTEELEMENTTYPE,
  EXECUTIONBEHAVIOREXECUTEELEMENT);

REGISTERACTORMESSAGE('EXECUTIONACTOR', AWAITTASKTYPE,
  EXECUTIONBEHAVIORAWAITTASK);

REGISTERACTORMESSAGE('EXECUTIONACTOR', GETTASKSTYPE,
  EXECUTIONBEHAVIORGETTASKS);

REGISTERACTORMESSAGE('EXECUTIONACTOR', GETTASKSTATUSTYPE,
  EXECUTIONBEHAVIORGETTASKSTATUS);

REGISTERACTORMESSAGE('EXECUTIONACTOR', CANCELTASKTYPE,
  EXECUTIONBEHAVIORCANCELTASK);

REGISTERACTORMESSAGE('EXECUTIONACTOR', STOPTASKTYPE,
  EXECUTIONBEHAVIORSTOPTASK);

REGISTERACTORMESSAGE('EXECUTIONACTOR', CCCCONTINUETYPE,
  EXECUTIONBEHAVIORCCCCONTINUE);

REGISTERACTORMESSAGE('EXECUTIONACTOR', CCCRETRYTYPE,
  EXECUTIONBEHAVIORCCCRETRY);

REGISTERACTORMESSAGE('EXECUTIONACTOR', CCCABORTTYPE,
  EXECUTIONBEHAVIORCCCABORT);

REGISTERACTORMESSAGE('EXECUTIONACTOR', TASKSETTLEDTYPE,
  EXECUTIONBEHAVIORTASKSETTLED);

REGISTERACTORMESSAGE('EXECUTIONACTOR', RECOVERTYPE,
  EXECUTIONBEHAVIORRECOVER);

REGISTERACTORMESSAGE('EXECUTIONACTOR', REGISTERPIPELINETYPE,
  EXECUTIONBEHAVIORREGISTERPIPELINE);

REGISTERACTORMESSAGE('EXECUTIONACTOR', PINGTYPE,
  EXECUTIONBEHAVIORPING);

// ============================================================
// §3 — Aggregate behaviour
// ============================================================

function EXECUTIONBEHAVIOR(ENV, MESSAGE) {
  var OUT = INVOKEHANDLER('EXECUTIONACTOR', ENV, MESSAGE);
  if (OUT.matched !== true) return ENV;
  return OUT.result;
}

REGISTERDISPATCH('EXECUTIONACTOR', EXECUTIONBEHAVIOR);

// ============================================================
// §4 — Task settlement (into the flow)
// ============================================================
//
// @proposal=P-ACTOR-FLOW-002 — SETTLETASK returns { ENV, RESPONSE }.
// It does NOT emit SENDRESPONSE. It resolves the task's settle signal
// so AWAITTASK's promises resolve. The dispatcher emits the ONE response
// owed to EXECUTEELEMENT's caller.

function SETTLETASK(TASKID, STATUS, RESULT, ERROR, ENV) {
  logdebug(ENV, '[EXECUTIONACTOR]', 'SETTLETASK TASK:', TASKID, 'STATUS:', STATUS);
  var NEXTENV = {};
  Object.keys(ENV || {}).forEach(function(K) { NEXTENV[K] = ENV[K]; });
  var EXECSLICE = NEXTENV.execution;
  if (!EXECSLICE) {
    NEXTENV = ENSUREEXECUTIONSLICE(NEXTENV);
    EXECSLICE = NEXTENV.execution;
  }
  var TASK = EXECSLICE.TASKS[TASKID];
  if (!TASK) return { ENV: NEXTENV, RESPONSE: undefined };

  TASK.STATUS = STATUS;
  TASK.RESULT = RESULT || null;
  TASK.ERROR = ERROR || null;

  var RESPONSEPAYLOAD = null;
  if (STATUS === 'EXECUTED') {
    RESPONSEPAYLOAD = { TASKID: TASKID, PIPELINEID: TASK.PIPELINEID, ELEMENTID: TASK.ELEMENTID, RESULT: RESULT || {} };
    SENDINSTRUCTION('BROADCAST', 'BLOCKEXECUTED', {
      PIPELINEID: TASK.PIPELINEID || null, STAGEPATH: TASK.STAGEPATH || null,
      ELEMENTID: TASK.ELEMENTID || null, TOKEN: TASK.TOKEN || null, RESULT: RESULT || {}
    }, GENERATETAG(), 'EXECUTIONACTOR');
  } else if (STATUS === 'FAILED') {
    RESPONSEPAYLOAD = {
      TASKID: TASKID, PIPELINEID: TASK.PIPELINEID, ELEMENTID: TASK.ELEMENTID,
      ERROR: { MESSAGE: ERROR ? ERROR.message : 'TASK FAILED', DIAGNOSTIC: (ERROR && ERROR.diagnostic) ? ERROR.diagnostic : {} }
    };
    SENDINSTRUCTION('BROADCAST', 'BLOCKFAILED', {
      PIPELINEID: TASK.PIPELINEID || null, STAGEPATH: TASK.STAGEPATH || null,
      ELEMENTID: TASK.ELEMENTID || null, TOKEN: TASK.TOKEN || null,
      ERROR: ERROR ? ERROR.message : 'TASK FAILED', DIAGNOSTIC: (ERROR && ERROR.diagnostic) ? ERROR.diagnostic : {}
    }, GENERATETAG(), 'EXECUTIONACTOR');
  }

  TASK.CONSUMERS = [];
  if (TASK.SETTLE_SIGNAL && TASK.SETTLE_SIGNAL.RESOLVE) {
    TASK.SETTLE_SIGNAL.RESOLVE({ STATUS: STATUS, RESULT: TASK.RESULT, ERROR: TASK.ERROR });
    TASK.SETTLE_SIGNAL.RESOLVE = null;
  }
  SENDEXECUTIONUPDATE(EXECSLICE);
  logdebug(ENV, '[EXECUTIONACTOR]', 'SETTLETASK COMPLETED:', TASKID);

  return { ENV: NEXTENV, RESPONSE: RESPONSEPAYLOAD };
}

function RUNELEMENTTASK(TASKID, DESCRIPTOR, ENV) {
  var EXECUTIONCONTEXT = {
    ENV: DESCRIPTOR.ENV || {},
    INPUTS: (DESCRIPTOR.SIGNATURE && (DESCRIPTOR.SIGNATURE.inputs || DESCRIPTOR.SIGNATURE.INPUTS)) || [],
    OUTPUTS: (DESCRIPTOR.SIGNATURE && (DESCRIPTOR.SIGNATURE.outputs || DESCRIPTOR.SIGNATURE.OUTPUTS)) || {},
    PROPERTIES: DESCRIPTOR.PROPERTIES || {}
  };
  logdebug(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK START:', TASKID, DESCRIPTOR.ELEMENTID, 'PIPELINE:', DESCRIPTOR.PIPELINEID);
  var EXECUTOR = DESCRIPTOR.EXECUTOR;
  if (typeof EXECUTOR !== 'function') {
    var FAILUREERROR = new Error('[EXECUTIONACTOR] DESCRIPTOR.EXECUTOR is not a function');
    return Promise.resolve(SETTLETASK(TASKID, 'FAILED', null, FAILUREERROR, ENV));
  }
  var EXECUTIONPROMISE;
  try {
    EXECUTIONPROMISE = Promise.resolve(EXECUTOR(EXECUTIONCONTEXT));
  } catch (SYNCERR) {
    EXECUTIONPROMISE = Promise.reject(SYNCERR);
  }
  return EXECUTIONPROMISE.then(function(RESULT) {
    logdebug(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK COMPLETED:', TASKID, DESCRIPTOR.ELEMENTID);
    return SETTLETASK(TASKID, 'EXECUTED', RESULT || {}, null, ENV);
  }).catch(function(ERR) {
    logerror(ENV, '[EXECUTIONACTOR]', 'RUNELEMENTTASK FAILED:', TASKID, DESCRIPTOR.ELEMENTID, ERR);
    return SETTLETASK(TASKID, 'FAILED', null, ERR, ENV);
  });
}

// ============================================================
// §5 — Producers (literals)
// ============================================================

function ENQUEUEEXECUTIONPIPELINELOADED(PIPELINEID, ENV, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'PIPELINELOADED', { PIPELINEID: PIPELINEID, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONSUBMIT(DESCRIPTOR, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'EXECUTEELEMENT', DESCRIPTOR, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONAWAITTASK(TASKID, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'AWAITTASK', { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONGETTASKS(FILTERS, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'GETTASKS', FILTERS || {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONGETTASKSTATUS(TASKID, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'GETTASKSTATUS', { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONCANCELTASK(TASKID, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'CANCELTASK', { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONSTOPTASK(TASKID, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'STOPTASK', { TASKID: TASKID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONGETSTATUS(PIPELINEID, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'GETSTATUS', { PIPELINEID: PIPELINEID }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONENVUPDATED(PIPELINEID, ENV, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'ENVUPDATED', { PIPELINEID: PIPELINEID, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONCCCABORT(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'CCCABORT', { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONCCCCONTINUE(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'CCCCONTINUE', { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONCCCRETRY(PIPELINEID, PATH, ELEMENTID, CONTINUATION, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'CCCRETRY', { PIPELINEID: PIPELINEID, PATH: PATH, ELEMENTID: ELEMENTID, CONTINUATION: CONTINUATION }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONREGISTERPIPELINE(PIPELINEID, DNA, ENV, RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'REGISTERPIPELINE', { PIPELINEID: PIPELINEID, DNA: DNA, ENV: ENV }, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONRECOVER(RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'RECOVER', {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }
function ENQUEUEEXECUTIONPING(RESPONSESPEC) { var TAG = GENERATETAG(); SENDINSTRUCTION('EXECUTIONACTOR', 'PING', {}, TAG, 'BLOCKCOMPILER', RESPONSESPEC); }

// ============================================================
// §6 — Actor handle surface (unchanged)
// ============================================================

var EXECUTIONACTORHANDLE = null;

function EXECUTIONACTORHANDLEINSTANCE() {
  if (!EXECUTIONACTORHANDLE) EXECUTIONACTORHANDLE = CREATEACTORHANDLE('EXECUTIONACTOR');
  return EXECUTIONACTORHANDLE;
}

function SUBMIT(ACTION) { return EXECUTIONACTORHANDLEINSTANCE().SUBMIT(ACTION); }
function EXPECT(ID, INTERVAL, TIMEOUT) { return EXECUTIONACTORHANDLEINSTANCE().EXPECT(ID, INTERVAL, TIMEOUT); }
function GETACTIONRESULT(ID) { return EXECUTIONACTORHANDLEINSTANCE().GETACTIONRESULT(ID); }

function STARTEXECUTIONACTOR(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS : (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) { var ENV = GETACTORSTATE('WORLDMAPACTOR'); if (ENV) ENV.VERBOSITY = LVL; }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('EXECUTIONACTOR', EXECUTIONBEHAVIOR, MESSAGE); },
    SUBMIT: SUBMIT, EXPECT: EXPECT, GETACTIONRESULT: GETACTIONRESULT
  };
}

function ENSUREEXECUTIONACTORREADY(OPTIONS) { return Promise.resolve(STARTEXECUTIONACTOR(OPTIONS)); }
