// hypervisoractor.js — hypervisor concern.
//
// @proposal=P5 (corrected) — the hypervisor no longer participates in
// pipeline boot. The corrected model has no DNA and no bootdna: the
// frontend imports a pipeline program and calls its init function,
// which runs the construction sequence and terminates with run(). The
// DNA-era cases (BOOTDNA, COMPILESTAGE, STAGECOMPLETED) and their
// helpers are removed. The hypervisor retains its other roles (env
// storage, render HTML, execution stack, routes, programs, active
// pipelines, registry, ping, recover, activate actors) and its
// actor-handle surface (SUBMIT / EXPECT / GETACTIONRESULT) established
// at Cycle 26.
//
// DOM event routing: the EVENTTRIGGERED message from RENDERACTOR had
// its dispatch path through the removed DNA-era machinery. Under the
// corrected model the pipeline state is a value threaded by argument
// to run() and is not centrally stored. The EVENTTRIGGERED case is
// therefore retained as a defensive stub. A follow-up cycle will
// define the corrected event routing mechanism. Recorded as
// DEV-C37R-EVENTROUTING.

var HYPERVISORVERBOSITYCONSTANTS = createverbosityconstants();

function ENSUREHYPERVISORSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'hypervisor', function() {
    return {
      BOOT: true,
      ENVBYPIPELINE: {},
      RENDERHTML: '',
      EXECUTIONSTACK: [],
      ROUTES: {},
      ACTIVEPIPELINES: [],
      PROGRAMS: {},
      NEXTSTAGEMESSAGES: {}
    };
  });
}

function CREATEHYPERVISORERRORCONTEXT(LABEL) {
  return function(ERR) {
    if (!ERR) ERR = new Error('unknown hypervisor error');
    if (!ERR.DIAGNOSTIC) ERR.DIAGNOSTIC = {};
    ERR.DIAGNOSTIC.HYPERVISORSTAGE = LABEL;
    throw ERR;
  };
}

function REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID) {
  if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
  if (HYPERSLICE.ACTIVEPIPELINES.indexOf(PIPELINEID) === -1) {
    HYPERSLICE.ACTIVEPIPELINES.push(PIPELINEID);
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
    }, GENERATETAG(), 'HYPERVISORACTOR');
  }
}

// Behavior function: (env, message) -> env | promise<env>
function HYPERVISORBEHAVIOR(ENV, MESSAGE) {
  logdebug(ENV, '[HYPERVISOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);

  var HYPERSLICE = ENSUREHYPERVISORSLICE(ENV);
  var PIPELINEID = MESSAGE.PIPELINEID;

  switch (MESSAGE.TYPE) {
    case MESSAGETYPES.LOAD:
      return ENV;
    case MESSAGETYPES.SAVE:
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETENV: {
      var ENVMAP = HYPERSLICE.ENVBYPIPELINE;
      var P = ENVMAP && ENVMAP[PIPELINEID];
      var RESULT = P ? P.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RESULT, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.SETENV: {
      if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = HYPERSLICE.ENVBYPIPELINE || {};
      if (!HYPERSLICE.ENVBYPIPELINE[PIPELINEID]) HYPERSLICE.ENVBYPIPELINE[PIPELINEID] = {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].ENV = MESSAGE.ENV || {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].UPDATEDAT = Date.now();
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETLATESTENV: {
      var ENVMAP2 = HYPERSLICE.ENVBYPIPELINE;
      var PSTATE = ENVMAP2 && ENVMAP2[PIPELINEID];
      var LATEST = PSTATE ? PSTATE.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, LATEST, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.GETRENDERHTML:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.RENDERHTML || '', 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETRENDERHTML:
      HYPERSLICE.RENDERHTML = MESSAGE.HTML || '';
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETEXECUTIONSTACK:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.EXECUTIONSTACK || [], 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETEXECUTIONSTACK:
      HYPERSLICE.EXECUTIONSTACK = MESSAGE.STACK || [];
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETROUTE:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.ROUTES && MESSAGE.KEY ? (HYPERSLICE.ROUTES[MESSAGE.KEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETROUTE:
      if (!HYPERSLICE.ROUTES) HYPERSLICE.ROUTES = {};
      HYPERSLICE.ROUTES[MESSAGE.KEY] = MESSAGE.ROUTE || null;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETACTIVEPIPELINES:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, (HYPERSLICE.ACTIVEPIPELINES || []).slice(), 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.REGISTERPIPELINE:
      REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID);
      return ENV;
    case MESSAGETYPES.UNREGISTERPIPELINE:
      if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
      HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES.filter(function(ID) { return ID !== PIPELINEID; });
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.SETPROGRAM: {
      var PROGKEY = MESSAGE.PROGRAMKEY;
      var PROGSOURCE = MESSAGE.PROGRAMSOURCE;
      if (!HYPERSLICE.PROGRAMS) HYPERSLICE.PROGRAMS = {};
      HYPERSLICE.PROGRAMS[PROGKEY] = PROGSOURCE;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETPROGRAM: {
      var PKEY = MESSAGE.PROGRAMKEY;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.PROGRAMS && PKEY ? (HYPERSLICE.PROGRAMS[PKEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.MARKBOOT:
      HYPERSLICE.BOOT = MESSAGE.BOOT !== false;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'HYPERVISOR', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.EVENTTRIGGERED: {
      // @proposal=P5 (corrected) — defensive stub. The DNA-era dispatch
      // path (LOADEDPIPELINES + COMPILESTAGEFROMSTOREDDNA) is removed.
      // The corrected event routing mechanism is not yet defined; see
      // the file header and DEV-C37R-EVENTROUTING.
      logwarn(ENV, '[HYPERVISOR]', 'EVENTTRIGGERED received; event routing under corrected P5 is not yet defined',
        'PIPELINEID:', PIPELINEID, 'STAGEID:', MESSAGE.STAGEID);
      return ENV;
    }
    case MESSAGETYPES.PING:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.RECOVER:
      DBRESTORE('actor:state:hypervisor').then(function(SAVED) {
        if (SAVED && typeof SAVED === 'object') ENV.HYPERVISOR = SAVED;
        else ENV.HYPERVISOR = {
          BOOT: true, ENVBYPIPELINE: {}, RENDERHTML: '', EXECUTIONSTACK: [],
          ROUTES: {}, ACTIVEPIPELINES: [], PROGRAMS: {}, NEXTSTAGEMESSAGES: {}
        };
        SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
          UPDATES: [{ PATH: 'HYPERVISOR', VALUE: ENV.HYPERVISOR }]
        }, GENERATETAG(), 'HYPERVISORACTOR');
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      }).catch(function(E) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: E.message || String(E) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      });
      return ENV;
    case MESSAGETYPES.ACTIVATEACTORS:
      return ENV;

    default:
      logwarn(ENV, '[HYPERVISOR]', 'UNKNOWN MESSAGE TYPE:', MESSAGE.TYPE);
      return ENV;
  }
}

function ENQUEUEHYPERVISOR(TYPE, PAYLOAD, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('HYPERVISORACTOR', TYPE, PAYLOAD || {}, TAG, 'system', RESPONSESPEC);
}

function ENQUEUEHYPERVISORLOAD(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.LOAD, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORSAVE(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.SAVE, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORGETENV(PIPELINEID, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETENV, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETENV(PIPELINEID, ENV, STAGEID, ELEMENTID, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.SETENV, { PIPELINEID: PIPELINEID, ENV: ENV, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETLATESTENV(PIPELINEID, STAGEID, ELEMENTID, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETLATESTENV, { PIPELINEID: PIPELINEID, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETRENDERHTML(RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETRENDERHTML, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETRENDERHTML(HTML, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.SETRENDERHTML, { HTML: HTML }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETEXECUTIONSTACK(RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETEXECUTIONSTACK, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETEXECUTIONSTACK(STACK, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.SETEXECUTIONSTACK, { STACK: STACK }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETROUTE(KEY, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETROUTE, { KEY: KEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETROUTE(KEY, ROUTE, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.SETROUTE, { KEY: KEY, ROUTE: ROUTE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETACTIVEPIPELINES(RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETACTIVEPIPELINES, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.REGISTERPIPELINE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORUNREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.UNREGISTERPIPELINE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETPROGRAM(PROGRAMKEY, PROGRAMSOURCE, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.SETPROGRAM, { PROGRAMKEY: PROGRAMKEY, PROGRAMSOURCE: PROGRAMSOURCE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETPROGRAM(PROGRAMKEY, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.GETPROGRAM, { PROGRAMKEY: PROGRAMKEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORMARKBOOT(BOOT, RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.MARKBOOT, { BOOT: BOOT }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORPING(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.PING, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORACTIVATEACTORS(RESPONSESPEC) {
  return ENQUEUEHYPERVISOR(MESSAGETYPES.ACTIVATEACTORS, {}, RESPONSESPEC);
}

// ---------- ACTOR HANDLE SURFACE — @proposal=P4 (Cycle 26) ----------
//
// The three operations are sourced from CREATEACTORHANDLE (Cycle 18).
// SUBMIT routes through the mail system (Q6); EXPECT polls
// GETACTIONRESULT until a response (including error) is obtained, and
// rejects on timeout or EXPIRED (Q7); GETACTIONRESULT is a non-blocking
// read of the mail-system records (Q8).

var HYPERVISORACTORHANDLE = null;

function HYPERVISORACTORHANDLEINSTANCE() {
  if (!HYPERVISORACTORHANDLE) {
    HYPERVISORACTORHANDLE = CREATEACTORHANDLE('HYPERVISORACTOR');
  }
  return HYPERVISORACTORHANDLE;
}

function SUBMIT(ACTION) { return HYPERVISORACTORHANDLEINSTANCE().SUBMIT(ACTION); }
function EXPECT(ID, INTERVAL, TIMEOUT) { return HYPERVISORACTORHANDLEINSTANCE().EXPECT(ID, INTERVAL, TIMEOUT); }
function GETACTIONRESULT(ID) { return HYPERVISORACTORHANDLEINSTANCE().GETACTIONRESULT(ID); }

function STARTHYPERVISORACTOR(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS :
      (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      if (ENV) ENV.VERBOSITY = LVL;
    }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('HYPERVISORACTOR', HYPERVISORBEHAVIOR, MESSAGE); },
    SUBMIT: SUBMIT,
    EXPECT: EXPECT,
    GETACTIONRESULT: GETACTIONRESULT
  };
}
