var HYPERVISORVERBOSITYCONSTANTS = createverbosityconstants();

function ENSUREHYPERVISORSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'hypervisor', function() {
    return {
      BOOT: true,
      ENVBYPIPELINE: {},
      RENDERHTML: '',
      EXECUTIONSTACK: [],
      ROUTES: {},
      ACTIVEPIPELINES: [],
      PROGRAMS: {},
      LOADEDPIPELINES: {},
      NEXTSTAGEMESSAGES: {}
    };
  });
}

function CREATEHYPERVISORERRORCONTEXT(LABEL) {
  return function(ERR) {
    if (!ERR) ERR = new Error('unknown hypervisor error');
    if (!ERR.DIAGNOSTIC) ERR.DIAGNOSTIC = {};
    ERR.DIAGNOSTIC.HYPERVISORSTAGE = LABEL;
    throw ERR;
  };
}

function REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID) {
  if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
  if (HYPERSLICE.ACTIVEPIPELINES.indexOf(PIPELINEID) === -1) {
    HYPERSLICE.ACTIVEPIPELINES.push(PIPELINEID);
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
    }, GENERATETAG(), 'HYPERVISORACTOR');
  }
}

function COMPILESTAGEFROMSTOREDDNA(HYPERSLICE, PIPELINEID, STAGEPATH, ENV, OPTIONS) {
  var LOADED = HYPERSLICE.LOADEDPIPELINES || HYPERSLICE.LOADEDPIPELINES;
  var ENTRY = LOADED && LOADED[PIPELINEID];
  if (!ENTRY || !ENTRY.DNA) {
    return Promise.resolve({ ERROR: 'missing DNA for pipeline: ' + PIPELINEID });
  }
  var ENVMAP = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
  var LATESTENV = (ENVMAP && ENVMAP[PIPELINEID] && ENVMAP[PIPELINEID].ENV) || ENV || {};
  var COMPFN = (typeof blockcompilercompilestage === 'function') ? blockcompilercompilestage :
    ((typeof blockcompilercompilestage === 'function') ? blockcompilercompilestage :
    ((typeof compilestage === 'function') ? compilestage : function() { return Promise.resolve(); }));
  return COMPFN(ENTRY.DNA, STAGEPATH, LATESTENV, OPTIONS || {});
}

function HANDLESTAGECOMPLETED(HYPERSLICE, MESSAGE) {
  var PIPELINEID = MESSAGE.PIPELINEID || MESSAGE.pipelineId;
  var STAGEID = MESSAGE.STAGEID || MESSAGE.stageId;
  var KEY = PIPELINEID + ':' + STAGEID;
  loginfo(HYPERSLICE, '[HYPERVISOR]', 'ACTION STAGECOMPLETED:', KEY);

  if (MESSAGE.SENDER && MESSAGE.TAG) {
    var ACKTYPE = MESSAGETYPES.STAGECOMPLETEDACK || MESSAGETYPES.STAGE_COMPLETED_ACK;
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STAGEID: STAGEID }, 'HYPERVISORACTOR', ACKTYPE);
  }

  if (MESSAGE.ENV !== undefined && MESSAGE.ENV !== null) {
    if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = HYPERSLICE.ENVBYPIPELINE || {};
    if (!HYPERSLICE.ENVBYPIPELINE[PIPELINEID]) HYPERSLICE.ENVBYPIPELINE[PIPELINEID] = {};
    HYPERSLICE.ENVBYPIPELINE[PIPELINEID].ENV = MESSAGE.ENV;
    HYPERSLICE.ENVBYPIPELINE[PIPELINEID].UPDATEDAT = Date.now();
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
    }, GENERATETAG(), 'HYPERVISORACTOR');
  }

  var NEXTMSGMAP = HYPERSLICE.NEXTSTAGEMESSAGES || HYPERSLICE.NEXTSTAGEMESSAGES || {};
  var NEXTMSG = MESSAGE.NEXTSTAGEMESSAGE || MESSAGE.nextStageMessage || NEXTMSGMAP[KEY];
  if (NEXTMSG) {
    if (NEXTMSGMAP[KEY]) delete NEXTMSGMAP[KEY];
    var NEXTSTAGEPATH;
    var SP = NEXTMSG.STAGEPATH || NEXTMSG.stagePath;
    if (SP && Array.isArray(SP) && SP.length > 0) {
      NEXTSTAGEPATH = SP;
    } else {
      var SIDX = (NEXTMSG.STAGEINDEX !== undefined) ? NEXTMSG.STAGEINDEX : NEXTMSG.stageIndex;
      NEXTSTAGEPATH = ['pipeline', 'elements', SIDX];
    }
    var TARGETPIPE = NEXTMSG.PIPELINEID || NEXTMSG.pipelineId || PIPELINEID;
    COMPILESTAGEFROMSTOREDDNA(
      HYPERSLICE,
      TARGETPIPE,
      NEXTSTAGEPATH,
      NEXTMSG.ENV || MESSAGE.ENV || {},
      NEXTMSG.OPTIONS || {}
    ).then(function() {
      // Next stage will send its own stage_completed
    }).catch(function(ERR) {
      logwarn(HYPERSLICE, '[HYPERVISOR]', 'NEXT STAGE ORCHESTRATION FAILED:', ERR);
    });
  } else {
    loginfo(HYPERSLICE, '[HYPERVISOR]', 'NO NEXT SEQUENTIAL STAGE FOR PIPELINE:', PIPELINEID);
  }
}

// Pure behavior function: (env, message) -> env
function HYPERVISORBEHAVIOR(ENV, MESSAGE) {
  logdebug(ENV, '[HYPERVISOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);

  var HYPERSLICE = ENSUREHYPERVISORSLICE(ENV);
  var PIPELINEID = MESSAGE.PIPELINEID || MESSAGE.pipelineId;

  switch (MESSAGE.TYPE) {
    case MESSAGETYPES.LOAD:
      return ENV;
    case MESSAGETYPES.SAVE:
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETENV:
    case MESSAGETYPES.GET_ENV: {
      var ENVMAP = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
      var P = ENVMAP && ENVMAP[PIPELINEID];
      var RESULT = P ? P.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RESULT, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.SETENV:
    case MESSAGETYPES.SET_ENV: {
      if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = HYPERSLICE.ENVBYPIPELINE || {};
      if (!HYPERSLICE.ENVBYPIPELINE[PIPELINEID]) HYPERSLICE.ENVBYPIPELINE[PIPELINEID] = {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].ENV = MESSAGE.ENV || {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].UPDATEDAT = Date.now();
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETLATESTENV:
    case MESSAGETYPES.GET_LATEST_ENV: {
      var ENVMAP2 = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
      var PSTATE = ENVMAP2 && ENVMAP2[PIPELINEID];
      var LATEST = PSTATE ? PSTATE.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, LATEST, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.GETRENDERHTML:
    case MESSAGETYPES.GET_RENDER_HTML:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.RENDERHTML || HYPERSLICE.RENDERHTML || '', 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETRENDERHTML:
    case MESSAGETYPES.SET_RENDER_HTML:
      HYPERSLICE.RENDERHTML = MESSAGE.HTML || '';
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETEXECUTIONSTACK:
    case MESSAGETYPES.GET_EXECUTION_STACK:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.EXECUTIONSTACK || HYPERSLICE.EXECUTIONSTACK || [], 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETEXECUTIONSTACK:
    case MESSAGETYPES.SET_EXECUTION_STACK:
      HYPERSLICE.EXECUTIONSTACK = MESSAGE.STACK || [];
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETROUTE:
    case MESSAGETYPES.GET_ROUTE:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.ROUTES && MESSAGE.KEY ? (HYPERSLICE.ROUTES[MESSAGE.KEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETROUTE:
    case MESSAGETYPES.SET_ROUTE:
      if (!HYPERSLICE.ROUTES) HYPERSLICE.ROUTES = {};
      HYPERSLICE.ROUTES[MESSAGE.KEY] = MESSAGE.ROUTE || null;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETACTIVEPIPELINES:
    case MESSAGETYPES.GET_ACTIVE_PIPELINES:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, (HYPERSLICE.ACTIVEPIPELINES || HYPERSLICE.ACTIVEPIPELINES || []).slice(), 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.REGISTERPIPELINE:
    case MESSAGETYPES.REGISTER_PIPELINE:
      REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID);
      return ENV;
    case MESSAGETYPES.UNREGISTERPIPELINE:
    case MESSAGETYPES.UNREGISTER_PIPELINE:
      if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
      HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES.filter(function(ID) { return ID !== PIPELINEID; });
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.SETPROGRAM:
    case MESSAGETYPES.SET_PROGRAM: {
      var PROGKEY = MESSAGE.PROGRAMKEY || MESSAGE.programKey;
      var PROGSOURCE = MESSAGE.PROGRAMSOURCE || MESSAGE.programSource;
      if (!HYPERSLICE.PROGRAMS) HYPERSLICE.PROGRAMS = {};
      HYPERSLICE.PROGRAMS[PROGKEY] = PROGSOURCE;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETPROGRAM:
    case MESSAGETYPES.GET_PROGRAM: {
      var PKEY = MESSAGE.PROGRAMKEY || MESSAGE.programKey;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.PROGRAMS && PKEY ? (HYPERSLICE.PROGRAMS[PKEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.MARKBOOT:
    case MESSAGETYPES.MARK_BOOT:
      HYPERSLICE.BOOT = MESSAGE.BOOT !== false;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.EVENTTRIGGERED:
    case MESSAGETYPES.EVENT_TRIGGERED: {
      var STAGEID = MESSAGE.STAGEID || MESSAGE.stageId;
      var STAGEPATH = MESSAGE.STAGEPATH || MESSAGE.stagePath || ['pipeline', 'elements', -1];

      var LOADEDMAP = HYPERSLICE.LOADEDPIPELINES || HYPERSLICE.LOADEDPIPELINES;
      var LOADEDENTRY = LOADEDMAP && LOADEDMAP[PIPELINEID];
      if (!LOADEDENTRY || !LOADEDENTRY.DNA) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: 'missing loaded pipeline DNA' }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        return ENV;
      }

      loginfo(ENV, '[HYPERVISOR]', 'EVENTTRIGGERED COMPILING STAGE:', PIPELINEID, STAGEID, STAGEPATH);

      var EVENTOPTIONS = LOADEDENTRY.OPTIONS || {};
      EVENTOPTIONS.ISEVENTTRIGGER = true;

      COMPILESTAGEFROMSTOREDDNA(HYPERSLICE, PIPELINEID, STAGEPATH, {}, EVENTOPTIONS)
        .then(function() {
          if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STARTED: true }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        })
        .catch(function(ERR) {
          logwarn(ENV, '[HYPERVISOR]', 'EVENTTRIGGERED COMPILATION FAILED:', ERR);
          if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: ERR.message || String(ERR) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        });
      return ENV;
    }
    case MESSAGETYPES.PING:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.RECOVER:
      DBRESTORE('actor:state:hypervisor').then(function(SAVED) {
        if (SAVED && typeof SAVED === 'object') ENV.HYPERVISOR = SAVED;
        else ENV.HYPERVISOR = {
          BOOT: true, ENVBYPIPELINE: {}, RENDERHTML: '', EXECUTIONSTACK: [],
          ROUTES: {}, ACTIVEPIPELINES: [], PROGRAMS: {}, LOADEDPIPELINES: {}, NEXTSTAGEMESSAGES: {}
        };
        SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
          UPDATES: [{ PATH: 'hypervisor', VALUE: ENV.HYPERVISOR }]
        }, GENERATETAG(), 'HYPERVISORACTOR');
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      }).catch(function(E) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: E.message || String(E) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      });
      return ENV;
    case MESSAGETYPES.ACTIVATEACTORS:
    case MESSAGETYPES.ACTIVATE_ACTORS:
      return ENV;
    case MESSAGETYPES.BOOTPIPELINE:
    case MESSAGETYPES.BOOT_PIPELINE: {
      var BOOTOPTIONS = MESSAGE.OPTIONS || {};
      if (BOOTOPTIONS.AUTORUN === undefined) BOOTOPTIONS.AUTORUN = true;
      if (BOOTOPTIONS.VERBOSITY === undefined && ENV.VERBOSITY !== undefined) BOOTOPTIONS.VERBOSITY = ENV.VERBOSITY;

      var DNAENVELOPE = MESSAGE.DNA;
      var BOOTEDTYPE = MESSAGETYPES.PIPELINEBOOTED || MESSAGETYPES.PIPELINE_BOOTED;
      if (!DNAENVELOPE || !DNAENVELOPE.DEFINITION) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: '[HYPERVISOR] missing DNA envelope' }, 'HYPERVISORACTOR', BOOTEDTYPE);
        return ENV;
      }

      var LOADEDMAP2 = HYPERSLICE.LOADEDPIPELINES || HYPERSLICE.LOADEDPIPELINES;
      var ALREADYLOADED = LOADEDMAP2 && LOADEDMAP2[PIPELINEID] && LOADEDMAP2[PIPELINEID].DNA;
      var ENVMAP3 = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
      var HASENVSTATE = ENVMAP3 && ENVMAP3[PIPELINEID] && ENVMAP3[PIPELINEID].ENV;

      if (ALREADYLOADED && HASENVSTATE) {
        loginfo(ENV, '[HYPERVISOR]', 'BOOTPIPELINE SKIPPED (STATE ALREADY PRESENT):', PIPELINEID);
        if (MESSAGE.SENDER && MESSAGE.TAG) {
          SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STARTED: true, PIPELINEID: PIPELINEID, REUSED: true }, 'HYPERVISORACTOR', BOOTEDTYPE);
        }
        return ENV;
      }

      if (!HYPERSLICE.LOADEDPIPELINES) HYPERSLICE.LOADEDPIPELINES = {};
      HYPERSLICE.LOADEDPIPELINES[PIPELINEID] = {
        DNA: DNAENVELOPE,
        OPTIONS: BOOTOPTIONS,
        ACCESSORS: MESSAGE.ACCESSORS || null,
        SINKS: MESSAGE.SINKS || []
      };

      REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID);
      var LOADEDMSGTYPE = MESSAGETYPES.PIPELINELOADED || MESSAGETYPES.PIPELINE_LOADED;
      var REGMSGTYPE = MESSAGETYPES.REGISTERPIPELINE || MESSAGETYPES.REGISTER_PIPELINE;
      SENDINSTRUCTION('EXECUTIONACTOR', LOADEDMSGTYPE, { PIPELINEID: PIPELINEID, ENV: {} }, null, 'HYPERVISORACTOR');
      SENDINSTRUCTION('EXECUTIONACTOR', REGMSGTYPE, { PIPELINEID: PIPELINEID, DNA: null, ENV: {} }, null, 'HYPERVISORACTOR');

      if (MESSAGE.SENDER && MESSAGE.TAG) {
        SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STARTED: true, PIPELINEID: PIPELINEID }, 'HYPERVISORACTOR', BOOTEDTYPE);
      }

      var STAGEPATH2 = MESSAGE.STAGEPATH || MESSAGE.stagePath || ['pipeline', 'elements', 0];
      COMPILESTAGEFROMSTOREDDNA(HYPERSLICE, PIPELINEID, STAGEPATH2, BOOTOPTIONS.BASEENV || BOOTOPTIONS.baseEnv || {}, BOOTOPTIONS)
        .then(function() {})
        .catch(function(ERR) {
          logwarn(ENV, '[HYPERVISOR]', 'BOOT PIPELINE ORCHESTRATION FAILED:', ERR);
        });

      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');

      return ENV;
    }
    case MESSAGETYPES.COMPILESTAGE:
    case MESSAGETYPES.COMPILE_STAGE: {
      var SP3 = MESSAGE.STAGEPATH || MESSAGE.stagePath || ['pipeline', 'elements', 0];
      logdebug(ENV, '[HYPERVISOR]', 'ACTION COMPILESTAGE:', PIPELINEID, 'STAGEPATH:', JSON.stringify(SP3));
      COMPILESTAGEFROMSTOREDDNA(
        HYPERSLICE,
        PIPELINEID,
        SP3,
        MESSAGE.ENV || {},
        MESSAGE.OPTIONS || {}
      ).then(function(RES) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RES, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      }).catch(function(ERR) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: ERR.message || String(ERR) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      });
      return ENV;
    }
    case MESSAGETYPES.STAGECOMPLETED:
    case MESSAGETYPES.STAGE_COMPLETED: {
      HANDLESTAGECOMPLETED(HYPERSLICE, MESSAGE);
      return ENV;
    }
    default:
      logwarn(ENV, '[HYPERVISOR]', 'UNKNOWN MESSAGE TYPE:', MESSAGE.TYPE);
      return ENV;
  }
}

function ENQUEUEHYPERVISOR(TYPE, PAYLOAD, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('HYPERVISORACTOR', TYPE, PAYLOAD || {}, TAG, 'system', RESPONSESPEC);
}

function ENQUEUEHYPERVISORLOAD(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.LOAD, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORSAVE(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.SAVE, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORGETENV(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETENV || MESSAGETYPES.GET_ENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETENV(PIPELINEID, ENV, STAGEID, ELEMENTID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETENV || MESSAGETYPES.SET_ENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, ENV: ENV, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETLATESTENV(PIPELINEID, STAGEID, ELEMENTID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETLATESTENV || MESSAGETYPES.GET_LATEST_ENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETRENDERHTML(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETRENDERHTML || MESSAGETYPES.GET_RENDER_HTML;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETRENDERHTML(HTML, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETRENDERHTML || MESSAGETYPES.SET_RENDER_HTML;
  return ENQUEUEHYPERVISOR(TYPE, { HTML: HTML }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETEXECUTIONSTACK(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETEXECUTIONSTACK || MESSAGETYPES.GET_EXECUTION_STACK;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETEXECUTIONSTACK(STACK, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETEXECUTIONSTACK || MESSAGETYPES.SET_EXECUTION_STACK;
  return ENQUEUEHYPERVISOR(TYPE, { STACK: STACK }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETROUTE(KEY, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETROUTE || MESSAGETYPES.GET_ROUTE;
  return ENQUEUEHYPERVISOR(TYPE, { KEY: KEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETROUTE(KEY, ROUTE, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETROUTE || MESSAGETYPES.SET_ROUTE;
  return ENQUEUEHYPERVISOR(TYPE, { KEY: KEY, ROUTE: ROUTE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETACTIVEPIPELINES(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETACTIVEPIPELINES || MESSAGETYPES.GET_ACTIVE_PIPELINES;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.REGISTERPIPELINE || MESSAGETYPES.REGISTER_PIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORUNREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.UNREGISTERPIPELINE || MESSAGETYPES.UNREGISTER_PIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETPROGRAM(PROGRAMKEY, PROGRAMSOURCE, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETPROGRAM || MESSAGETYPES.SET_PROGRAM;
  return ENQUEUEHYPERVISOR(TYPE, { PROGRAMKEY: PROGRAMKEY, PROGRAMSOURCE: PROGRAMSOURCE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETPROGRAM(PROGRAMKEY, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETPROGRAM || MESSAGETYPES.GET_PROGRAM;
  return ENQUEUEHYPERVISOR(TYPE, { PROGRAMKEY: PROGRAMKEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORMARKBOOT(BOOT, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.MARKBOOT || MESSAGETYPES.MARK_BOOT;
  return ENQUEUEHYPERVISOR(TYPE, { BOOT: BOOT }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORPING(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.PING, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORACTIVATEACTORS(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.ACTIVATEACTORS || MESSAGETYPES.ACTIVATE_ACTORS;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORBOOTPIPELINE(PAYLOAD, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.BOOTPIPELINE || MESSAGETYPES.BOOT_PIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, PAYLOAD, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSTAGECOMPLETED(PIPELINEID, STAGEID, NEXTSTAGEMESSAGE, ENV, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.STAGECOMPLETED || MESSAGETYPES.STAGE_COMPLETED;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, STAGEID: STAGEID, NEXTSTAGEMESSAGE: NEXTSTAGEMESSAGE, ENV: ENV }, RESPONSESPEC);
}

function STARTHYPERVISORACTOR(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS :
      (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      if (ENV) ENV.VERBOSITY = LVL;
    }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('HYPERVISORACTOR', HYPERVISORBEHAVIOR, MESSAGE); }
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    HYPERVISORVERBOSITYCONSTANTS: HYPERVISORVERBOSITYCONSTANTS,
    ENSUREHYPERVISORSLICE: ENSUREHYPERVISORSLICE,
    CREATEHYPERVISORERRORCONTEXT: CREATEHYPERVISORERRORCONTEXT,
    REGISTERHYPERVISORPIPELINE: REGISTERHYPERVISORPIPELINE,
    COMPILESTAGEFROMSTOREDDNA: COMPILESTAGEFROMSTOREDDNA,
    HANDLESTAGECOMPLETED: HANDLESTAGECOMPLETED,
    HYPERVISORBEHAVIOR: HYPERVISORBEHAVIOR,
    ENQUEUEHYPERVISOR: ENQUEUEHYPERVISOR,
    ENQUEUEHYPERVISORLOAD: ENQUEUEHYPERVISORLOAD,
    ENQUEUEHYPERVISORSAVE: ENQUEUEHYPERVISORSAVE,
    ENQUEUEHYPERVISORGETENV: ENQUEUEHYPERVISORGETENV,
    ENQUEUEHYPERVISORSETENV: ENQUEUEHYPERVISORSETENV,
    ENQUEUEHYPERVISORGETLATESTENV: ENQUEUEHYPERVISORGETLATESTENV,
    ENQUEUEHYPERVISORGETRENDERHTML: ENQUEUEHYPERVISORGETRENDERHTML,
    ENQUEUEHYPERVISORSETRENDERHTML: ENQUEUEHYPERVISORSETRENDERHTML,
    ENQUEUEHYPERVISORGETEXECUTIONSTACK: ENQUEUEHYPERVISORGETEXECUTIONSTACK,
    ENQUEUEHYPERVISORSETEXECUTIONSTACK: ENQUEUEHYPERVISORSETEXECUTIONSTACK,
    ENQUEUEHYPERVISORGETROUTE: ENQUEUEHYPERVISORGETROUTE,
    ENQUEUEHYPERVISORSETROUTE: ENQUEUEHYPERVISORSETROUTE,
    ENQUEUEHYPERVISORGETACTIVEPIPELINES: ENQUEUEHYPERVISORGETACTIVEPIPELINES,
    ENQUEUEHYPERVISORREGISTERPIPELINE: ENQUEUEHYPERVISORREGISTERPIPELINE,
    ENQUEUEHYPERVISORUNREGISTERPIPELINE: ENQUEUEHYPERVISORUNREGISTERPIPELINE,
    ENQUEUEHYPERVISORSETPROGRAM: ENQUEUEHYPERVISORSETPROGRAM,
    ENQUEUEHYPERVISORGETPROGRAM: ENQUEUEHYPERVISORGETPROGRAM,
    ENQUEUEHYPERVISORMARKBOOT: ENQUEUEHYPERVISORMARKBOOT,
    ENQUEUEHYPERVISORPING: ENQUEUEHYPERVISORPING,
    ENQUEUEHYPERVISORACTIVATEACTORS: ENQUEUEHYPERVISORACTIVATEACTORS,
    ENQUEUEHYPERVISORBOOTPIPELINE: ENQUEUEHYPERVISORBOOTPIPELINE,
    ENQUEUEHYPERVISORSTAGECOMPLETED: ENQUEUEHYPERVISORSTAGECOMPLETED,
    STARTHYPERVISORACTOR: STARTHYPERVISORACTOR
  };
}
