var HYPERVISORVERBOSITYCONSTANTS = createverbosityconstants();

// ===== ADDED: safety check for global =====
if (typeof loadPipeline === 'undefined') {
  throw new Error('[HYPERVISORACTOR] loadPipeline is not defined. Ensure blockcompiler.js is loaded first.');
}
// ===== END ADDED =====

function ENSUREHYPERVISORSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'hypervisor', function() {
    return {
      BOOT: true,
      ENVBYPIPELINE: {},
      RENDERHTML: '',
      EXECUTIONSTACK: [],
      ROUTES: {},
      ACTIVEPIPELINES: [],
      PROGRAMS: {},
      LOADEDPIPELINES: {},
      NEXTSTAGEMESSAGES: {}
    };
  });
}

function CREATEHYPERVISORERRORCONTEXT(LABEL) {
  return function(ERR) {
    if (!ERR) ERR = new Error('unknown hypervisor error');
    if (!ERR.DIAGNOSTIC) ERR.DIAGNOSTIC = {};
    ERR.DIAGNOSTIC.HYPERVISORSTAGE = LABEL;
    throw ERR;
  };
}

function REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID) {
  if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
  if (HYPERSLICE.ACTIVEPIPELINES.indexOf(PIPELINEID) === -1) {
    HYPERSLICE.ACTIVEPIPELINES.push(PIPELINEID);
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
    }, GENERATETAG(), 'HYPERVISORACTOR');
  }
}

function COMPILESTAGEFROMSTOREDDNA(HYPERSLICE, PIPELINEID, STAGEPATH, ENV, OPTIONS) {
  var LOADED = HYPERSLICE.LOADEDPIPELINES || HYPERSLICE.LOADEDPIPELINES;
  var ENTRY = LOADED && LOADED[PIPELINEID];
  if (!ENTRY || !ENTRY.DNA) {
    return Promise.resolve({ ERROR: 'missing DNA for pipeline: ' + PIPELINEID });
  }
  var ENVMAP = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
  var LATESTENV = (ENVMAP && ENVMAP[PIPELINEID] && ENVMAP[PIPELINEID].ENV) || ENV || {};
  var COMPFN = (typeof blockcompilercompilestage === 'function') ? blockcompilercompilestage :
    ((typeof blockcompilercompilestage === 'function') ? blockcompilercompilestage :
    ((typeof compilestage === 'function') ? compilestage : function() { return Promise.resolve(); }));
  return COMPFN(ENTRY.DNA, STAGEPATH, LATESTENV, OPTIONS || {});
}

function HANDLESTAGECOMPLETED(HYPERSLICE, MESSAGE) {
  var PIPELINEID = MESSAGE.PIPELINEID || MESSAGE.pipelineId;
  var STAGEID = MESSAGE.STAGEID || MESSAGE.stageId;
  var KEY = PIPELINEID + ':' + STAGEID;
  loginfo(HYPERSLICE, '[HYPERVISOR]', 'ACTION STAGECOMPLETED:', KEY);

  if (MESSAGE.SENDER && MESSAGE.TAG) {
    var ACKTYPE = MESSAGETYPES.STAGECOMPLETEDACK || MESSAGETYPES.STAGECOMPLETEDACK;
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STAGEID: STAGEID }, 'HYPERVISORACTOR', ACKTYPE);
  }

  if (MESSAGE.ENV !== undefined && MESSAGE.ENV !== null) {
    if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = HYPERSLICE.ENVBYPIPELINE || {};
    if (!HYPERSLICE.ENVBYPIPELINE[PIPELINEID]) HYPERSLICE.ENVBYPIPELINE[PIPELINEID] = {};
    HYPERSLICE.ENVBYPIPELINE[PIPELINEID].ENV = MESSAGE.ENV;
    HYPERSLICE.ENVBYPIPELINE[PIPELINEID].UPDATEDAT = Date.now();
    SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
      UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
    }, GENERATETAG(), 'HYPERVISORACTOR');
  }

  var NEXTMSGMAP = HYPERSLICE.NEXTSTAGEMESSAGES || HYPERSLICE.NEXTSTAGEMESSAGES || {};
  var NEXTMSG = MESSAGE.NEXTSTAGEMESSAGE || MESSAGE.nextStageMessage || NEXTMSGMAP[KEY];
  if (NEXTMSG) {
    if (NEXTMSGMAP[KEY]) delete NEXTMSGMAP[KEY];
    var NEXTSTAGEPATH;
    var SP = NEXTMSG.STAGEPATH || NEXTMSG.stagePath;
    if (SP && Array.isArray(SP) && SP.length > 0) {
      NEXTSTAGEPATH = SP;
    } else {
      var SIDX = (NEXTMSG.STAGEINDEX !== undefined) ? NEXTMSG.STAGEINDEX : NEXTMSG.stageIndex;
      NEXTSTAGEPATH = ['pipeline', 'elements', SIDX];
    }
    var TARGETPIPE = NEXTMSG.PIPELINEID || NEXTMSG.pipelineId || PIPELINEID;
    COMPILESTAGEFROMSTOREDDNA(
      HYPERSLICE,
      TARGETPIPE,
      NEXTSTAGEPATH,
      NEXTMSG.ENV || MESSAGE.ENV || {},
      NEXTMSG.OPTIONS || {}
    ).then(function() {
      // Next stage will send its own stagecompleted
    }).catch(function(ERR) {
      logwarn(HYPERSLICE, '[HYPERVISOR]', 'NEXT STAGE ORCHESTRATION FAILED:', ERR);
    });
  } else {
    loginfo(HYPERSLICE, '[HYPERVISOR]', 'NO NEXT SEQUENTIAL STAGE FOR PIPELINE:', PIPELINEID);
  }
}

// Pure behavior function: (env, message) -> env
function HYPERVISORBEHAVIOR(ENV, MESSAGE) {
  logdebug(ENV, '[HYPERVISOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE);

  var HYPERSLICE = ENSUREHYPERVISORSLICE(ENV);
  var PIPELINEID = MESSAGE.PIPELINEID || MESSAGE.pipelineId;

  switch (MESSAGE.TYPE) {
    case MESSAGETYPES.LOAD:
      return ENV;
    case MESSAGETYPES.SAVE:
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETENV:
    case MESSAGETYPES.GETENV: {
      var ENVMAP = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
      var P = ENVMAP && ENVMAP[PIPELINEID];
      var RESULT = P ? P.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RESULT, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.SETENV:
    case MESSAGETYPES.SETENV: {
      if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = HYPERSLICE.ENVBYPIPELINE || {};
      if (!HYPERSLICE.ENVBYPIPELINE[PIPELINEID]) HYPERSLICE.ENVBYPIPELINE[PIPELINEID] = {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].ENV = MESSAGE.ENV || {};
      HYPERSLICE.ENVBYPIPELINE[PIPELINEID].UPDATEDAT = Date.now();
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETLATESTENV:
    case MESSAGETYPES.GETLATESTENV: {
      var ENVMAP2 = HYPERSLICE.ENVBYPIPELINE || HYPERSLICE.ENVBYPIPELINE;
      var PSTATE = ENVMAP2 && ENVMAP2[PIPELINEID];
      var LATEST = PSTATE ? PSTATE.ENV : null;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, LATEST, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.GETRENDERHTML:
    case MESSAGETYPES.GETRENDERHTML:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.RENDERHTML || HYPERSLICE.RENDERHTML || '', 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETRENDERHTML:
    case MESSAGETYPES.SETRENDERHTML:
      HYPERSLICE.RENDERHTML = MESSAGE.HTML || '';
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETEXECUTIONSTACK:
    case MESSAGETYPES.GETEXECUTIONSTACK:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.EXECUTIONSTACK || HYPERSLICE.EXECUTIONSTACK || [], 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETEXECUTIONSTACK:
    case MESSAGETYPES.SETEXECUTIONSTACK:
      HYPERSLICE.EXECUTIONSTACK = MESSAGE.STACK || [];
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETROUTE:
    case MESSAGETYPES.GETROUTE:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.ROUTES && MESSAGE.KEY ? (HYPERSLICE.ROUTES[MESSAGE.KEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.SETROUTE:
    case MESSAGETYPES.SETROUTE:
      if (!HYPERSLICE.ROUTES) HYPERSLICE.ROUTES = {};
      HYPERSLICE.ROUTES[MESSAGE.KEY] = MESSAGE.ROUTE || null;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.GETACTIVEPIPELINES:
    case MESSAGETYPES.GETACTIVEPIPELINES:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, (HYPERSLICE.ACTIVEPIPELINES || HYPERSLICE.ACTIVEPIPELINES || []).slice(), 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.REGISTERPIPELINE:
    case MESSAGETYPES.REGISTERPIPELINE:
      REGISTERHYPERVISORPIPELINE(HYPERSLICE, PIPELINEID);
      return ENV;
    case MESSAGETYPES.UNREGISTERPIPELINE:
    case MESSAGETYPES.UNREGISTERPIPELINE:
      if (!HYPERSLICE.ACTIVEPIPELINES) HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES || [];
      HYPERSLICE.ACTIVEPIPELINES = HYPERSLICE.ACTIVEPIPELINES.filter(function(ID) { return ID !== PIPELINEID; });
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.SETPROGRAM:
    case MESSAGETYPES.SETPROGRAM: {
      var PROGKEY = MESSAGE.PROGRAMKEY || MESSAGE.programKey;
      var PROGSOURCE = MESSAGE.PROGRAMSOURCE || MESSAGE.programSource;
      if (!HYPERSLICE.PROGRAMS) HYPERSLICE.PROGRAMS = {};
      HYPERSLICE.PROGRAMS[PROGKEY] = PROGSOURCE;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    }
    case MESSAGETYPES.GETPROGRAM:
    case MESSAGETYPES.GETPROGRAM: {
      var PKEY = MESSAGE.PROGRAMKEY || MESSAGE.programKey;
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, HYPERSLICE.PROGRAMS && PKEY ? (HYPERSLICE.PROGRAMS[PKEY] || null) : null, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    }
    case MESSAGETYPES.MARKBOOT:
    case MESSAGETYPES.MARKBOOT:
      HYPERSLICE.BOOT = MESSAGE.BOOT !== false;
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
      }, GENERATETAG(), 'HYPERVISORACTOR');
      return ENV;
    case MESSAGETYPES.EVENTTRIGGERED:
    case MESSAGETYPES.EVENTTRIGGERED: {
      var STAGEID = MESSAGE.STAGEID || MESSAGE.stageId;
      var STAGEPATH = MESSAGE.STAGEPATH || MESSAGE.stagePath || ['pipeline', 'elements', -1];

      var LOADEDMAP = HYPERSLICE.LOADEDPIPELINES || HYPERSLICE.LOADEDPIPELINES;
      var LOADEDENTRY = LOADEDMAP && LOADEDMAP[PIPELINEID];
      if (!LOADEDENTRY || !LOADEDENTRY.DNA) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: 'missing loaded pipeline DNA' }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        return ENV;
      }

      loginfo(ENV, '[HYPERVISOR]', 'EVENTTRIGGERED COMPILING STAGE:', PIPELINEID, STAGEID, STAGEPATH);

      var EVENTOPTIONS = LOADEDENTRY.OPTIONS || {};
      EVENTOPTIONS.ISEVENTTRIGGER = true;

      COMPILESTAGEFROMSTOREDDNA(HYPERSLICE, PIPELINEID, STAGEPATH, {}, EVENTOPTIONS)
        .then(function() {
          if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { STARTED: true }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        })
        .catch(function(ERR) {
          logwarn(ENV, '[HYPERVISOR]', 'EVENTTRIGGERED COMPILATION FAILED:', ERR);
          if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: ERR.message || String(ERR) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
        });
      return ENV;
    }
    case MESSAGETYPES.PING:
      if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, true, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      return ENV;
    case MESSAGETYPES.RECOVER:
      DBRESTORE('actor:state:hypervisor').then(function(SAVED) {
        if (SAVED && typeof SAVED === 'object') ENV.HYPERVISOR = SAVED;
        else ENV.HYPERVISOR = {
          BOOT: true, ENVBYPIPELINE: {}, RENDERHTML: '', EXECUTIONSTACK: [],
          ROUTES: {}, ACTIVEPIPELINES: [], PROGRAMS: {}, LOADEDPIPELINES: {}, NEXTSTAGEMESSAGES: {}
        };
        SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
          UPDATES: [{ PATH: 'hypervisor', VALUE: ENV.HYPERVISOR }]
        }, GENERATETAG(), 'HYPERVISORACTOR');
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, ENV, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      }).catch(function(E) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: E.message || String(E) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      });
      return ENV;
    case MESSAGETYPES.ACTIVATEACTORS:
    case MESSAGETYPES.ACTIVATEACTORS:
      return ENV;

    case MESSAGETYPES.BOOTDNA: {
      loginfo(ENV, '[HYPERVISOR]', 'ACTION BOOTDNA for pipeline:', MESSAGE.pipelineId);

      var dna = MESSAGE.dna;
      var pipelineId = MESSAGE.pipelineId || (dna && dna.pipelineid);
      var options = MESSAGE.options || {};

      if (!dna || !pipelineId) {
        if (MESSAGE.SENDER && MESSAGE.TAG) {
          SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, {
            ERROR: 'BOOTDNA: missing dna or pipelineId',
            type: 'BOOTERROR'
          }, 'HYPERVISORACTOR', MESSAGETYPES.PIPELINEBOOTED);
        }
        return ENV;
      }

      if (!HYPERSLICE.LOADEDPIPELINES) HYPERSLICE.LOADEDPIPELINES = {};
      if (!HYPERSLICE.LOADEDPIPELINES[pipelineId]) {
        HYPERSLICE.LOADEDPIPELINES[pipelineId] = {
          DNA: dna,
          OPTIONS: options,
          ACCESSORS: null,
          SINKS: []
        };
      }

      var existingEnv = HYPERSLICE.ENVBYPIPELINE && HYPERSLICE.ENVBYPIPELINE[pipelineId];
      var stageIndex = 0;
      var env = {};

      if (existingEnv && existingEnv.ENV && existingEnv.currentStageIndex !== undefined) {
        stageIndex = existingEnv.currentStageIndex;
        env = existingEnv.ENV;
        loginfo(ENV, '[HYPERVISOR]', 'Resuming pipeline ' + pipelineId + ' at stage ' + stageIndex);
      } else {
        loginfo(ENV, '[HYPERVISOR]', 'Starting new pipeline ' + pipelineId + ' from stage 0');
        if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = {};
        HYPERSLICE.ENVBYPIPELINE[pipelineId] = {
          ENV: {},
          currentStageIndex: 0,
          status: 'running',
          startedAt: Date.now()
        };
      }

      // ===== USE GLOBAL loadPipeline =====
      return loadPipeline(dna, stageIndex, env, options)
        .then(function(result) {
          var newEnv = result.env || env;
          var nextStageIndex = result.nextStageIndex;

          if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = {};
          if (!HYPERSLICE.ENVBYPIPELINE[pipelineId]) HYPERSLICE.ENVBYPIPELINE[pipelineId] = {};
          HYPERSLICE.ENVBYPIPELINE[pipelineId].ENV = newEnv;
          HYPERSLICE.ENVBYPIPELINE[pipelineId].currentStageIndex = nextStageIndex !== null ? nextStageIndex : -1;
          HYPERSLICE.ENVBYPIPELINE[pipelineId].status = (nextStageIndex === null) ? 'complete' : 'running';
          if (nextStageIndex === null) {
            HYPERSLICE.ENVBYPIPELINE[pipelineId].completedAt = Date.now();
          }
          SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
            UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
          }, GENERATETAG(), 'HYPERVISORACTOR');

          var responsePayload = {
            type: 'BOOTREADY',
            pipelineId: pipelineId,
            env: newEnv,
            currentStageIndex: nextStageIndex,
            status: HYPERSLICE.ENVBYPIPELINE[pipelineId].status
          };
          if (MESSAGE.SENDER && MESSAGE.TAG) {
            SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, responsePayload, 'HYPERVISORACTOR', MESSAGETYPES.PIPELINEBOOTED);
          }
          return ENV;
        })
        .catch(function(err) {
          logerror(ENV, '[HYPERVISOR]', 'BOOTDNA stage compilation failed:', err);
          var errorPayload = {
            type: 'BOOTERROR',
            pipelineId: pipelineId,
            ERROR: err.message || String(err),
            DIAGNOSTIC: err.diagnostic || {}
          };
          if (MESSAGE.SENDER && MESSAGE.TAG) {
            SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, errorPayload, 'HYPERVISORACTOR', MESSAGETYPES.PIPELINEBOOTED);
          }
          if (HYPERSLICE.ENVBYPIPELINE && HYPERSLICE.ENVBYPIPELINE[pipelineId]) {
            HYPERSLICE.ENVBYPIPELINE[pipelineId].status = 'error';
          }
          return ENV;
        });
    }

    case MESSAGETYPES.COMPILESTAGE:
    case MESSAGETYPES.COMPILESTAGE: {
      var STAGEPATH = MESSAGE.STAGEPATH || MESSAGE.stagePath || ['pipeline', 'elements', 0];
      logdebug(ENV, '[HYPERVISOR]', 'ACTION COMPILESTAGE:', PIPELINEID, 'STAGEPATH:', JSON.stringify(STAGEPATH));
      COMPILESTAGEFROMSTOREDDNA(
        HYPERSLICE,
        PIPELINEID,
        STAGEPATH,
        MESSAGE.ENV || {},
        MESSAGE.OPTIONS || {}
      ).then(function(RES) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RES, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      }).catch(function(ERR) {
        if (MESSAGE.SENDER && MESSAGE.TAG) SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: ERR.message || String(ERR) }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
      });
      return ENV;
    }

    case MESSAGETYPES.STAGECOMPLETED:
    case MESSAGETYPES.STAGECOMPLETED: {
      loginfo(ENV, '[HYPERVISOR]', 'ACTION STAGECOMPLETED for pipeline:', MESSAGE.pipelineId, 'stage:', MESSAGE.stageId);
      var pipeId = MESSAGE.PIPELINEID || MESSAGE.pipelineId;
      var stageId = MESSAGE.STAGEID || MESSAGE.stageId;

      if (MESSAGE.ENV !== undefined && MESSAGE.ENV !== null) {
        if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = {};
        if (!HYPERSLICE.ENVBYPIPELINE[pipeId]) HYPERSLICE.ENVBYPIPELINE[pipeId] = {};
        HYPERSLICE.ENVBYPIPELINE[pipeId].ENV = MESSAGE.ENV;
        HYPERSLICE.ENVBYPIPELINE[pipeId].lastStageId = stageId;
        HYPERSLICE.ENVBYPIPELINE[pipeId].updatedAt = Date.now();
        SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
          UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
        }, GENERATETAG(), 'HYPERVISORACTOR');
      }

      var nextStageIndex = null;
      var nextMsg = MESSAGE.NEXTSTAGEMESSAGE || MESSAGE.nextStageMessage;
      if (nextMsg) {
        if (nextMsg.stageindex !== undefined) nextStageIndex = nextMsg.stageindex;
        else if (nextMsg.stageIndex !== undefined) nextStageIndex = nextMsg.stageIndex;
        else if (nextMsg.STAGEINDEX !== undefined) nextStageIndex = nextMsg.STAGEINDEX;
      }

      if (nextStageIndex !== null && nextStageIndex >= 0) {
        loginfo(ENV, '[HYPERVISOR]', 'Continuing pipeline ' + pipeId + ' to stage ' + nextStageIndex);
        var dnaEntry = HYPERSLICE.LOADEDPIPELINES && HYPERSLICE.LOADEDPIPELINES[pipeId];
        if (!dnaEntry || !dnaEntry.DNA) {
          logwarn(ENV, '[HYPERVISOR]', 'Missing DNA for pipeline ' + pipeId + ' – cannot continue');
          if (MESSAGE.SENDER && MESSAGE.TAG) {
            SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, { ERROR: 'Missing DNA for continuation' }, 'HYPERVISORACTOR', MESSAGETYPES.RESPONSE);
          }
          return ENV;
        }
        var dna = dnaEntry.DNA;
        var env = MESSAGE.ENV || HYPERSLICE.ENVBYPIPELINE[pipeId].ENV || {};
        var options = dnaEntry.OPTIONS || {};

        // ===== USE GLOBAL loadPipeline =====
        loadPipeline(dna, nextStageIndex, env, options)
          .then(function(result) {
            var newEnv = result.env || env;
            var nextNextIndex = result.nextStageIndex;

            if (!HYPERSLICE.ENVBYPIPELINE) HYPERSLICE.ENVBYPIPELINE = {};
            if (!HYPERSLICE.ENVBYPIPELINE[pipeId]) HYPERSLICE.ENVBYPIPELINE[pipeId] = {};
            HYPERSLICE.ENVBYPIPELINE[pipeId].ENV = newEnv;
            HYPERSLICE.ENVBYPIPELINE[pipeId].currentStageIndex = nextNextIndex !== null ? nextNextIndex : -1;
            HYPERSLICE.ENVBYPIPELINE[pipeId].status = (nextNextIndex === null) ? 'complete' : 'running';
            if (nextNextIndex === null) {
              HYPERSLICE.ENVBYPIPELINE[pipeId].completedAt = Date.now();
            }
            SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
              UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
            }, GENERATETAG(), 'HYPERVISORACTOR');

            if (MESSAGE.SENDER && MESSAGE.TAG) {
              SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, {
                stageId: stageId,
                pipelineId: pipeId,
                nextStageIndex: nextNextIndex,
                status: HYPERSLICE.ENVBYPIPELINE[pipeId].status
              }, 'HYPERVISORACTOR', MESSAGETYPES.STAGECOMPLETEDACK);
            }
          })
          .catch(function(err) {
            logerror(ENV, '[HYPERVISOR]', 'Failed to compile next stage for pipeline ' + pipeId + ':', err);
            if (MESSAGE.SENDER && MESSAGE.TAG) {
              SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, {
                ERROR: err.message || String(err),
                DIAGNOSTIC: err.diagnostic || {}
              }, 'HYPERVISORACTOR', MESSAGETYPES.STAGECOMPLETEDACK);
            }
            if (HYPERSLICE.ENVBYPIPELINE && HYPERSLICE.ENVBYPIPELINE[pipeId]) {
              HYPERSLICE.ENVBYPIPELINE[pipeId].status = 'error';
            }
          });
      } else {
        loginfo(ENV, '[HYPERVISOR]', 'Pipeline ' + pipeId + ' completed.');
        if (HYPERSLICE.ENVBYPIPELINE && HYPERSLICE.ENVBYPIPELINE[pipeId]) {
          HYPERSLICE.ENVBYPIPELINE[pipeId].status = 'complete';
          HYPERSLICE.ENVBYPIPELINE[pipeId].completedAt = Date.now();
        }
        SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
          UPDATES: [{ PATH: 'hypervisor', VALUE: HYPERSLICE }]
        }, GENERATETAG(), 'HYPERVISORACTOR');
        if (MESSAGE.SENDER && MESSAGE.TAG) {
          SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, {
            stageId: stageId,
            pipelineId: pipeId,
            status: 'complete'
          }, 'HYPERVISORACTOR', MESSAGETYPES.STAGECOMPLETEDACK);
        }
      }
      return ENV;
    }

    default:
      logwarn(ENV, '[HYPERVISOR]', 'UNKNOWN MESSAGE TYPE:', MESSAGE.TYPE);
      return ENV;
  }
}

function ENQUEUEHYPERVISOR(TYPE, PAYLOAD, RESPONSESPEC) {
  var TAG = GENERATETAG();
  SENDINSTRUCTION('HYPERVISORACTOR', TYPE, PAYLOAD || {}, TAG, 'system', RESPONSESPEC);
}

function ENQUEUEHYPERVISORLOAD(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.LOAD, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORSAVE(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.SAVE, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORGETENV(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETENV || MESSAGETYPES.GETENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETENV(PIPELINEID, ENV, STAGEID, ELEMENTID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETENV || MESSAGETYPES.SETENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, ENV: ENV, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETLATESTENV(PIPELINEID, STAGEID, ELEMENTID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETLATESTENV || MESSAGETYPES.GETLATESTENV;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, STAGEID: STAGEID, ELEMENTID: ELEMENTID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETRENDERHTML(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETRENDERHTML || MESSAGETYPES.GETRENDERHTML;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETRENDERHTML(HTML, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETRENDERHTML || MESSAGETYPES.SETRENDERHTML;
  return ENQUEUEHYPERVISOR(TYPE, { HTML: HTML }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETEXECUTIONSTACK(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETEXECUTIONSTACK || MESSAGETYPES.GETEXECUTIONSTACK;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETEXECUTIONSTACK(STACK, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETEXECUTIONSTACK || MESSAGETYPES.SETEXECUTIONSTACK;
  return ENQUEUEHYPERVISOR(TYPE, { STACK: STACK }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETROUTE(KEY, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETROUTE || MESSAGETYPES.GETROUTE;
  return ENQUEUEHYPERVISOR(TYPE, { KEY: KEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETROUTE(KEY, ROUTE, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETROUTE || MESSAGETYPES.SETROUTE;
  return ENQUEUEHYPERVISOR(TYPE, { KEY: KEY, ROUTE: ROUTE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETACTIVEPIPELINES(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETACTIVEPIPELINES || MESSAGETYPES.GETACTIVEPIPELINES;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.REGISTERPIPELINE || MESSAGETYPES.REGISTERPIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORUNREGISTERPIPELINE(PIPELINEID, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.UNREGISTERPIPELINE || MESSAGETYPES.UNREGISTERPIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSETPROGRAM(PROGRAMKEY, PROGRAMSOURCE, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.SETPROGRAM || MESSAGETYPES.SETPROGRAM;
  return ENQUEUEHYPERVISOR(TYPE, { PROGRAMKEY: PROGRAMKEY, PROGRAMSOURCE: PROGRAMSOURCE }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORGETPROGRAM(PROGRAMKEY, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.GETPROGRAM || MESSAGETYPES.GETPROGRAM;
  return ENQUEUEHYPERVISOR(TYPE, { PROGRAMKEY: PROGRAMKEY }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORMARKBOOT(BOOT, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.MARKBOOT || MESSAGETYPES.MARKBOOT;
  return ENQUEUEHYPERVISOR(TYPE, { BOOT: BOOT }, RESPONSESPEC);
}
function ENQUEUEHYPERVISORPING(RESPONSESPEC) { return ENQUEUEHYPERVISOR(MESSAGETYPES.PING, {}, RESPONSESPEC); }
function ENQUEUEHYPERVISORACTIVATEACTORS(RESPONSESPEC) {
  var TYPE = MESSAGETYPES.ACTIVATEACTORS || MESSAGETYPES.ACTIVATEACTORS;
  return ENQUEUEHYPERVISOR(TYPE, {}, RESPONSESPEC);
}
function ENQUEUEHYPERVISORBOOTPIPELINE(PAYLOAD, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.BOOTPIPELINE || MESSAGETYPES.BOOTPIPELINE;
  return ENQUEUEHYPERVISOR(TYPE, PAYLOAD, RESPONSESPEC);
}
function ENQUEUEHYPERVISORSTAGECOMPLETED(PIPELINEID, STAGEID, NEXTSTAGEMESSAGE, ENV, RESPONSESPEC) {
  var TYPE = MESSAGETYPES.STAGECOMPLETED || MESSAGETYPES.STAGECOMPLETED;
  return ENQUEUEHYPERVISOR(TYPE, { PIPELINEID: PIPELINEID, STAGEID: STAGEID, NEXTSTAGEMESSAGE: NEXTSTAGEMESSAGE, ENV: ENV }, RESPONSESPEC);
}

function STARTHYPERVISORACTOR(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS :
      (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      if (ENV) ENV.VERBOSITY = LVL;
    }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('HYPERVISORACTOR', HYPERVISORBEHAVIOR, MESSAGE); }
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    HYPERVISORVERBOSITYCONSTANTS: HYPERVISORVERBOSITYCONSTANTS,
    ENSUREHYPERVISORSLICE: ENSUREHYPERVISORSLICE,
    CREATEHYPERVISORERRORCONTEXT: CREATEHYPERVISORERRORCONTEXT,
    REGISTERHYPERVISORPIPELINE: REGISTERHYPERVISORPIPELINE,
    COMPILESTAGEFROMSTOREDDNA: COMPILESTAGEFROMSTOREDDNA,
    HANDLESTAGECOMPLETED: HANDLESTAGECOMPLETED,
    HYPERVISORBEHAVIOR: HYPERVISORBEHAVIOR,
    ENQUEUEHYPERVISOR: ENQUEUEHYPERVISOR,
    ENQUEUEHYPERVISORLOAD: ENQUEUEHYPERVISORLOAD,
    ENQUEUEHYPERVISORSAVE: ENQUEUEHYPERVISORSAVE,
    ENQUEUEHYPERVISORGETENV: ENQUEUEHYPERVISORGETENV,
    ENQUEUEHYPERVISORSETENV: ENQUEUEHYPERVISORSETENV,
    ENQUEUEHYPERVISORGETLATESTENV: ENQUEUEHYPERVISORGETLATESTENV,
    ENQUEUEHYPERVISORGETRENDERHTML: ENQUEUEHYPERVISORGETRENDERHTML,
    ENQUEUEHYPERVISORSETRENDERHTML: ENQUEUEHYPERVISORSETRENDERHTML,
    ENQUEUEHYPERVISORGETEXECUTIONSTACK: ENQUEUEHYPERVISORGETEXECUTIONSTACK,
    ENQUEUEHYPERVISORSETEXECUTIONSTACK: ENQUEUEHYPERVISORSETEXECUTIONSTACK,
    ENQUEUEHYPERVISORGETROUTE: ENQUEUEHYPERVISORGETROUTE,
    ENQUEUEHYPERVISORSETROUTE: ENQUEUEHYPERVISORSETROUTE,
    ENQUEUEHYPERVISORGETACTIVEPIPELINES: ENQUEUEHYPERVISORGETACTIVEPIPELINES,
    ENQUEUEHYPERVISORREGISTERPIPELINE: ENQUEUEHYPERVISORREGISTERPIPELINE,
    ENQUEUEHYPERVISORUNREGISTERPIPELINE: ENQUEUEHYPERVISORUNREGISTERPIPELINE,
    ENQUEUEHYPERVISORSETPROGRAM: ENQUEUEHYPERVISORSETPROGRAM,
    ENQUEUEHYPERVISORGETPROGRAM: ENQUEUEHYPERVISORGETPROGRAM,
    ENQUEUEHYPERVISORMARKBOOT: ENQUEUEHYPERVISORMARKBOOT,
    ENQUEUEHYPERVISORPING: ENQUEUEHYPERVISORPING,
    ENQUEUEHYPERVISORACTIVATEACTORS: ENQUEUEHYPERVISORACTIVATEACTORS,
    ENQUEUEHYPERVISORBOOTPIPELINE: ENQUEUEHYPERVISORBOOTPIPELINE,
    ENQUEUEHYPERVISORSTAGECOMPLETED: ENQUEUEHYPERVISORSTAGECOMPLETED,
    STARTHYPERVISORACTOR: STARTHYPERVISORACTOR
  };
}
