var RENDERVERBOSITYCONSTANTS = CREATEVERBOSITYCONSTANTS();

function ENSURERENDERSLICE(ENV) {
  return ENSUREENVSLICE(ENV, 'RENDER', function() {
    return {
      HTML: '',
      VIEWPORT: null,
      ACTORREGISTRY: null,
      GC: (typeof CREATEGARBAGECOLLECTOR === 'function' ? CREATEGARBAGECOLLECTOR() : (typeof CREATEGARBAGECOLLECTOR === 'function' ? CREATEGARBAGECOLLECTOR() : {})),
      TRIGGEROBSERVERINSTALLED: false,
      TRIGGERGCSCHEDULED: false,
      SCRIPTTAGS: []
    };
  });
}

function CREATERENDERERRORCONTEXT(LABEL) {
  return function(ERR) {
    if (!ERR) ERR = new Error('unknown render error');
    if (!ERR.DIAGNOSTIC) ERR.DIAGNOSTIC = {};
    ERR.DIAGNOSTIC.RENDERSTAGE = LABEL;
    throw ERR;
  };
}

function WITHELEMENT(ID, REJECT, FN) {
  if (!ID || typeof ID !== 'string') {
    if (typeof REJECT === 'function') REJECT(new Error('[RENDERACTOR] id must be a non-empty string'));
    return null;
  }
  var EL = DOCUMENT.GETELEMENTBYID(ID);
  if (!EL) {
    if (typeof REJECT === 'function') REJECT(new Error('[RENDERACTOR] element not found: ' + ID));
    return null;
  }
  return FN(EL);
}

function WITHELEMENTRETRY(ID, REJECT, FN, TIMEOUT) {
  if (TIMEOUT === undefined) TIMEOUT = 5000;
  var EXISTING = DOCUMENT.GETELEMENTBYID(ID);
  if (EXISTING) return FN(EXISTING);
  return new Promise(function(RESOLVE, REJECTPROMISE) {
    var OBSERVER = null;
    var TIMEOUTID = setTimeout(function() {
      if (OBSERVER) OBSERVER.DISCONNECT();
      REJECTPROMISE(new Error('[RENDERACTOR] element not found after timeout: ' + ID));
    }, TIMEOUT);
    OBSERVER = new MUTATIONOBSERVER(function() {
      var EL = DOCUMENT.GETELEMENTBYID(ID);
      if (EL) {
        clearTimeout(TIMEOUTID);
        OBSERVER.DISCONNECT();
        try { RESOLVE(FN(EL)); } catch (ERR) { REJECTPROMISE(ERR); }
      }
    });
    OBSERVER.OBSERVE(DOCUMENT.BODY, { CHILDLIST: true, SUBTREE: true });
  });
}

function WAITFORDOMREADY() {
  if (typeof DOCUMENT === 'undefined') return Promise.resolve();
  if (DOCUMENT.READYSTATE === 'loading') {
    return new Promise(function(RESOLVE) { DOCUMENT.ADDEVENTLISTENER('DOMContentLoaded', RESOLVE, { ONCE: true }); });
  }
  if (DOCUMENT.READYSTATE !== 'complete') {
    return new Promise(function(RESOLVE) { WINDOW.ADDEVENTLISTENER('load', RESOLVE, { ONCE: true }); });
  }
  return Promise.resolve();
}

function CREATEEVENTPRODUCERCONSUMER(MSG) {
  return {
    PRODUCER: { TYPE: 'domevent', ID: MSG.SOURCEID, EVENT: MSG.EVENT },
    CONSUMER: { TYPE: 'eventtrigger', PIPELINEID: MSG.PIPELINEID || MSG.PIPELINEID, STAGEID: MSG.STAGEID || MSG.STAGEID },
    METADATA: { STAGEPATH: MSG.STAGEPATH || MSG.STAGEPATH || [], CONTROL: MSG.CONTROL, CHILDREN: MSG.ELEMENTS, ENV: MSG.ENV || {} }
  };
}

function SCHEDULEGCCYCLE(RENDERSLICE) {
  if (!RENDERSLICE) return;
  var SCHEDULED = RENDERSLICE.TRIGGERGCSCHEDULED || RENDERSLICE._TRIGGERGCSCHEDULED;
  if (SCHEDULED) return;
  RENDERSLICE.TRIGGERGCSCHEDULED = true;
  RENDERSLICE._TRIGGERGCSCHEDULED = true;
  setTimeout(function() {
    RENDERSLICE.TRIGGERGCSCHEDULED = false;
    RENDERSLICE._TRIGGERGCSCHEDULED = false;
    var GC = RENDERSLICE.GC || RENDERSLICE._GC;
    if (GC) {
      if (typeof COLLECTENDED === 'function') COLLECTENDED(GC);
      else if (typeof COLLECTENDED === 'function') COLLECTENDED(GC);
    }
  }, 0);
}

function ENSUREEVENTOBSERVER(RENDERSLICE) {
  var INSTALLED = RENDERSLICE && (RENDERSLICE.TRIGGEROBSERVERINSTALLED || RENDERSLICE._TRIGGEROBSERVERINSTALLED);
  if (!RENDERSLICE || INSTALLED) return;
  if (typeof DOCUMENT === 'undefined') return;
  RENDERSLICE.TRIGGEROBSERVERINSTALLED = true;
  RENDERSLICE._TRIGGEROBSERVERINSTALLED = true;
  LOGINFO(RENDERSLICE, '[RENDERACTOR]', 'INSTALLING GLOBAL DOM EVENT OBSERVER FOR EVENT STAGES');

  var HANDLER = function(EVENT) {
    var TARGET = EVENT.TARGET;
    var TARGETID = TARGET && TARGET.ID;
    var GC = RENDERSLICE.GC || RENDERSLICE._GC;
    if (!TARGETID || !GC) return;

    var LISTFN = (typeof LISTOBJECTS === 'function') ? LISTOBJECTS : LISTOBJECTS;
    var INCSENTFN = (typeof INCREMENTSENT === 'function') ? INCREMENTSENT : INCREMENTSENT;
    var MATCHINGOBJECTS = LISTFN(GC).filter(function(GCOBJ) {
      var PRODUCER = GCOBJ.PRODUCER || {};
      return (PRODUCER.TYPE === 'domevent' || PRODUCER.TYPE === 'DOM-EVENT') &&
             PRODUCER.ID === TARGETID &&
             PRODUCER.EVENT === EVENT.TYPE;
    });

    if (MATCHINGOBJECTS.length === 0) return;

    var FIRSTCONSUMER = MATCHINGOBJECTS[0].CONSUMER || {};
    LOGINFO(RENDERSLICE, '[RENDERACTOR]', 'EVENT OBSERVED:', {
      SOURCEID: TARGETID,
      EVENT: EVENT.TYPE,
      PIPELINEID: FIRSTCONSUMER.PIPELINEID || FIRSTCONSUMER.PIPELINEID,
      STAGEID: FIRSTCONSUMER.STAGEID || FIRSTCONSUMER.STAGEID
    });

    MATCHINGOBJECTS.forEach(function(GCOBJ) {
      INCSENTFN(GC, GCOBJ.ID, 1);

      var CONSUMER = GCOBJ.CONSUMER || {};
      var METADATA = GCOBJ.METADATA || {};
      var PIPELINEID = CONSUMER.PIPELINEID || CONSUMER.PIPELINEID;
      var STAGEID = CONSUMER.STAGEID || CONSUMER.STAGEID;
      var STAGEPATH = METADATA.STAGEPATH || METADATA.STAGEPATH || [STAGEID];

      var EVENTTRIGGERPAYLOAD = {
        PIPELINEID: PIPELINEID,
        STAGEID: STAGEID,
        STAGEPATH: STAGEPATH,
        EVENTPAYLOAD: { TYPE: EVENT.TYPE, TARGETID: TARGETID }
      };

      var MSGTYPE = MESSAGETYPES.EVENTTRIGGERED || MESSAGETYPES.EVENT_TRIGGERED;
      SENDINSTRUCTION('HYPERVISORACTOR', MSGTYPE, EVENTTRIGGERPAYLOAD, null, 'RENDERACTOR');

      LOGDEBUG(RENDERSLICE, '[RENDERACTOR]', 'EVENTTRIGGERED SENT TO HYPERVISORACTOR FOR', STAGEID);
    });
  };

  DOCUMENT.ADDEVENTLISTENER('click', HANDLER, true);
  DOCUMENT.ADDEVENTLISTENER('input', HANDLER, true);
  DOCUMENT.ADDEVENTLISTENER('change', HANDLER, true);
  LOGINFO(RENDERSLICE, '[RENDERACTOR]', 'GLOBAL EVENT OBSERVER INSTALLED FOR CLICK/INPUT/CHANGE');
}

var HANDLERS = {};
HANDLERS[MESSAGETYPES.RENDER] = function(ENV, MSG) {
  var TARGET = MSG.ID ? DOCUMENT.GETELEMENTBYID(MSG.ID) : null;
  if (typeof MSG.RENDERER === 'function') {
    try { MSG.RENDERER(TARGET, MSG.DATA, MSG.ENV || {}); } catch (ERR) { CONSOLE.ERROR('[RENDERACTOR] Renderer error:', ERR); throw ERR; }
  }
  return true;
};
HANDLERS[MESSAGETYPES.CLEAR] = function(ENV, MSG) {
  WITHELEMENT(MSG.ID, null, function(EL) { EL.INNERHTML = ''; });
  return true;
};
HANDLERS[MESSAGETYPES.HTML] = function(ENV, MSG) {
  WAITFORDOMREADY().then(function() {
    WITHELEMENTRETRY(MSG.ID, null, function(EL) {
      if (MSG.APPEND) EL.INSERTADJACENTHTML('beforeend', MSG.MARKUP);
      else EL.INNERHTML = MSG.MARKUP;
    });
    RESPONDIFNEEDED(ENV, MSG, true);
  }).catch(function(ERR) {
    RESPONDIFNEEDED(ENV, MSG, { ERROR: ERR.MESSAGE || String(ERR) });
  });
};
HANDLERS[MESSAGETYPES.REMOVE] = function(ENV, MSG) {
  WITHELEMENT(MSG.ID, null, function(EL) { EL.REMOVE(); });
  return true;
};
HANDLERS[MESSAGETYPES.SETSTYLES] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) {
    Object.keys(MSG.STYLES || {}).forEach(function(PROP) { EL.STYLE[PROP] = MSG.STYLES[PROP]; });
  });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.SETATTR] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { EL.SETATTRIBUTE(MSG.NAME, MSG.VALUE); });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.TOGGLECLASS] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { EL.CLASSLIST.TOGGLE(MSG.CLASSNAME, MSG.FORCE); });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.CRYPTO] = function(ENV, MSG) {
  var WIN = typeof WINDOW !== 'undefined' ? WINDOW : (typeof SELF !== 'undefined' ? SELF : (typeof GLOBAL !== 'undefined' ? GLOBAL : null));
  var ARRAY = new Uint8Array(MSG.BYTES);
  WIN.CRYPTO.GETRANDOMVALUES(ARRAY);
  return Array.prototype.slice.call(ARRAY);
};
HANDLERS[MESSAGETYPES.GEOLOCATION] = function(ENV, MSG) {
  var WIN = typeof WINDOW !== 'undefined' ? WINDOW : (typeof SELF !== 'undefined' ? SELF : (typeof GLOBAL !== 'undefined' ? GLOBAL : null));
  var GEO = WIN.NAVIGATOR && WIN.NAVIGATOR.GEOLOCATION;
  if (!GEO) {
    RESPONDIFNEEDED(ENV, MSG, { ERROR: 'geolocation API unavailable' });
    return;
  }
  GEO.GETCURRENTPOSITION(
    function(POS) { RESPONDIFNEEDED(ENV, MSG, { LATITUDE: POS.COORDS.LATITUDE, LONGITUDE: POS.COORDS.LONGITUDE, ACCURACY: POS.COORDS.ACCURACY }); },
    function(ERR) { RESPONDIFNEEDED(ENV, MSG, { ERROR: 'geolocation failed: ' + ERR.MESSAGE }); },
    { ENABLEHIGHACCURACY: MSG.ENABLEHIGHACCURACY || false, TIMEOUT: MSG.TIMEOUT || 5000 }
  );
};
HANDLERS[MESSAGETYPES.PERSISTENCE] = function(ENV, MSG) {
  var WIN = typeof WINDOW !== 'undefined' ? WINDOW : (typeof SELF !== 'undefined' ? SELF : (typeof GLOBAL !== 'undefined' ? GLOBAL : null));
  var STORAGE = WIN.LOCALSTORAGE;
  if (!STORAGE) return { ERROR: 'localStorage unavailable' };
  try {
    if (MSG.ACTION === 'getItem') return { VALUE: STORAGE.GETITEM(MSG.KEY) };
    else if (MSG.ACTION === 'setItem') { STORAGE.SETITEM(MSG.KEY, MSG.VALUE); return { SUCCESS: true }; }
    else if (MSG.ACTION === 'removeItem') { STORAGE.REMOVEITEM(MSG.KEY); return { SUCCESS: true }; }
    else if (MSG.ACTION === 'clear') { STORAGE.CLEAR(); return { SUCCESS: true }; }
    else return { ERROR: 'unknown persistence action: ' + MSG.ACTION };
  } catch (ERR) { return { ERROR: ERR.MESSAGE }; }
};
HANDLERS[MESSAGETYPES.CREATEELEMENT] = function(ENV, MSG) {
  try {
    var EL = DOCUMENT.CREATEELEMENT(MSG.TAG);
    if (MSG.PROPS) Object.keys(MSG.PROPS).forEach(function(PROP) { EL[PROP] = MSG.PROPS[PROP]; });
    var REG = ENV.RENDER && (ENV.RENDER.ACTORREGISTRY || ENV.RENDER.ACTORREGISTRY);
    var DOMREFFN = (typeof CREATEDOMREF === 'function') ? CREATEDOMREF : (typeof CREATEDOMREF === 'function' ? CREATEDOMREF : function(E) { return E; });
    return DOMREFFN(EL, REG);
  } catch (ERR) { return { ERROR: ERR.MESSAGE }; }
};
HANDLERS[MESSAGETYPES.CREATECONTAINER] = function(ENV, MSG) {
  try {
    var REG2 = ENV.RENDER && (ENV.RENDER.ACTORREGISTRY || ENV.RENDER.ACTORREGISTRY);
    var DOMREFFN2 = (typeof CREATEDOMREF === 'function') ? CREATEDOMREF : (typeof CREATEDOMREF === 'function' ? CREATEDOMREF : function(E) { return E; });
    return DOMREFFN2(DOCUMENT.CREATEELEMENT('div'), REG2);
  } catch (ERR) { return { ERROR: ERR.MESSAGE }; }
};
HANDLERS[MESSAGETYPES.CREATEFROMHTML] = function(ENV, MSG) {
  try {
    var WRAPPER = DOCUMENT.CREATEELEMENT('div');
    WRAPPER.INNERHTML = MSG.HTML;
    var CHILD = WRAPPER.FIRSTELEMENTCHILD || WRAPPER;
    var REG3 = ENV.RENDER && (ENV.RENDER.ACTORREGISTRY || ENV.RENDER.ACTORREGISTRY);
    var DOMREFFN3 = (typeof CREATEDOMREF === 'function') ? CREATEDOMREF : (typeof CREATEDOMREF === 'function' ? CREATEDOMREF : function(E) { return E; });
    return DOMREFFN3(CHILD, REG3);
  } catch (ERR) { return { ERROR: ERR.MESSAGE }; }
};
HANDLERS[MESSAGETYPES.PROPERTY] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  var FN = EL[MSG.NAME];
  if (typeof FN !== 'function') return { ERROR: 'property "' + MSG.NAME + '" is not a function' };
  try { return FN.APPLY(EL, MSG.ARGUMENTS || []); } catch (E) { return { ERROR: E.MESSAGE }; }
};
HANDLERS[MESSAGETYPES.GETHTML] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  return { TAG: EL.TAGNAME.TOLOWERCASE(), INNERHTML: EL.INNERHTML };
};
HANDLERS[MESSAGETYPES.GETVALUE] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  return EL.VALUE;
};
HANDLERS[MESSAGETYPES.GETSTYLE] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  var COMPUTED = WINDOW.GETCOMPUTEDSTYLE(EL);
  var STYLEOBJ = Array.prototype.slice.call(COMPUTED).reduce(function(ACC, PROP) {
    ACC[PROP] = COMPUTED.GETPROPERTYVALUE(PROP);
    return ACC;
  }, {});
  return STYLEOBJ;
};
HANDLERS[MESSAGETYPES.GETPOSITION] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  var RECT = EL.GETBOUNDINGCLIENTRECT();
  return { X: RECT.X, Y: RECT.Y, WIDTH: RECT.WIDTH, HEIGHT: RECT.HEIGHT, TOP: RECT.TOP, RIGHT: RECT.RIGHT, BOTTOM: RECT.BOTTOM, LEFT: RECT.LEFT };
};
HANDLERS[MESSAGETYPES.GETLAYOUT] = function(ENV, MSG) {
  var EL = DOCUMENT.GETELEMENTBYID(MSG.ID);
  if (!EL) return { ERROR: 'element not found: ' + MSG.ID };
  return {
    OFFSETWIDTH: EL.OFFSETWIDTH, OFFSETHEIGHT: EL.OFFSETHEIGHT,
    OFFSETLEFT: EL.OFFSETLEFT, OFFSETTOP: EL.OFFSETTOP,
    SCROLLWIDTH: EL.SCROLLWIDTH, SCROLLHEIGHT: EL.SCROLLHEIGHT,
    CLIENTWIDTH: EL.CLIENTWIDTH, CLIENTHEIGHT: EL.CLIENTHEIGHT
  };
};
HANDLERS[MESSAGETYPES.SETHTML] = function(ENV, MSG) {
  WAITFORDOMREADY().then(function() {
    WITHELEMENTRETRY(MSG.ID, null, function(EL) { EL.INNERHTML = MSG.VALUE; });
    RESPONDIFNEEDED(ENV, MSG, true);
  }).catch(function(ERR) {
    RESPONDIFNEEDED(ENV, MSG, { ERROR: ERR.MESSAGE || String(ERR) });
  });
};
HANDLERS[MESSAGETYPES.SETPOSITION] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { Object.keys(MSG.VALUE || {}).forEach(function(PROP) { EL.STYLE[PROP] = MSG.VALUE[PROP]; }); });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.SETSTYLE] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { Object.keys(MSG.VALUE || {}).forEach(function(PROP) { EL.STYLE[PROP] = MSG.VALUE[PROP]; }); });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.SETVALUE] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { EL.VALUE = MSG.VALUE; });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.SETLAYOUT] = function(ENV, MSG) {
  WITHELEMENTRETRY(MSG.ID, null, function(EL) { Object.keys(MSG.VALUE || {}).forEach(function(PROP) { EL[PROP] = MSG.VALUE[PROP]; }); });
  RESPONDIFNEEDED(ENV, MSG, true);
};
HANDLERS[MESSAGETYPES.GETVIEWPORT] = function(ENV, MSG) {
  var DOC = DOCUMENT.DOCUMENTELEMENT;
  return { VIEWPORTWIDTH: DOC.CLIENTWIDTH, VIEWPORTHEIGHT: DOC.CLIENTHEIGHT };
};
HANDLERS[MESSAGETYPES.GETSCREEN] = function(ENV, MSG) {
  var SCR = WINDOW.SCREEN;
  return { SCREENWIDTH: SCR.WIDTH, SCREENHEIGHT: SCR.HEIGHT, AVAILWIDTH: SCR.AVAILWIDTH, AVAILHEIGHT: SCR.AVAILHEIGHT };
};
HANDLERS[MESSAGETYPES.MATCHMEDIA] = function(ENV, MSG) {
  return { MATCHES: WINDOW.MATCHMEDIA(MSG.QUERY).MATCHES };
};
HANDLERS[MESSAGETYPES.GETBODYHTML || MESSAGETYPES.GET_BODY_HTML] = function(ENV, MSG) {
  return DOCUMENT.BODY ? DOCUMENT.BODY.INNERHTML : '';
};
HANDLERS[MESSAGETYPES.RESTOREBODYHTML || MESSAGETYPES.RESTORE_BODY_HTML] = function(ENV, MSG) {
  WAITFORDOMREADY().then(function() {
    if (DOCUMENT.BODY) DOCUMENT.BODY.INNERHTML = MSG.HTML;
    RESPONDIFNEEDED(ENV, MSG, true);
  }).catch(function(ERR) {
    RESPONDIFNEEDED(ENV, MSG, { ERROR: ERR.MESSAGE || String(ERR) });
  });
};
HANDLERS[MESSAGETYPES.RECOVER] = function(ENV, MSG) {
  WAITFORDOMREADY().then(function() {
    return DBRESTORE('ACTOR:STATE:RENDER').then(function(SAVED) {
      if (SAVED !== null && SAVED !== undefined) {
        ENV.RENDER = SAVED;
      } else {
        ENV.RENDER = { HTML: '', VIEWPORT: null, ACTORREGISTRY: null, SCRIPTTAGS: [] };
      }
      SCHEDULEGCCYCLE(ENV.RENDER);
      REINJECTSCRIPTTAGS(ENV.RENDER.SCRIPTTAGS || ENV.RENDER.SCRIPTTAGS || []);
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'RENDER', VALUE: ENV.RENDER }]
      }, GENERATETAG(), 'RENDERACTOR');
      RESPONDIFNEEDED(ENV, MSG, ENV);
    }).catch(function(E) {
      ENV.RENDER = { HTML: '', VIEWPORT: null, ACTORREGISTRY: null, SCRIPTTAGS: [] };
      SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
        UPDATES: [{ PATH: 'RENDER', VALUE: ENV.RENDER }]
      }, GENERATETAG(), 'RENDERACTOR');
      RESPONDIFNEEDED(ENV, MSG, { ERROR: E.MESSAGE || String(E) });
    });
  }).catch(function(ERR) {
    RESPONDIFNEEDED(ENV, MSG, { ERROR: ERR.MESSAGE || String(ERR) });
  });
};
HANDLERS[MESSAGETYPES.PING] = function(ENV, MSG) { return true; };

var REGLISTENERKEY = MESSAGETYPES.REGISTEREVENTLISTENER || MESSAGETYPES.REGISTER_EVENT_LISTENER;
HANDLERS[REGLISTENERKEY] = function(ENV, MSG) {
  var RENDERSLICE = ENSURERENDERSLICE(ENV);
  var GC = RENDERSLICE.GC || RENDERSLICE._GC;
  if (!GC) {
    GC = (typeof CREATEGARBAGECOLLECTOR === 'function') ? CREATEGARBAGECOLLECTOR() : CREATEGARBAGECOLLECTOR();
    RENDERSLICE.GC = GC;
  }

  LOGINFO(ENV, '[RENDERACTOR]', 'REGISTEREVENTLISTENER START:', {
    SOURCEID: MSG.SOURCEID,
    EVENT: MSG.EVENT,
    PIPELINEID: MSG.PIPELINEID || MSG.PIPELINEID,
    STAGEID: MSG.STAGEID || MSG.STAGEID
  });

  var PC = CREATEEVENTPRODUCERCONSUMER(MSG);
  var LISTFN = (typeof LISTOBJECTS === 'function') ? LISTOBJECTS : LISTOBJECTS;
  var REGOBJFN = (typeof REGISTEROBJECT === 'function') ? REGISTEROBJECT : REGISTEROBJECT;
  var INCRECVFN = (typeof INCREMENTRECEIVED === 'function') ? INCREMENTRECEIVED : INCREMENTRECEIVED;

  var EXISTING = LISTFN(GC).filter(function(OBJ) {
    var P = OBJ.PRODUCER || {};
    var C = OBJ.CONSUMER || {};
    return P.ID === PC.PRODUCER.ID && P.EVENT === PC.PRODUCER.EVENT &&
      (C.PIPELINEID || C.PIPELINEID) === (PC.CONSUMER.PIPELINEID || PC.CONSUMER.PIPELINEID) &&
      (C.STAGEID || C.STAGEID) === (PC.CONSUMER.STAGEID || PC.CONSUMER.STAGEID);
  })[0];

  if (EXISTING) {
    LOGINFO(ENV, '[RENDERACTOR]', 'EVENT LISTENER ALREADY REGISTERED FOR', MSG.SOURCEID, MSG.EVENT);
    EXISTING.METADATA = PC.METADATA;
    EXISTING.STATUS = 'EXPECTING';
    EXISTING.SENTCOUNT = 0;
    EXISTING.RECEIVEDCOUNT = 1;
  } else {
    var GCOBJECT = {
      PRODUCER: PC.PRODUCER,
      CONSUMER: PC.CONSUMER,
      METADATA: PC.METADATA,
      STATUS: 'EXPECTING',
      SENTCOUNT: 0,
      RECEIVEDCOUNT: 0
    };
    REGOBJFN(GC, GCOBJECT);
    INCRECVFN(GC, GCOBJECT.ID, 1);
    ENSUREEVENTOBSERVER(RENDERSLICE);
    LOGINFO(ENV, '[RENDERACTOR]', 'EVENT LISTENER REGISTERED:', MSG.SOURCEID, MSG.EVENT, 'FOR STAGE', MSG.STAGEID || MSG.STAGEID);
  }

  SCHEDULEGCCYCLE(RENDERSLICE);
  SENDINSTRUCTION('WORLDMAPACTOR', MESSAGETYPES.UPDATE, {
    UPDATES: [{ PATH: 'RENDER', VALUE: RENDERSLICE }]
  }, GENERATETAG(), 'RENDERACTOR');

  return { REGISTERED: true, SOURCEID: MSG.SOURCEID, EVENT: MSG.EVENT };
};

function RESPONDIFNEEDED(ENV, MESSAGE, RESULT) {
  if (MESSAGE.SENDER && MESSAGE.TAG) {
    var RESPONSESPEC = MESSAGE.RESPONSESPEC || MESSAGE.RESPONSESPEC;
    var DOMRESULTTYPE = MESSAGETYPES.DOMRESULT || MESSAGETYPES.DOM_RESULT;
    var RESPONSETYPE = (RESPONSESPEC && (RESPONSESPEC.RESPONSETYPE || RESPONSESPEC.RESPONSETYPE)) || DOMRESULTTYPE;
    SENDRESPONSE(MESSAGE.SENDER, MESSAGE.TAG, RESULT, 'RENDERACTOR', RESPONSETYPE);
  }
}

function REINJECTSCRIPTTAGS(SCRIPTTAGS) {
  if (!SCRIPTTAGS || !SCRIPTTAGS.length || typeof DOCUMENT === 'undefined') return;
  var EXISTINGSRCS = {};
  Array.prototype.slice.call(DOCUMENT.HEAD.GETELEMENTSBYTAGNAME('script')).forEach(function(S) {
    if (S.SRC) EXISTINGSRCS[S.SRC] = true;
  });
  SCRIPTTAGS.forEach(function(SRC) {
    if (!EXISTINGSRCS[SRC]) {
      var SCRIPT = DOCUMENT.CREATEELEMENT('script');
      SCRIPT.SRC = SRC;
      DOCUMENT.HEAD.APPENDCHILD(SCRIPT);
      LOGINFO({}, '[RENDERACTOR]', 'RE-INJECTED SCRIPT TAG:', SRC);
    }
  });
}

// Pure behavior function: (env, message) -> env
function RENDERBEHAVIOR(ENV, MESSAGE) {
  LOGDEBUG(ENV, '[RENDERACTOR]', 'BEHAVIOR HANDLING ACTION:', MESSAGE.TYPE, MESSAGE.ID || '');
  var RENDERSLICE = ENSURERENDERSLICE(ENV);
  var HANDLER = HANDLERS[MESSAGE.TYPE];
  if (HANDLER) {
    var RESULT = HANDLER(ENV, MESSAGE);
    if (RESULT !== undefined) {
      RESPONDIFNEEDED(ENV, MESSAGE, RESULT);
    }
  }
  return ENV;
}

function CREATEENQUEUER(TYPE, IDREQUIRED, EXTRAPAYLOADFN) {
  return function() {
    var ARGS = Array.prototype.slice.call(arguments);
    var ID, REST;
    if (IDREQUIRED) { ID = ARGS[0]; REST = ARGS.slice(1); } else { ID = undefined; REST = ARGS; }
    var TAG = GENERATETAG();
    var PAYLOAD = IDREQUIRED ? { ID: ID } : {};
    if (EXTRAPAYLOADFN) {
      var EXTRA = EXTRAPAYLOADFN(REST);
      Object.keys(EXTRA).forEach(function(KEY) { PAYLOAD[KEY] = EXTRA[KEY]; });
    }
    var RESPONSESPEC = undefined;
    if (arguments.length > 0) {
      var LASTARG = arguments[arguments.length - 1];
      if (LASTARG && typeof LASTARG === 'object' && (LASTARG.RESPONSETYPE || LASTARG.RESPONSETYPE)) {
        RESPONSESPEC = LASTARG;
      }
    }
    SENDINSTRUCTION('RENDERACTOR', TYPE, PAYLOAD, TAG, 'system', RESPONSESPEC);
  };
}

var ENQUEUERENDER = CREATEENQUEUER(MESSAGETYPES.RENDER, true, function(REST) { return { RENDERER: REST[0], DATA: REST[1], ENV: REST[2] }; });
var ENQUEUECLEAR = CREATEENQUEUER(MESSAGETYPES.CLEAR, true);
var ENQUEUEHTML = CREATEENQUEUER(MESSAGETYPES.HTML, true, function(REST) { return { MARKUP: REST[0], APPEND: REST[1] }; });
var ENQUEUEREMOVE = CREATEENQUEUER(MESSAGETYPES.REMOVE, true);
var ENQUEUESTYLES = CREATEENQUEUER(MESSAGETYPES.SETSTYLES, true, function(REST) { return { STYLES: REST[0] }; });
var ENQUEUESETATTR = CREATEENQUEUER(MESSAGETYPES.SETATTR, true, function(REST) { return { NAME: REST[0], VALUE: REST[1] }; });
var ENQUEUETOGGLECLASS = CREATEENQUEUER(MESSAGETYPES.TOGGLECLASS, true, function(REST) { return { CLASSNAME: REST[0], FORCE: REST[1] }; });
var ENQUEUECREATEELEMENT = CREATEENQUEUER(MESSAGETYPES.CREATEELEMENT, false, function(REST) { return { TAG: REST[0], PROPS: REST[1] }; });
var ENQUEUECREATECONTAINER = CREATEENQUEUER(MESSAGETYPES.CREATECONTAINER, false);
var ENQUEUECREATEFROMHTML = CREATEENQUEUER(MESSAGETYPES.CREATEFROMHTML, false, function(REST) { return { HTML: REST[0] }; });
var ENQUEUEGETHTML = CREATEENQUEUER(MESSAGETYPES.GETHTML, true);
var ENQUEUEGETVALUE = CREATEENQUEUER(MESSAGETYPES.GETVALUE, true);
var ENQUEUEGETSTYLE = CREATEENQUEUER(MESSAGETYPES.GETSTYLE, true);
var ENQUEUEGETPOSITION = CREATEENQUEUER(MESSAGETYPES.GETPOSITION, true);
var ENQUEUEGETLAYOUT = CREATEENQUEUER(MESSAGETYPES.GETLAYOUT, true);
var ENQUEUESETHTML = CREATEENQUEUER(MESSAGETYPES.SETHTML, true, function(REST) { return { VALUE: REST[0] }; });
var ENQUEUESETPOSITION = CREATEENQUEUER(MESSAGETYPES.SETPOSITION, true, function(REST) { return { VALUE: REST[0] }; });
var ENQUEUESETSTYLE = CREATEENQUEUER(MESSAGETYPES.SETSTYLE, true, function(REST) { return { VALUE: REST[0] }; });
var ENQUEUESETVALUE = CREATEENQUEUER(MESSAGETYPES.SETVALUE, true, function(REST) { return { VALUE: REST[0] }; });
var ENQUEUEPROPERTY = CREATEENQUEUER(MESSAGETYPES.PROPERTY, true, function(REST) { return { NAME: REST[0], ARGUMENTS: REST[1] }; });
var ENQUEUESETLAYOUT = CREATEENQUEUER(MESSAGETYPES.SETLAYOUT, true, function(REST) { return { VALUE: REST[0] }; });
var ENQUEUEGETVIEWPORT = CREATEENQUEUER(MESSAGETYPES.GETVIEWPORT, false);
var ENQUEUEGETSCREEN = CREATEENQUEUER(MESSAGETYPES.GETSCREEN, false);
var ENQUEUEMATCHMEDIA = CREATEENQUEUER(MESSAGETYPES.MATCHMEDIA, false, function(REST) { return { QUERY: REST[0] }; });

function ENQUEUERENDERREGISTERTRIGGER(REGISTRATION, RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERREGISTERTRIGGER; USE BLOCKCOMPILER REGISTER_EVENT_LISTENER INSTEAD');
  return undefined;
}
function ENQUEUERENDERREGISTERTRIGGEREXPECTATION(REGISTRATION, RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERREGISTERTRIGGEREXPECTATION; USE BLOCKCOMPILER REGISTER_EVENT_LISTENER INSTEAD');
  return undefined;
}
function ENQUEUERENDERREVALIDATETRIGGERS(RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERREVALIDATETRIGGERS; NO LONGER NEEDED');
  return undefined;
}
function ENQUEUERENDERPING(RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERPING; USE ENQUEUERENDER... OR DIRECT MESSAGE');
  return undefined;
}
function ENQUEUERENDERGETBODYHTML(RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERGETBODYHTML; USE GET_BODY_HTML MESSAGE DIRECTLY');
  return undefined;
}
function ENQUEUERENDERRESTOREBODYHTML(HTML, RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERRESTOREBODYHTML; USE RESTORE_BODY_HTML MESSAGE DIRECTLY');
  return undefined;
}
function ENQUEUERENDERRECOVER(RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERRECOVER; USE RECOVER MESSAGE DIRECTLY');
  return undefined;
}
function ENQUEUERENDERCRYPTO(BYTES, RESPONSESPEC) {
  LOGWARN({}, '[RENDERACTOR]', 'DEPRECATED ENQUEUER CALLED: ENQUEUERENDERCRYPTO; USE CRYPTO MESSAGE DIRECTLY');
  return undefined;
}

var STARTRENDERACTOR = function(OPTIONS) {
  if (OPTIONS !== undefined) {
    var LVL = typeof OPTIONS === 'number' ? OPTIONS :
      (OPTIONS && OPTIONS.VERBOSITY !== undefined ? OPTIONS.VERBOSITY : (OPTIONS && OPTIONS.VERBOSITYLEVEL));
    if (LVL !== undefined) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      if (ENV) ENV.VERBOSITY = LVL;
    }
  }
  return {
    GETSTATE: function() { return GETACTORSTATE('WORLDMAPACTOR'); },
    DISPATCH: function(MESSAGE) { return DISPATCHTOACTOR('RENDERACTOR', RENDERBEHAVIOR, MESSAGE); }
  };
};

var EXPECTELEMENT = function(ID, TIMEOUT) {
  if (TIMEOUT === undefined) TIMEOUT = 30000;
  return new Promise(function(RESOLVE, REJECT) {
    var EXISTING = DOCUMENT.GETELEMENTBYID(ID);
    var DOMREFFN = (typeof CREATEDOMREF === 'function') ? CREATEDOMREF : (typeof CREATEDOMREF === 'function' ? CREATEDOMREF : function(E) { return E; });
    if (EXISTING) {
      var ENV = GETACTORSTATE('WORLDMAPACTOR');
      var REG = ENV && ENV.RENDER && (ENV.RENDER.ACTORREGISTRY || ENV.RENDER.ACTORREGISTRY);
      return RESOLVE(DOMREFFN(EXISTING, REG));
    }
    var OBSERVER = null;
    var TIMEOUTID = setTimeout(function() { if (OBSERVER) OBSERVER.DISCONNECT(); REJECT(new Error('[EXPECTELEMENT] ELEMENT NOT FOUND: ' + ID)); }, TIMEOUT);
    OBSERVER = new MUTATIONOBSERVER(function() {
      var EL = DOCUMENT.GETELEMENTBYID(ID);
      if (EL) {
        clearTimeout(TIMEOUTID);
        OBSERVER.DISCONNECT();
        var ENVNOW = GETACTORSTATE('WORLDMAPACTOR');
        var REGNOW = ENVNOW && ENVNOW.RENDER && (ENVNOW.RENDER.ACTORREGISTRY || ENVNOW.RENDER.ACTORREGISTRY);
        RESOLVE(DOMREFFN(EL, REGNOW));
      }
    });
    OBSERVER.OBSERVE(DOCUMENT.BODY, { CHILDLIST: true, SUBTREE: true });
  });
};

var EXPECTELEMENTALIAS = EXPECTELEMENT;

var HANDLEFILEREADERREQUEST = function(PAYLOAD) {
  return new Promise(function(RESOLVE, REJECT) {
    var READER = new FILEREADER();
    READER.ONLOAD = function(E) { RESOLVE({ TEXT: E.TARGET.RESULT }); };
    READER.ONERROR = function() { REJECT(new Error('[RENDERACTOR] FileReader error')); };
    READER.READASTEXT(PAYLOAD.FILE);
  });
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    RENDERVERBOSITYCONSTANTS: RENDERVERBOSITYCONSTANTS,
    ENSURERENDERSLICE: ENSURERENDERSLICE,
    CREATERENDERERRORCONTEXT: CREATERENDERERRORCONTEXT,
    WITHELEMENT: WITHELEMENT,
    WITHELEMENTRETRY: WITHELEMENTRETRY,
    WAITFORDOMREADY: WAITFORDOMREADY,
    CREATEEVENTPRODUCERCONSUMER: CREATEEVENTPRODUCERCONSUMER,
    SCHEDULEGCCYCLE: SCHEDULEGCCYCLE,
    ENSUREEVENTOBSERVER: ENSUREEVENTOBSERVER,
    RENDERBEHAVIOR: RENDERBEHAVIOR,
    CREATEENQUEUER: CREATEENQUEUER,
    ENQUEUERENDER: ENQUEUERENDER,
    ENQUEUECLEAR: ENQUEUECLEAR,
    ENQUEUEHTML: ENQUEUEHTML,
    ENQUEUEREMOVE: ENQUEUEREMOVE,
    ENQUEUESTYLES: ENQUEUESTYLES,
    ENQUEUESETATTR: ENQUEUESETATTR,
    ENQUEUETOGGLECLASS: ENQUEUETOGGLECLASS,
    ENQUEUECREATEELEMENT: ENQUEUECREATEELEMENT,
    ENQUEUECREATECONTAINER: ENQUEUECREATECONTAINER,
    ENQUEUECREATEFROMHTML: ENQUEUECREATEFROMHTML,
    ENQUEUEGETHTML: ENQUEUEGETHTML,
    ENQUEUEGETVALUE: ENQUEUEGETVALUE,
    ENQUEUEGETSTYLE: ENQUEUEGETSTYLE,
    ENQUEUEGETPOSITION: ENQUEUEGETPOSITION,
    ENQUEUEGETLAYOUT: ENQUEUEGETLAYOUT,
    ENQUEUESETHTML: ENQUEUESETHTML,
    ENQUEUESETPOSITION: ENQUEUESETPOSITION,
    ENQUEUESETSTYLE: ENQUEUESETSTYLE,
    ENQUEUESETVALUE: ENQUEUESETVALUE,
    ENQUEUEPROPERTY: ENQUEUEPROPERTY,
    ENQUEUESETLAYOUT: ENQUEUESETLAYOUT,
    ENQUEUEGETVIEWPORT: ENQUEUEGETVIEWPORT,
    ENQUEUEGETSCREEN: ENQUEUEGETSCREEN,
    ENQUEUEMATCHMEDIA: ENQUEUEMATCHMEDIA,
    STARTRENDERACTOR: STARTRENDERACTOR,
    EXPECTELEMENT: EXPECTELEMENT,
    EXPECTELEMENTALIAS: EXPECTELEMENTALIAS,
    HANDLEFILEREADERREQUEST: HANDLEFILEREADERREQUEST
  };
}
