import { 
  contrastRatio, computeForeground, emphasize,
  complementary, analogous, monochromatic, pick, 
  getContrastingPalette, getHarmoniousPalette, colorHarmonyScore,
  hexToRgb, rgbToHsl, hslToRgb, rgbToHex, 
  extractInlineStyle 
} from './colorutils.js';
import { logdebug, getverbosity, VERBOSITY } from '../verbosity.js';

// ==================== RECURSIVE PATH ENGINE (unchanged) ====================
// ... (existing getAncestors, getAllDescendants, getNextSiblings, getPreviousSiblings, getDepth, applyStep, resolvePath)

// ==================== STYLIZER FUNCTION (unchanged) ====================

export function rewritestyleattrs(html, rules) {
  var doc = new DOMParser().parseFromString(html, 'text/html');
  var body = doc.body;
  for (var ri = 0; ri < rules.length; ri++) {
    var rule = rules[ri];
    var els = [];
    if (rule.path) {
      els = resolvePath(body, rule.path);
    } else {
      if (rule.id)      els = [doc.getElementById(rule.id)];
      if (rule.tag)     els = doc.getElementsByTagName(rule.tag);
      if (rule.class)   els = doc.getElementsByClassName(rule.class);
      if (rule.name)    els = [doc.getElementByName(rule.name)];
    }

    var eli = -1;
    while (eli < els.length) {
      eli = eli + 1;
      var el = els[eli];
      if (!el) continue;
      var newstyle = rule.style;
      if (newstyle) {
        var newkeys = Object.keys(newstyle);
        for (var ni = 0; ni < newkeys.length; ni++) {
          try {
            el.style[newkeys[ni]] = newstyle[newkeys[ni]];
          } catch(e) {
            console.log({e});
          }
        }
      }
    }
  }
  return body.innerHTML;
}

// ==================== COLOR SCHEME UTILITY (unchanged) ====================

export function computecolorscheme(pos, tilecols, cellw, cellh, gridcols) {
  // ... (original implementation)
}

// ==================== RESPONSIVE STYLES INJECTION (unchanged) ====================

export function injectResponsiveStyles(html, breakpointRules) {
  // ... (original implementation)
}

// ==================== NEW: TAG STYLE EXTRACTION ====================

/**
 * Parses a theme reference HTML and returns a map of tag names to their complete inline style objects.
 * The reference must contain one element per tag under #theme-reference.
 * @param {string} referenceHTML - HTML string generated by generateThemeReference
 * @returns {Object} { tagName: { styleProp: value, ... } }
 */
export function extractAllTagStyles(referenceHTML) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(referenceHTML, 'text/html');
  const refRoot = doc.getElementById('theme-reference');
  if (!refRoot) return {};
  
  const map = {};
  const children = Array.from(refRoot.children);
  for (const el of children) {
    const tag = el.tagName.toLowerCase();
    const styleObj = {};
    for (let i = 0; i < el.style.length; i++) {
      const prop = el.style[i];
      styleObj[prop] = el.style[prop];
    }
    if (Object.keys(styleObj).length > 0) {
      map[tag] = styleObj;
    }
  }
  return map;
}

// ==================== NEW: STYLE CONSOLIDATION ====================

/**
 * Removes redundant inherited inline style properties from child elements.
 * @param {string} html 
 * @returns {string} optimized HTML
 */
export function consolidateStyles(html) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const safeProps = new Set([
    'color', 'font-family', 'font-size', 'font-weight', 'font-style', 
    'line-height', 'text-align', 'cursor', 'letter-spacing', 'word-spacing'
  ]);
  
  function walk(el) {
    const children = Array.from(el.children);
    const parentStyle = el.style;
    for (const child of children) {
      if (!child.style) continue;
      const toRemove = [];
      for (let i = 0; i < child.style.length; i++) {
        const prop = child.style[i];
        if (safeProps.has(prop) && parentStyle[prop] === child.style[prop]) {
          toRemove.push(prop);
        }
      }
      for (const prop of toRemove) {
        child.style.removeProperty(prop);
      }
      walk(child);
    }
  }
  walk(doc.body);
  return doc.body.innerHTML;
}

// ==================== NEW: DESIGN VERIFICATION ====================

/**
 * Auto‑corrects text‑background contrast to meet WCAG AA (4.5:1).
 * Uses vector palette from colorutils to pick best replacement.
 * @param {string} html 
 * @param {number} minRatio 
 * @returns {string} corrected HTML
 */
export function verifyContrast(html, minRatio = 4.5) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  
  function getEffectiveBackground(el) {
    let bg = el.style.backgroundColor;
    let parent = el.parentNode;
    while ((!bg || bg === 'transparent' || bg === '') && parent && parent !== doc) {
      if (parent.style) bg = parent.style.backgroundColor;
      parent = parent.parentNode;
    }
    return bg || '#ffffff';
  }
  
  function walk(el) {
    if (el.nodeType === 1 && el.textContent.trim()) {
      const color = el.style.color;
      const bg = getEffectiveBackground(el);
      if (color && bg) {
        const ratio = contrastRatio(color, bg);
        if (ratio < minRatio) {
          const palette = getContrastingPalette(bg, minRatio);
          if (palette.length > 0) {
            el.style.color = palette[0]; // least contrasting that still meets min
          } else {
            // fallback to computed foreground
            el.style.color = computeForeground(color, bg, minRatio);
          }
        }
      }
    }
    for (const child of el.children) {
      walk(child);
    }
  }
  walk(doc.body);
  return doc.body.innerHTML;
}

/**
 * Checks that text elements have visible font size, contrast, and line height.
 * @param {string} html 
 * @returns {object[]} violations
 */
export function verifyTextVisibility(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  function walk(el) {
    if (el.nodeType === 1 && el.textContent.trim()) {
      const fontSize = parseFloat(el.style.fontSize) || 0;
      const lineHeight = parseFloat(el.style.lineHeight) || 0;
      const color = el.style.color;
      if (fontSize && fontSize < 12) {
        violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'font-size too small', value: fontSize });
      }
      if (lineHeight && lineHeight < 1.2) {
        violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'line-height too tight', value: lineHeight });
      }
      if (!color || color === 'transparent') {
        violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'text color not set or transparent' });
      }
    }
    for (const child of el.children) walk(child);
  }
  walk(doc.body);
  return violations;
}

/**
 * Verifies buttons are visually distinct (size, contrast, cursor).
 * @param {string} html 
 * @returns {object[]} violations
 */
export function verifyButtonVisibility(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const buttons = doc.querySelectorAll('button, [role="button"], input[type="submit"], input[type="button"]');
  buttons.forEach(btn => {
    const width = parseFloat(btn.style.width) || 0;
    const height = parseFloat(btn.style.height) || 0;
    const fontSize = parseFloat(btn.style.fontSize) || 0;
    const cursor = btn.style.cursor;
    if (width < 44 || height < 44) {
      violations.push({ element: btn.tagName + (btn.id ? '#'+btn.id : ''), issue: 'touch target too small', w: width, h: height });
    }
    if (cursor !== 'pointer') {
      violations.push({ element: btn.tagName + (btn.id ? '#'+btn.id : ''), issue: 'cursor not pointer' });
    }
  });
  return violations;
}

/**
 * Scores harmony between adjacent elements (color harmony) and reports poor combinations.
 * Can optionally correct using harmonious palette.
 * @param {string} html 
 * @param {object} options { autoCorrect: boolean }
 * @returns {object} { html?, violations[] }
 */
export function verifyHarmony(html, options = {}) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const allElements = doc.querySelectorAll('*');
  allElements.forEach(el => {
    if (!el.textContent.trim()) return;
    const bg = el.style.backgroundColor;
    const color = el.style.color;
    if (bg && color) {
      const score = colorHarmonyScore(color, bg);
      if (score < 0.5) {
        violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), score, color, bg });
        if (options.autoCorrect) {
          const palette = getHarmoniousPalette(bg, 3, { scheme: 'analogous' });
          if (palette.length > 0) {
            el.style.color = palette[0];
          }
        }
      }
    }
  });
  return { html: options.autoCorrect ? doc.body.innerHTML : html, violations };
}

// ==================== LAYOUT VERIFICATION ====================

/**
 * Checks minimum spacing between adjacent block‑level elements.
 * @param {string} html 
 * @param {number} minGap 
 * @returns {object[]} violations
 */
export function checkSpacing(html, minGap = 12) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  
  function walk(parent) {
    const children = Array.from(parent.children).filter(el => {
      const display = el.style.display || 'inline';
      return display === 'block' || display === 'flex' || display === 'grid' || 
             ['div','section','article','header','footer','nav','p','h1','h2','h3','h4','h5','h6','li'].includes(el.tagName.toLowerCase());
    });
    for (let i = 0; i < children.length - 1; i++) {
      const a = children[i], b = children[i + 1];
      const mb = parseFloat(a.style.marginBottom) || 0;
      const mt = parseFloat(b.style.marginTop) || 0;
      if (mb + mt < minGap) {
        violations.push({
          elementA: a.tagName + (a.id ? '#'+a.id : ''),
          elementB: b.tagName + (b.id ? '#'+b.id : ''),
          gap: mb + mt
        });
      }
      walk(b);
    }
  }
  walk(doc.body);
  return violations;
}

/**
 * Detects potential overlapping elements based on explicit positioning.
 * Checks if absolute/fixed elements share the same space.
 * @param {string} html 
 * @returns {object[]} violations
 */
export function checkOverlap(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const positioned = Array.from(doc.querySelectorAll('[style*="position: absolute"], [style*="position: fixed"]'));
  for (let i = 0; i < positioned.length; i++) {
    for (let j = i + 1; j < positioned.length; j++) {
      const a = positioned[i], b = positioned[j];
      const aTop = parseFloat(a.style.top) || 0;
      const aLeft = parseFloat(a.style.left) || 0;
      const aWidth = parseFloat(a.style.width) || 0;
      const aHeight = parseFloat(a.style.height) || 0;
      const bTop = parseFloat(b.style.top) || 0;
      const bLeft = parseFloat(b.style.left) || 0;
      const bWidth = parseFloat(b.style.width) || 0;
      const bHeight = parseFloat(b.style.height) || 0;
      if (aWidth && aHeight && bWidth && bHeight) {
        if (aLeft < bLeft + bWidth && aLeft + aWidth > bLeft &&
            aTop < bTop + bHeight && aTop + aHeight > bTop) {
          violations.push({
            elementA: a.tagName + (a.id ? '#'+a.id : ''),
            elementB: b.tagName + (b.id ? '#'+b.id : ''),
            zone: { top: Math.max(aTop, bTop), left: Math.max(aLeft, bLeft),
                    bottom: Math.min(aTop+aHeight, bTop+bHeight), right: Math.min(aLeft+aWidth, bLeft+bWidth) }
          });
        }
      }
    }
  }
  return violations;
}

/**
 * Checks if any element has content that may overflow its container without proper overflow style.
 * @param {string} html 
 * @returns {object[]} violations
 */
export function checkOverflow(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  function walk(el) {
    const style = el.style;
    const overflow = style.overflow || style.overflowX || style.overflowY;
    if (el.scrollWidth > el.clientWidth || el.scrollHeight > el.clientHeight) {
      if (!overflow || overflow === 'visible') {
        violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'content overflows but overflow not set' });
      }
    }
    for (const child of el.children) walk(child);
  }
  walk(doc.body);
  return violations;
}

/**
 * Verifies that scrollable containers have appropriate styling (overflow:auto/scroll, touch action).
 * @param {string} html 
 * @returns {object[]} violations
 */
export function checkScrollability(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const scrollable = doc.querySelectorAll('[style*="overflow: auto"], [style*="overflow: scroll"]');
  scrollable.forEach(el => {
    if (el.scrollHeight <= el.clientHeight && el.scrollWidth <= el.clientWidth) {
      violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'scrollable container has no overflowing content' });
    }
    // check touch action for better mobile scroll
    if (!el.style.touchAction) {
      violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'touch-action not set for scrollable element' });
    }
  });
  return violations;
}

/**
 * Checks that overlapping elements (absolute/fixed) have a defined z‑index and appropriate opacity.
 * @param {string} html 
 * @returns {object[]} violations
 */
export function checkControlledOverlay(html) {
  const violations = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const overlays = doc.querySelectorAll('[style*="position: absolute"], [style*="position: fixed"]');
  overlays.forEach(el => {
    if (!el.style.zIndex) {
      violations.push({ element: el.tagName + (el.id ? '#'+el.id : ''), issue: 'positioned element lacks z-index' });
    }
  });
  return violations;
}

/**
 * Aggregates verification checks based on goal list.
 * @param {string} html 
 * @param {string[]} goals - e.g. ['contrast', 'spacing', 'overlap']
 * @returns {object} { passed: boolean, violations: [...], correctedHtml?: string }
 */
export function runVerification(html, goals = []) {
  const result = { passed: true, violations: [], correctedHtml: html };
  for (const goal of goals) {
    switch (goal) {
      case 'contrast':
        result.correctedHtml = verifyContrast(result.correctedHtml);
        break;
      case 'spacing': {
        const v = checkSpacing(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'overlap': {
        const v = checkOverlap(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'overflow': {
        const v = checkOverflow(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'scrollability': {
        const v = checkScrollability(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'overlay': {
        const v = checkControlledOverlay(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'textvisibility': {
        const v = verifyTextVisibility(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'buttonvisibility': {
        const v = verifyButtonVisibility(result.correctedHtml);
        if (v.length) { result.passed = false; result.violations.push(...v); }
        break;
      }
      case 'harmony': {
        const res = verifyHarmony(result.correctedHtml, { autoCorrect: true });
        result.correctedHtml = res.html;
        if (res.violations.length) { result.passed = false; result.violations.push(...res.violations); }
        break;
      }
    }
  }
  return result;
}
